#!/usr/bin/env python3
"""Generate contract-driven connection tests; independent of the RTL renderer.

This tests all lanes in both directions, modports, packed types and handshake
wires. Arbitrary pin vectors are intentional: no service algorithm is modeled.
"""

import argparse
import ast
import hashlib
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
FAMILIES = ("cci", "crypto_secret", "crypto_staging", "crypto_entropy")


def value(expr, w):
    # Current base contract uses only integer literals, DATA_W and DATA_W/8.
    if str(expr) == "DATA_W":
        return w
    if str(expr) == "DATA_W/8":
        return w // 8
    node = ast.literal_eval(str(expr))
    if type(node) is not int or node < 1:
        raise ValueError(expr)
    return node


def render(family):
    source = ROOT / "bus" / family / "contract" / f"{family}.interface.yaml"
    c = yaml.safe_load(source.read_text())
    name = c["interface"]["name"]
    a, b = [r["id"] for r in c["roles"]]
    fields = [s for ch in c["channels"] for s in ch["signals"]]
    forward = [s for s in fields if s["from"] == a]
    reverse = [s for s in fields if s["from"] == b]
    out = [
        "// SPDX-License-Identifier: Apache-2.0",
        "// Generated by examples/crypto_interfaces/generate_smoke.py; no service model.",
        "// Contract SHA256: " + hashlib.sha256(source.read_bytes()).hexdigest(),
        "`timescale 1ns/1ps",
    ]
    widths = c["parameters"][0]["constraints"]["enum"]
    for w in widths:
        req_bits = sum(value(s["width"], w) for s in forward)
        rsp_bits = sum(value(s["width"], w) for s in reverse)
        out += [
            f"module {family}_peer_{w}({name}_if.{b} link,",
            f"  input logic [{rsp_bits - 1}:0] response, output logic [{req_bits - 1}:0] observed);",
        ]
        offset = rsp_bits
        for s in reverse:
            size = value(s["width"], w)
            offset -= size
            out.append(f"  assign link.{s['id']} = response[{offset} +: {size}];")
        # Explicit flat concatenation in YAML order checks packed layout/role partition.
        out.append("  assign observed = {" + ", ".join("link." + s["id"] for s in forward) + "};")
        out += [
            "  always @(posedge link.clk) if (link.reset_n !== 1'b0 && link.reset_n !== 1'b1) $fatal(1,\"reset modport\");",
            "endmodule",
        ]
        out += [
            f"module {family}_case_{w}(input logic clk, reset_n, output logic done);",
            f"  import {name}_pkg::*;",
            f"  {name}_w{w}_req_t request;",
            f"  {name}_w{w}_rsp_t response;",
            f"  logic [{rsp_bits - 1}:0] expected;",
            f"  logic [{req_bits - 1}:0] observed;",
            f"  {name}_if #(.DATA_W({w})) link (.clk(clk), .reset_n(reset_n));",
            f"  {family}_peer_{w} peer(link, expected, observed);",
            f"  {name}_flat_wrapper #(.DATA_W({w})) bridge(.link(link),",
        ]
        connections = []
        for s in fields:
            forward_direction = s["from"] == a
            suffix = "i" if forward_direction else "o"
            container = "request" if forward_direction else "response"
            connections.append(f"    .{s['id']}_{suffix}({container}.{s['id']})")
        out += [
            ",\n".join(connections),
            "  );",
            f"  function automatic logic [{max(req_bits, rsp_bits) - 1}:0] pattern(input int seed);",
            "    int unsigned state; state=32'h9e3779b9 ^ (32'h85ebca6b * seed);",
            f"    for (int i=0;i<{max(req_bits, rsp_bits)};i++) begin",
            "      state=1664525*state+1013904223; pattern[i]=state[31];",
            "    end",
            "  endfunction",
            "  task automatic compare_paths;",
            f'    if (observed !== request) $fatal(1,"{family} W{w} forward wiring");',
            f'    if (response !== expected) $fatal(1,"{family} W{w} reverse wiring");',
            "  endtask",
            "  initial begin",
            "    done=0; request='0; expected='0;",
            f'    if ($bits(request)!={req_bits} || $bits(response)!={rsp_bits}) $fatal(1,"aggregate width");',
        ]
        for s in fields:
            out.append(
                f'    if ($bits(link.{s["id"]})!={value(s["width"], w)}) $fatal(1,"{s["id"]} width");'
            )
        for ch in c["channels"]:
            payload = sum(
                value(s["width"], w)
                for s in ch["signals"]
                if s["id"] not in [ch["id"] + "_valid", ch["id"] + "_ready"]
            )
            out.append(
                f'    if ($bits({name}_w{w}_{ch["id"]}_payload_t)!={payload}) $fatal(1,"payload width");'
            )
        if w == 128:
            out.append(
                f'    if ($bits({name}_req_t)!={req_bits} || $bits({name}_rsp_t)!={rsp_bits}) $fatal(1,"default aliases");'
            )
        for group, items in c["semantics"].items():
            if not group.endswith("_codes"):
                continue
            for item in items:
                code, label = item.split("=", 1)
                label = label.split()[0]
                constant = group.removesuffix("_codes").upper() + "_" + label
                out.append(f'    if ({constant}!={code}) $fatal(1,"{constant} encoding");')
        out += [
            "    wait(reset_n); #1; compare_paths();",
            "    request='1; expected='1; #1; compare_paths();",
            "    for (int sample=1;sample<=128;sample++) begin",
            f"      request={req_bits}'(pattern(sample)); expected={rsp_bits}'(pattern(sample+271));",
            "      #1; compare_paths();",
            "    end",
            # Walking bit patterns catch ordering, lane swaps and truncation independently.
            f"    for (int bitno=0;bitno<{req_bits};bitno++) begin",
            "      request='0; request[bitno]=1'b1; #1; compare_paths(); end",
            f"    for (int bitno=0;bitno<{rsp_bits};bitno++) begin",
            "      expected='0; expected[bitno]=1'b1; #1; compare_paths(); end",
            f'    $display("PASS {family} DATA_W={w} fields={len(fields)}"); done=1;',
            "  end",
            "endmodule",
        ]
    out += [
        f"module tb_{family};",
        "  logic clk=0; logic reset_n=0;",
        f"  logic [{len(widths) - 1}:0] done;",
        "  always #5 clk=~clk;",
        "  initial begin #20; reset_n=1; end",
    ]
    for i, w in enumerate(widths):
        out.append(f"  {family}_case_{w} case_{w}(clk,reset_n,done[{i}]);")
    out += [
        f'  initial begin wait (&done); $display("HWIF_SMOKE_PASS {family}"); $finish; end',
        '  initial begin #100000; $fatal(1,"timeout"); end',
        "endmodule",
        "",
    ]
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check-only", action="store_true")
    args = parser.parse_args()
    bad = []
    for family in FAMILIES:
        dest = ROOT / "bus" / family / "tests" / f"tb_{family}.sv"
        text = render(family)
        if args.check_only:
            if not dest.exists() or dest.read_text() != text:
                bad.append(family)
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(text)
    print("smoke source drift: " + str(bad))
    return bool(bad)


if __name__ == "__main__":
    raise SystemExit(main())
