// SPDX-License-Identifier: Apache-2.0
// Generated by examples/crypto_interfaces/generate_smoke.py; no service model.
// Contract SHA256: ab69c8e514895f51b0609b1697951f60ab5141f607ec3befd341ef261b88bdf4
`timescale 1ns/1ps
module crypto_staging_peer_32(aix_crypto_staging_if.staging link,
  input logic [822:0] response, output logic [1341:0] observed);
  assign link.req_ready = response[822 +: 1];
  assign link.rsp_valid = response[821 +: 1];
  assign link.rsp_owner_id = response[789 +: 32];
  assign link.rsp_instance_id = response[773 +: 16];
  assign link.rsp_epoch = response[741 +: 32];
  assign link.rsp_task_id = response[709 +: 32];
  assign link.rsp_request_seq = response[645 +: 64];
  assign link.rsp_context_id = response[629 +: 16];
  assign link.rsp_generation = response[597 +: 32];
  assign link.rsp_request_id = response[533 +: 64];
  assign link.rsp_status = response[517 +: 16];
  assign link.rsp_staging_ref = response[453 +: 64];
  assign link.rsp_reserved_bytes = response[389 +: 64];
  assign link.rsp_written_bytes = response[325 +: 64];
  assign link.rsp_state = response[317 +: 8];
  assign link.rsp_cleanup_done = response[316 +: 1];
  assign link.write_ready = response[315 +: 1];
  assign link.control_req_ready = response[314 +: 1];
  assign link.control_rsp_valid = response[313 +: 1];
  assign link.control_rsp_owner_id = response[281 +: 32];
  assign link.control_rsp_instance_id = response[265 +: 16];
  assign link.control_rsp_epoch = response[233 +: 32];
  assign link.control_rsp_task_id = response[201 +: 32];
  assign link.control_rsp_request_seq = response[137 +: 64];
  assign link.control_rsp_context_id = response[121 +: 16];
  assign link.control_rsp_generation = response[89 +: 32];
  assign link.control_rsp_request_id = response[25 +: 64];
  assign link.control_rsp_status = response[9 +: 16];
  assign link.control_rsp_state = response[1 +: 8];
  assign link.control_rsp_cleanup_done = response[0 +: 1];
  assign observed = {link.req_valid, link.req_owner_id, link.req_instance_id, link.req_epoch, link.req_task_id, link.req_request_seq, link.req_context_id, link.req_generation, link.req_service_version, link.req_request_id, link.req_operation, link.req_staging_ref, link.req_length, link.req_policy_epoch, link.req_auth_valid, link.req_auth_ok, link.rsp_ready, link.write_valid, link.write_owner_id, link.write_instance_id, link.write_epoch, link.write_task_id, link.write_request_seq, link.write_context_id, link.write_generation, link.write_staging_ref, link.write_offset, link.write_data, link.write_keep, link.write_last, link.control_req_valid, link.control_req_owner_id, link.control_req_instance_id, link.control_req_epoch, link.control_req_task_id, link.control_req_request_seq, link.control_req_context_id, link.control_req_generation, link.control_req_service_version, link.control_req_request_id, link.control_req_operation, link.control_req_staging_ref, link.control_req_length, link.control_req_policy_epoch, link.control_req_auth_valid, link.control_req_auth_ok, link.control_rsp_ready};
  always @(posedge link.clk) if (link.reset_n !== 1'b0 && link.reset_n !== 1'b1) $fatal(1,"reset modport");
endmodule
module crypto_staging_case_32(input logic clk, reset_n, output logic done);
  import aix_crypto_staging_pkg::*;
  aix_crypto_staging_w32_req_t request;
  aix_crypto_staging_w32_rsp_t response;
  logic [822:0] expected;
  logic [1341:0] observed;
  aix_crypto_staging_if #(.DATA_W(32)) link (.clk(clk), .reset_n(reset_n));
  crypto_staging_peer_32 peer(link, expected, observed);
  aix_crypto_staging_flat_wrapper #(.DATA_W(32)) bridge(.link(link),
    .req_valid_i(request.req_valid),
    .req_ready_o(response.req_ready),
    .req_owner_id_i(request.req_owner_id),
    .req_instance_id_i(request.req_instance_id),
    .req_epoch_i(request.req_epoch),
    .req_task_id_i(request.req_task_id),
    .req_request_seq_i(request.req_request_seq),
    .req_context_id_i(request.req_context_id),
    .req_generation_i(request.req_generation),
    .req_service_version_i(request.req_service_version),
    .req_request_id_i(request.req_request_id),
    .req_operation_i(request.req_operation),
    .req_staging_ref_i(request.req_staging_ref),
    .req_length_i(request.req_length),
    .req_policy_epoch_i(request.req_policy_epoch),
    .req_auth_valid_i(request.req_auth_valid),
    .req_auth_ok_i(request.req_auth_ok),
    .rsp_valid_o(response.rsp_valid),
    .rsp_ready_i(request.rsp_ready),
    .rsp_owner_id_o(response.rsp_owner_id),
    .rsp_instance_id_o(response.rsp_instance_id),
    .rsp_epoch_o(response.rsp_epoch),
    .rsp_task_id_o(response.rsp_task_id),
    .rsp_request_seq_o(response.rsp_request_seq),
    .rsp_context_id_o(response.rsp_context_id),
    .rsp_generation_o(response.rsp_generation),
    .rsp_request_id_o(response.rsp_request_id),
    .rsp_status_o(response.rsp_status),
    .rsp_staging_ref_o(response.rsp_staging_ref),
    .rsp_reserved_bytes_o(response.rsp_reserved_bytes),
    .rsp_written_bytes_o(response.rsp_written_bytes),
    .rsp_state_o(response.rsp_state),
    .rsp_cleanup_done_o(response.rsp_cleanup_done),
    .write_valid_i(request.write_valid),
    .write_ready_o(response.write_ready),
    .write_owner_id_i(request.write_owner_id),
    .write_instance_id_i(request.write_instance_id),
    .write_epoch_i(request.write_epoch),
    .write_task_id_i(request.write_task_id),
    .write_request_seq_i(request.write_request_seq),
    .write_context_id_i(request.write_context_id),
    .write_generation_i(request.write_generation),
    .write_staging_ref_i(request.write_staging_ref),
    .write_offset_i(request.write_offset),
    .write_data_i(request.write_data),
    .write_keep_i(request.write_keep),
    .write_last_i(request.write_last),
    .control_req_valid_i(request.control_req_valid),
    .control_req_ready_o(response.control_req_ready),
    .control_req_owner_id_i(request.control_req_owner_id),
    .control_req_instance_id_i(request.control_req_instance_id),
    .control_req_epoch_i(request.control_req_epoch),
    .control_req_task_id_i(request.control_req_task_id),
    .control_req_request_seq_i(request.control_req_request_seq),
    .control_req_context_id_i(request.control_req_context_id),
    .control_req_generation_i(request.control_req_generation),
    .control_req_service_version_i(request.control_req_service_version),
    .control_req_request_id_i(request.control_req_request_id),
    .control_req_operation_i(request.control_req_operation),
    .control_req_staging_ref_i(request.control_req_staging_ref),
    .control_req_length_i(request.control_req_length),
    .control_req_policy_epoch_i(request.control_req_policy_epoch),
    .control_req_auth_valid_i(request.control_req_auth_valid),
    .control_req_auth_ok_i(request.control_req_auth_ok),
    .control_rsp_valid_o(response.control_rsp_valid),
    .control_rsp_ready_i(request.control_rsp_ready),
    .control_rsp_owner_id_o(response.control_rsp_owner_id),
    .control_rsp_instance_id_o(response.control_rsp_instance_id),
    .control_rsp_epoch_o(response.control_rsp_epoch),
    .control_rsp_task_id_o(response.control_rsp_task_id),
    .control_rsp_request_seq_o(response.control_rsp_request_seq),
    .control_rsp_context_id_o(response.control_rsp_context_id),
    .control_rsp_generation_o(response.control_rsp_generation),
    .control_rsp_request_id_o(response.control_rsp_request_id),
    .control_rsp_status_o(response.control_rsp_status),
    .control_rsp_state_o(response.control_rsp_state),
    .control_rsp_cleanup_done_o(response.control_rsp_cleanup_done)
  );
  function automatic logic [1341:0] pattern(input int seed);
    int unsigned state; state=32'h9e3779b9 ^ (32'h85ebca6b * seed);
    for (int i=0;i<1342;i++) begin
      state=1664525*state+1013904223; pattern[i]=state[31];
    end
  endfunction
  task automatic compare_paths;
    if (observed !== request) $fatal(1,"crypto_staging W32 forward wiring");
    if (response !== expected) $fatal(1,"crypto_staging W32 reverse wiring");
  endtask
  initial begin
    done=0; request='0; expected='0;
    if ($bits(request)!=1342 || $bits(response)!=823) $fatal(1,"aggregate width");
    if ($bits(link.req_valid)!=1) $fatal(1,"req_valid width");
    if ($bits(link.req_ready)!=1) $fatal(1,"req_ready width");
    if ($bits(link.req_owner_id)!=32) $fatal(1,"req_owner_id width");
    if ($bits(link.req_instance_id)!=16) $fatal(1,"req_instance_id width");
    if ($bits(link.req_epoch)!=32) $fatal(1,"req_epoch width");
    if ($bits(link.req_task_id)!=32) $fatal(1,"req_task_id width");
    if ($bits(link.req_request_seq)!=64) $fatal(1,"req_request_seq width");
    if ($bits(link.req_context_id)!=16) $fatal(1,"req_context_id width");
    if ($bits(link.req_generation)!=32) $fatal(1,"req_generation width");
    if ($bits(link.req_service_version)!=16) $fatal(1,"req_service_version width");
    if ($bits(link.req_request_id)!=64) $fatal(1,"req_request_id width");
    if ($bits(link.req_operation)!=8) $fatal(1,"req_operation width");
    if ($bits(link.req_staging_ref)!=64) $fatal(1,"req_staging_ref width");
    if ($bits(link.req_length)!=64) $fatal(1,"req_length width");
    if ($bits(link.req_policy_epoch)!=32) $fatal(1,"req_policy_epoch width");
    if ($bits(link.req_auth_valid)!=1) $fatal(1,"req_auth_valid width");
    if ($bits(link.req_auth_ok)!=1) $fatal(1,"req_auth_ok width");
    if ($bits(link.rsp_valid)!=1) $fatal(1,"rsp_valid width");
    if ($bits(link.rsp_ready)!=1) $fatal(1,"rsp_ready width");
    if ($bits(link.rsp_owner_id)!=32) $fatal(1,"rsp_owner_id width");
    if ($bits(link.rsp_instance_id)!=16) $fatal(1,"rsp_instance_id width");
    if ($bits(link.rsp_epoch)!=32) $fatal(1,"rsp_epoch width");
    if ($bits(link.rsp_task_id)!=32) $fatal(1,"rsp_task_id width");
    if ($bits(link.rsp_request_seq)!=64) $fatal(1,"rsp_request_seq width");
    if ($bits(link.rsp_context_id)!=16) $fatal(1,"rsp_context_id width");
    if ($bits(link.rsp_generation)!=32) $fatal(1,"rsp_generation width");
    if ($bits(link.rsp_request_id)!=64) $fatal(1,"rsp_request_id width");
    if ($bits(link.rsp_status)!=16) $fatal(1,"rsp_status width");
    if ($bits(link.rsp_staging_ref)!=64) $fatal(1,"rsp_staging_ref width");
    if ($bits(link.rsp_reserved_bytes)!=64) $fatal(1,"rsp_reserved_bytes width");
    if ($bits(link.rsp_written_bytes)!=64) $fatal(1,"rsp_written_bytes width");
    if ($bits(link.rsp_state)!=8) $fatal(1,"rsp_state width");
    if ($bits(link.rsp_cleanup_done)!=1) $fatal(1,"rsp_cleanup_done width");
    if ($bits(link.write_valid)!=1) $fatal(1,"write_valid width");
    if ($bits(link.write_ready)!=1) $fatal(1,"write_ready width");
    if ($bits(link.write_owner_id)!=32) $fatal(1,"write_owner_id width");
    if ($bits(link.write_instance_id)!=16) $fatal(1,"write_instance_id width");
    if ($bits(link.write_epoch)!=32) $fatal(1,"write_epoch width");
    if ($bits(link.write_task_id)!=32) $fatal(1,"write_task_id width");
    if ($bits(link.write_request_seq)!=64) $fatal(1,"write_request_seq width");
    if ($bits(link.write_context_id)!=16) $fatal(1,"write_context_id width");
    if ($bits(link.write_generation)!=32) $fatal(1,"write_generation width");
    if ($bits(link.write_staging_ref)!=64) $fatal(1,"write_staging_ref width");
    if ($bits(link.write_offset)!=64) $fatal(1,"write_offset width");
    if ($bits(link.write_data)!=32) $fatal(1,"write_data width");
    if ($bits(link.write_keep)!=4) $fatal(1,"write_keep width");
    if ($bits(link.write_last)!=1) $fatal(1,"write_last width");
    if ($bits(link.control_req_valid)!=1) $fatal(1,"control_req_valid width");
    if ($bits(link.control_req_ready)!=1) $fatal(1,"control_req_ready width");
    if ($bits(link.control_req_owner_id)!=32) $fatal(1,"control_req_owner_id width");
    if ($bits(link.control_req_instance_id)!=16) $fatal(1,"control_req_instance_id width");
    if ($bits(link.control_req_epoch)!=32) $fatal(1,"control_req_epoch width");
    if ($bits(link.control_req_task_id)!=32) $fatal(1,"control_req_task_id width");
    if ($bits(link.control_req_request_seq)!=64) $fatal(1,"control_req_request_seq width");
    if ($bits(link.control_req_context_id)!=16) $fatal(1,"control_req_context_id width");
    if ($bits(link.control_req_generation)!=32) $fatal(1,"control_req_generation width");
    if ($bits(link.control_req_service_version)!=16) $fatal(1,"control_req_service_version width");
    if ($bits(link.control_req_request_id)!=64) $fatal(1,"control_req_request_id width");
    if ($bits(link.control_req_operation)!=8) $fatal(1,"control_req_operation width");
    if ($bits(link.control_req_staging_ref)!=64) $fatal(1,"control_req_staging_ref width");
    if ($bits(link.control_req_length)!=64) $fatal(1,"control_req_length width");
    if ($bits(link.control_req_policy_epoch)!=32) $fatal(1,"control_req_policy_epoch width");
    if ($bits(link.control_req_auth_valid)!=1) $fatal(1,"control_req_auth_valid width");
    if ($bits(link.control_req_auth_ok)!=1) $fatal(1,"control_req_auth_ok width");
    if ($bits(link.control_rsp_valid)!=1) $fatal(1,"control_rsp_valid width");
    if ($bits(link.control_rsp_ready)!=1) $fatal(1,"control_rsp_ready width");
    if ($bits(link.control_rsp_owner_id)!=32) $fatal(1,"control_rsp_owner_id width");
    if ($bits(link.control_rsp_instance_id)!=16) $fatal(1,"control_rsp_instance_id width");
    if ($bits(link.control_rsp_epoch)!=32) $fatal(1,"control_rsp_epoch width");
    if ($bits(link.control_rsp_task_id)!=32) $fatal(1,"control_rsp_task_id width");
    if ($bits(link.control_rsp_request_seq)!=64) $fatal(1,"control_rsp_request_seq width");
    if ($bits(link.control_rsp_context_id)!=16) $fatal(1,"control_rsp_context_id width");
    if ($bits(link.control_rsp_generation)!=32) $fatal(1,"control_rsp_generation width");
    if ($bits(link.control_rsp_request_id)!=64) $fatal(1,"control_rsp_request_id width");
    if ($bits(link.control_rsp_status)!=16) $fatal(1,"control_rsp_status width");
    if ($bits(link.control_rsp_state)!=8) $fatal(1,"control_rsp_state width");
    if ($bits(link.control_rsp_cleanup_done)!=1) $fatal(1,"control_rsp_cleanup_done width");
    if ($bits(aix_crypto_staging_w32_req_payload_t)!=474) $fatal(1,"payload width");
    if ($bits(aix_crypto_staging_w32_rsp_payload_t)!=505) $fatal(1,"payload width");
    if ($bits(aix_crypto_staging_w32_write_payload_t)!=389) $fatal(1,"payload width");
    if ($bits(aix_crypto_staging_w32_control_req_payload_t)!=474) $fatal(1,"payload width");
    if ($bits(aix_crypto_staging_w32_control_rsp_payload_t)!=313) $fatal(1,"payload width");
    if (OPERATION_RESERVE!=1) $fatal(1,"OPERATION_RESERVE encoding");
    if (OPERATION_PREPARE!=2) $fatal(1,"OPERATION_PREPARE encoding");
    if (OPERATION_COMMIT!=3) $fatal(1,"OPERATION_COMMIT encoding");
    if (OPERATION_DESTROY!=4) $fatal(1,"OPERATION_DESTROY encoding");
    if (OPERATION_QUERY!=5) $fatal(1,"OPERATION_QUERY encoding");
    if (STATE_NONE!=0) $fatal(1,"STATE_NONE encoding");
    if (STATE_RESERVED!=1) $fatal(1,"STATE_RESERVED encoding");
    if (STATE_WRITTEN!=2) $fatal(1,"STATE_WRITTEN encoding");
    if (STATE_PREPARED!=3) $fatal(1,"STATE_PREPARED encoding");
    if (STATE_COMMITTED!=4) $fatal(1,"STATE_COMMITTED encoding");
    if (STATE_DESTROYED!=5) $fatal(1,"STATE_DESTROYED encoding");
    if (STATE_LOCKED!=6) $fatal(1,"STATE_LOCKED encoding");
    if (STATE_UNKNOWN!=7) $fatal(1,"STATE_UNKNOWN encoding");
    wait(reset_n); #1; compare_paths();
    request='1; expected='1; #1; compare_paths();
    for (int sample=1;sample<=128;sample++) begin
      request=1342'(pattern(sample)); expected=823'(pattern(sample+271));
      #1; compare_paths();
    end
    for (int bitno=0;bitno<1342;bitno++) begin
      request='0; request[bitno]=1'b1; #1; compare_paths(); end
    for (int bitno=0;bitno<823;bitno++) begin
      expected='0; expected[bitno]=1'b1; #1; compare_paths(); end
    $display("PASS crypto_staging DATA_W=32 fields=77"); done=1;
  end
endmodule
module crypto_staging_peer_64(aix_crypto_staging_if.staging link,
  input logic [822:0] response, output logic [1377:0] observed);
  assign link.req_ready = response[822 +: 1];
  assign link.rsp_valid = response[821 +: 1];
  assign link.rsp_owner_id = response[789 +: 32];
  assign link.rsp_instance_id = response[773 +: 16];
  assign link.rsp_epoch = response[741 +: 32];
  assign link.rsp_task_id = response[709 +: 32];
  assign link.rsp_request_seq = response[645 +: 64];
  assign link.rsp_context_id = response[629 +: 16];
  assign link.rsp_generation = response[597 +: 32];
  assign link.rsp_request_id = response[533 +: 64];
  assign link.rsp_status = response[517 +: 16];
  assign link.rsp_staging_ref = response[453 +: 64];
  assign link.rsp_reserved_bytes = response[389 +: 64];
  assign link.rsp_written_bytes = response[325 +: 64];
  assign link.rsp_state = response[317 +: 8];
  assign link.rsp_cleanup_done = response[316 +: 1];
  assign link.write_ready = response[315 +: 1];
  assign link.control_req_ready = response[314 +: 1];
  assign link.control_rsp_valid = response[313 +: 1];
  assign link.control_rsp_owner_id = response[281 +: 32];
  assign link.control_rsp_instance_id = response[265 +: 16];
  assign link.control_rsp_epoch = response[233 +: 32];
  assign link.control_rsp_task_id = response[201 +: 32];
  assign link.control_rsp_request_seq = response[137 +: 64];
  assign link.control_rsp_context_id = response[121 +: 16];
  assign link.control_rsp_generation = response[89 +: 32];
  assign link.control_rsp_request_id = response[25 +: 64];
  assign link.control_rsp_status = response[9 +: 16];
  assign link.control_rsp_state = response[1 +: 8];
  assign link.control_rsp_cleanup_done = response[0 +: 1];
  assign observed = {link.req_valid, link.req_owner_id, link.req_instance_id, link.req_epoch, link.req_task_id, link.req_request_seq, link.req_context_id, link.req_generation, link.req_service_version, link.req_request_id, link.req_operation, link.req_staging_ref, link.req_length, link.req_policy_epoch, link.req_auth_valid, link.req_auth_ok, link.rsp_ready, link.write_valid, link.write_owner_id, link.write_instance_id, link.write_epoch, link.write_task_id, link.write_request_seq, link.write_context_id, link.write_generation, link.write_staging_ref, link.write_offset, link.write_data, link.write_keep, link.write_last, link.control_req_valid, link.control_req_owner_id, link.control_req_instance_id, link.control_req_epoch, link.control_req_task_id, link.control_req_request_seq, link.control_req_context_id, link.control_req_generation, link.control_req_service_version, link.control_req_request_id, link.control_req_operation, link.control_req_staging_ref, link.control_req_length, link.control_req_policy_epoch, link.control_req_auth_valid, link.control_req_auth_ok, link.control_rsp_ready};
  always @(posedge link.clk) if (link.reset_n !== 1'b0 && link.reset_n !== 1'b1) $fatal(1,"reset modport");
endmodule
module crypto_staging_case_64(input logic clk, reset_n, output logic done);
  import aix_crypto_staging_pkg::*;
  aix_crypto_staging_w64_req_t request;
  aix_crypto_staging_w64_rsp_t response;
  logic [822:0] expected;
  logic [1377:0] observed;
  aix_crypto_staging_if #(.DATA_W(64)) link (.clk(clk), .reset_n(reset_n));
  crypto_staging_peer_64 peer(link, expected, observed);
  aix_crypto_staging_flat_wrapper #(.DATA_W(64)) bridge(.link(link),
    .req_valid_i(request.req_valid),
    .req_ready_o(response.req_ready),
    .req_owner_id_i(request.req_owner_id),
    .req_instance_id_i(request.req_instance_id),
    .req_epoch_i(request.req_epoch),
    .req_task_id_i(request.req_task_id),
    .req_request_seq_i(request.req_request_seq),
    .req_context_id_i(request.req_context_id),
    .req_generation_i(request.req_generation),
    .req_service_version_i(request.req_service_version),
    .req_request_id_i(request.req_request_id),
    .req_operation_i(request.req_operation),
    .req_staging_ref_i(request.req_staging_ref),
    .req_length_i(request.req_length),
    .req_policy_epoch_i(request.req_policy_epoch),
    .req_auth_valid_i(request.req_auth_valid),
    .req_auth_ok_i(request.req_auth_ok),
    .rsp_valid_o(response.rsp_valid),
    .rsp_ready_i(request.rsp_ready),
    .rsp_owner_id_o(response.rsp_owner_id),
    .rsp_instance_id_o(response.rsp_instance_id),
    .rsp_epoch_o(response.rsp_epoch),
    .rsp_task_id_o(response.rsp_task_id),
    .rsp_request_seq_o(response.rsp_request_seq),
    .rsp_context_id_o(response.rsp_context_id),
    .rsp_generation_o(response.rsp_generation),
    .rsp_request_id_o(response.rsp_request_id),
    .rsp_status_o(response.rsp_status),
    .rsp_staging_ref_o(response.rsp_staging_ref),
    .rsp_reserved_bytes_o(response.rsp_reserved_bytes),
    .rsp_written_bytes_o(response.rsp_written_bytes),
    .rsp_state_o(response.rsp_state),
    .rsp_cleanup_done_o(response.rsp_cleanup_done),
    .write_valid_i(request.write_valid),
    .write_ready_o(response.write_ready),
    .write_owner_id_i(request.write_owner_id),
    .write_instance_id_i(request.write_instance_id),
    .write_epoch_i(request.write_epoch),
    .write_task_id_i(request.write_task_id),
    .write_request_seq_i(request.write_request_seq),
    .write_context_id_i(request.write_context_id),
    .write_generation_i(request.write_generation),
    .write_staging_ref_i(request.write_staging_ref),
    .write_offset_i(request.write_offset),
    .write_data_i(request.write_data),
    .write_keep_i(request.write_keep),
    .write_last_i(request.write_last),
    .control_req_valid_i(request.control_req_valid),
    .control_req_ready_o(response.control_req_ready),
    .control_req_owner_id_i(request.control_req_owner_id),
    .control_req_instance_id_i(request.control_req_instance_id),
    .control_req_epoch_i(request.control_req_epoch),
    .control_req_task_id_i(request.control_req_task_id),
    .control_req_request_seq_i(request.control_req_request_seq),
    .control_req_context_id_i(request.control_req_context_id),
    .control_req_generation_i(request.control_req_generation),
    .control_req_service_version_i(request.control_req_service_version),
    .control_req_request_id_i(request.control_req_request_id),
    .control_req_operation_i(request.control_req_operation),
    .control_req_staging_ref_i(request.control_req_staging_ref),
    .control_req_length_i(request.control_req_length),
    .control_req_policy_epoch_i(request.control_req_policy_epoch),
    .control_req_auth_valid_i(request.control_req_auth_valid),
    .control_req_auth_ok_i(request.control_req_auth_ok),
    .control_rsp_valid_o(response.control_rsp_valid),
    .control_rsp_ready_i(request.control_rsp_ready),
    .control_rsp_owner_id_o(response.control_rsp_owner_id),
    .control_rsp_instance_id_o(response.control_rsp_instance_id),
    .control_rsp_epoch_o(response.control_rsp_epoch),
    .control_rsp_task_id_o(response.control_rsp_task_id),
    .control_rsp_request_seq_o(response.control_rsp_request_seq),
    .control_rsp_context_id_o(response.control_rsp_context_id),
    .control_rsp_generation_o(response.control_rsp_generation),
    .control_rsp_request_id_o(response.control_rsp_request_id),
    .control_rsp_status_o(response.control_rsp_status),
    .control_rsp_state_o(response.control_rsp_state),
    .control_rsp_cleanup_done_o(response.control_rsp_cleanup_done)
  );
  function automatic logic [1377:0] pattern(input int seed);
    int unsigned state; state=32'h9e3779b9 ^ (32'h85ebca6b * seed);
    for (int i=0;i<1378;i++) begin
      state=1664525*state+1013904223; pattern[i]=state[31];
    end
  endfunction
  task automatic compare_paths;
    if (observed !== request) $fatal(1,"crypto_staging W64 forward wiring");
    if (response !== expected) $fatal(1,"crypto_staging W64 reverse wiring");
  endtask
  initial begin
    done=0; request='0; expected='0;
    if ($bits(request)!=1378 || $bits(response)!=823) $fatal(1,"aggregate width");
    if ($bits(link.req_valid)!=1) $fatal(1,"req_valid width");
    if ($bits(link.req_ready)!=1) $fatal(1,"req_ready width");
    if ($bits(link.req_owner_id)!=32) $fatal(1,"req_owner_id width");
    if ($bits(link.req_instance_id)!=16) $fatal(1,"req_instance_id width");
    if ($bits(link.req_epoch)!=32) $fatal(1,"req_epoch width");
    if ($bits(link.req_task_id)!=32) $fatal(1,"req_task_id width");
    if ($bits(link.req_request_seq)!=64) $fatal(1,"req_request_seq width");
    if ($bits(link.req_context_id)!=16) $fatal(1,"req_context_id width");
    if ($bits(link.req_generation)!=32) $fatal(1,"req_generation width");
    if ($bits(link.req_service_version)!=16) $fatal(1,"req_service_version width");
    if ($bits(link.req_request_id)!=64) $fatal(1,"req_request_id width");
    if ($bits(link.req_operation)!=8) $fatal(1,"req_operation width");
    if ($bits(link.req_staging_ref)!=64) $fatal(1,"req_staging_ref width");
    if ($bits(link.req_length)!=64) $fatal(1,"req_length width");
    if ($bits(link.req_policy_epoch)!=32) $fatal(1,"req_policy_epoch width");
    if ($bits(link.req_auth_valid)!=1) $fatal(1,"req_auth_valid width");
    if ($bits(link.req_auth_ok)!=1) $fatal(1,"req_auth_ok width");
    if ($bits(link.rsp_valid)!=1) $fatal(1,"rsp_valid width");
    if ($bits(link.rsp_ready)!=1) $fatal(1,"rsp_ready width");
    if ($bits(link.rsp_owner_id)!=32) $fatal(1,"rsp_owner_id width");
    if ($bits(link.rsp_instance_id)!=16) $fatal(1,"rsp_instance_id width");
    if ($bits(link.rsp_epoch)!=32) $fatal(1,"rsp_epoch width");
    if ($bits(link.rsp_task_id)!=32) $fatal(1,"rsp_task_id width");
    if ($bits(link.rsp_request_seq)!=64) $fatal(1,"rsp_request_seq width");
    if ($bits(link.rsp_context_id)!=16) $fatal(1,"rsp_context_id width");
    if ($bits(link.rsp_generation)!=32) $fatal(1,"rsp_generation width");
    if ($bits(link.rsp_request_id)!=64) $fatal(1,"rsp_request_id width");
    if ($bits(link.rsp_status)!=16) $fatal(1,"rsp_status width");
    if ($bits(link.rsp_staging_ref)!=64) $fatal(1,"rsp_staging_ref width");
    if ($bits(link.rsp_reserved_bytes)!=64) $fatal(1,"rsp_reserved_bytes width");
    if ($bits(link.rsp_written_bytes)!=64) $fatal(1,"rsp_written_bytes width");
    if ($bits(link.rsp_state)!=8) $fatal(1,"rsp_state width");
    if ($bits(link.rsp_cleanup_done)!=1) $fatal(1,"rsp_cleanup_done width");
    if ($bits(link.write_valid)!=1) $fatal(1,"write_valid width");
    if ($bits(link.write_ready)!=1) $fatal(1,"write_ready width");
    if ($bits(link.write_owner_id)!=32) $fatal(1,"write_owner_id width");
    if ($bits(link.write_instance_id)!=16) $fatal(1,"write_instance_id width");
    if ($bits(link.write_epoch)!=32) $fatal(1,"write_epoch width");
    if ($bits(link.write_task_id)!=32) $fatal(1,"write_task_id width");
    if ($bits(link.write_request_seq)!=64) $fatal(1,"write_request_seq width");
    if ($bits(link.write_context_id)!=16) $fatal(1,"write_context_id width");
    if ($bits(link.write_generation)!=32) $fatal(1,"write_generation width");
    if ($bits(link.write_staging_ref)!=64) $fatal(1,"write_staging_ref width");
    if ($bits(link.write_offset)!=64) $fatal(1,"write_offset width");
    if ($bits(link.write_data)!=64) $fatal(1,"write_data width");
    if ($bits(link.write_keep)!=8) $fatal(1,"write_keep width");
    if ($bits(link.write_last)!=1) $fatal(1,"write_last width");
    if ($bits(link.control_req_valid)!=1) $fatal(1,"control_req_valid width");
    if ($bits(link.control_req_ready)!=1) $fatal(1,"control_req_ready width");
    if ($bits(link.control_req_owner_id)!=32) $fatal(1,"control_req_owner_id width");
    if ($bits(link.control_req_instance_id)!=16) $fatal(1,"control_req_instance_id width");
    if ($bits(link.control_req_epoch)!=32) $fatal(1,"control_req_epoch width");
    if ($bits(link.control_req_task_id)!=32) $fatal(1,"control_req_task_id width");
    if ($bits(link.control_req_request_seq)!=64) $fatal(1,"control_req_request_seq width");
    if ($bits(link.control_req_context_id)!=16) $fatal(1,"control_req_context_id width");
    if ($bits(link.control_req_generation)!=32) $fatal(1,"control_req_generation width");
    if ($bits(link.control_req_service_version)!=16) $fatal(1,"control_req_service_version width");
    if ($bits(link.control_req_request_id)!=64) $fatal(1,"control_req_request_id width");
    if ($bits(link.control_req_operation)!=8) $fatal(1,"control_req_operation width");
    if ($bits(link.control_req_staging_ref)!=64) $fatal(1,"control_req_staging_ref width");
    if ($bits(link.control_req_length)!=64) $fatal(1,"control_req_length width");
    if ($bits(link.control_req_policy_epoch)!=32) $fatal(1,"control_req_policy_epoch width");
    if ($bits(link.control_req_auth_valid)!=1) $fatal(1,"control_req_auth_valid width");
    if ($bits(link.control_req_auth_ok)!=1) $fatal(1,"control_req_auth_ok width");
    if ($bits(link.control_rsp_valid)!=1) $fatal(1,"control_rsp_valid width");
    if ($bits(link.control_rsp_ready)!=1) $fatal(1,"control_rsp_ready width");
    if ($bits(link.control_rsp_owner_id)!=32) $fatal(1,"control_rsp_owner_id width");
    if ($bits(link.control_rsp_instance_id)!=16) $fatal(1,"control_rsp_instance_id width");
    if ($bits(link.control_rsp_epoch)!=32) $fatal(1,"control_rsp_epoch width");
    if ($bits(link.control_rsp_task_id)!=32) $fatal(1,"control_rsp_task_id width");
    if ($bits(link.control_rsp_request_seq)!=64) $fatal(1,"control_rsp_request_seq width");
    if ($bits(link.control_rsp_context_id)!=16) $fatal(1,"control_rsp_context_id width");
    if ($bits(link.control_rsp_generation)!=32) $fatal(1,"control_rsp_generation width");
    if ($bits(link.control_rsp_request_id)!=64) $fatal(1,"control_rsp_request_id width");
    if ($bits(link.control_rsp_status)!=16) $fatal(1,"control_rsp_status width");
    if ($bits(link.control_rsp_state)!=8) $fatal(1,"control_rsp_state width");
    if ($bits(link.control_rsp_cleanup_done)!=1) $fatal(1,"control_rsp_cleanup_done width");
    if ($bits(aix_crypto_staging_w64_req_payload_t)!=474) $fatal(1,"payload width");
    if ($bits(aix_crypto_staging_w64_rsp_payload_t)!=505) $fatal(1,"payload width");
    if ($bits(aix_crypto_staging_w64_write_payload_t)!=425) $fatal(1,"payload width");
    if ($bits(aix_crypto_staging_w64_control_req_payload_t)!=474) $fatal(1,"payload width");
    if ($bits(aix_crypto_staging_w64_control_rsp_payload_t)!=313) $fatal(1,"payload width");
    if (OPERATION_RESERVE!=1) $fatal(1,"OPERATION_RESERVE encoding");
    if (OPERATION_PREPARE!=2) $fatal(1,"OPERATION_PREPARE encoding");
    if (OPERATION_COMMIT!=3) $fatal(1,"OPERATION_COMMIT encoding");
    if (OPERATION_DESTROY!=4) $fatal(1,"OPERATION_DESTROY encoding");
    if (OPERATION_QUERY!=5) $fatal(1,"OPERATION_QUERY encoding");
    if (STATE_NONE!=0) $fatal(1,"STATE_NONE encoding");
    if (STATE_RESERVED!=1) $fatal(1,"STATE_RESERVED encoding");
    if (STATE_WRITTEN!=2) $fatal(1,"STATE_WRITTEN encoding");
    if (STATE_PREPARED!=3) $fatal(1,"STATE_PREPARED encoding");
    if (STATE_COMMITTED!=4) $fatal(1,"STATE_COMMITTED encoding");
    if (STATE_DESTROYED!=5) $fatal(1,"STATE_DESTROYED encoding");
    if (STATE_LOCKED!=6) $fatal(1,"STATE_LOCKED encoding");
    if (STATE_UNKNOWN!=7) $fatal(1,"STATE_UNKNOWN encoding");
    wait(reset_n); #1; compare_paths();
    request='1; expected='1; #1; compare_paths();
    for (int sample=1;sample<=128;sample++) begin
      request=1378'(pattern(sample)); expected=823'(pattern(sample+271));
      #1; compare_paths();
    end
    for (int bitno=0;bitno<1378;bitno++) begin
      request='0; request[bitno]=1'b1; #1; compare_paths(); end
    for (int bitno=0;bitno<823;bitno++) begin
      expected='0; expected[bitno]=1'b1; #1; compare_paths(); end
    $display("PASS crypto_staging DATA_W=64 fields=77"); done=1;
  end
endmodule
module crypto_staging_peer_128(aix_crypto_staging_if.staging link,
  input logic [822:0] response, output logic [1449:0] observed);
  assign link.req_ready = response[822 +: 1];
  assign link.rsp_valid = response[821 +: 1];
  assign link.rsp_owner_id = response[789 +: 32];
  assign link.rsp_instance_id = response[773 +: 16];
  assign link.rsp_epoch = response[741 +: 32];
  assign link.rsp_task_id = response[709 +: 32];
  assign link.rsp_request_seq = response[645 +: 64];
  assign link.rsp_context_id = response[629 +: 16];
  assign link.rsp_generation = response[597 +: 32];
  assign link.rsp_request_id = response[533 +: 64];
  assign link.rsp_status = response[517 +: 16];
  assign link.rsp_staging_ref = response[453 +: 64];
  assign link.rsp_reserved_bytes = response[389 +: 64];
  assign link.rsp_written_bytes = response[325 +: 64];
  assign link.rsp_state = response[317 +: 8];
  assign link.rsp_cleanup_done = response[316 +: 1];
  assign link.write_ready = response[315 +: 1];
  assign link.control_req_ready = response[314 +: 1];
  assign link.control_rsp_valid = response[313 +: 1];
  assign link.control_rsp_owner_id = response[281 +: 32];
  assign link.control_rsp_instance_id = response[265 +: 16];
  assign link.control_rsp_epoch = response[233 +: 32];
  assign link.control_rsp_task_id = response[201 +: 32];
  assign link.control_rsp_request_seq = response[137 +: 64];
  assign link.control_rsp_context_id = response[121 +: 16];
  assign link.control_rsp_generation = response[89 +: 32];
  assign link.control_rsp_request_id = response[25 +: 64];
  assign link.control_rsp_status = response[9 +: 16];
  assign link.control_rsp_state = response[1 +: 8];
  assign link.control_rsp_cleanup_done = response[0 +: 1];
  assign observed = {link.req_valid, link.req_owner_id, link.req_instance_id, link.req_epoch, link.req_task_id, link.req_request_seq, link.req_context_id, link.req_generation, link.req_service_version, link.req_request_id, link.req_operation, link.req_staging_ref, link.req_length, link.req_policy_epoch, link.req_auth_valid, link.req_auth_ok, link.rsp_ready, link.write_valid, link.write_owner_id, link.write_instance_id, link.write_epoch, link.write_task_id, link.write_request_seq, link.write_context_id, link.write_generation, link.write_staging_ref, link.write_offset, link.write_data, link.write_keep, link.write_last, link.control_req_valid, link.control_req_owner_id, link.control_req_instance_id, link.control_req_epoch, link.control_req_task_id, link.control_req_request_seq, link.control_req_context_id, link.control_req_generation, link.control_req_service_version, link.control_req_request_id, link.control_req_operation, link.control_req_staging_ref, link.control_req_length, link.control_req_policy_epoch, link.control_req_auth_valid, link.control_req_auth_ok, link.control_rsp_ready};
  always @(posedge link.clk) if (link.reset_n !== 1'b0 && link.reset_n !== 1'b1) $fatal(1,"reset modport");
endmodule
module crypto_staging_case_128(input logic clk, reset_n, output logic done);
  import aix_crypto_staging_pkg::*;
  aix_crypto_staging_w128_req_t request;
  aix_crypto_staging_w128_rsp_t response;
  logic [822:0] expected;
  logic [1449:0] observed;
  aix_crypto_staging_if #(.DATA_W(128)) link (.clk(clk), .reset_n(reset_n));
  crypto_staging_peer_128 peer(link, expected, observed);
  aix_crypto_staging_flat_wrapper #(.DATA_W(128)) bridge(.link(link),
    .req_valid_i(request.req_valid),
    .req_ready_o(response.req_ready),
    .req_owner_id_i(request.req_owner_id),
    .req_instance_id_i(request.req_instance_id),
    .req_epoch_i(request.req_epoch),
    .req_task_id_i(request.req_task_id),
    .req_request_seq_i(request.req_request_seq),
    .req_context_id_i(request.req_context_id),
    .req_generation_i(request.req_generation),
    .req_service_version_i(request.req_service_version),
    .req_request_id_i(request.req_request_id),
    .req_operation_i(request.req_operation),
    .req_staging_ref_i(request.req_staging_ref),
    .req_length_i(request.req_length),
    .req_policy_epoch_i(request.req_policy_epoch),
    .req_auth_valid_i(request.req_auth_valid),
    .req_auth_ok_i(request.req_auth_ok),
    .rsp_valid_o(response.rsp_valid),
    .rsp_ready_i(request.rsp_ready),
    .rsp_owner_id_o(response.rsp_owner_id),
    .rsp_instance_id_o(response.rsp_instance_id),
    .rsp_epoch_o(response.rsp_epoch),
    .rsp_task_id_o(response.rsp_task_id),
    .rsp_request_seq_o(response.rsp_request_seq),
    .rsp_context_id_o(response.rsp_context_id),
    .rsp_generation_o(response.rsp_generation),
    .rsp_request_id_o(response.rsp_request_id),
    .rsp_status_o(response.rsp_status),
    .rsp_staging_ref_o(response.rsp_staging_ref),
    .rsp_reserved_bytes_o(response.rsp_reserved_bytes),
    .rsp_written_bytes_o(response.rsp_written_bytes),
    .rsp_state_o(response.rsp_state),
    .rsp_cleanup_done_o(response.rsp_cleanup_done),
    .write_valid_i(request.write_valid),
    .write_ready_o(response.write_ready),
    .write_owner_id_i(request.write_owner_id),
    .write_instance_id_i(request.write_instance_id),
    .write_epoch_i(request.write_epoch),
    .write_task_id_i(request.write_task_id),
    .write_request_seq_i(request.write_request_seq),
    .write_context_id_i(request.write_context_id),
    .write_generation_i(request.write_generation),
    .write_staging_ref_i(request.write_staging_ref),
    .write_offset_i(request.write_offset),
    .write_data_i(request.write_data),
    .write_keep_i(request.write_keep),
    .write_last_i(request.write_last),
    .control_req_valid_i(request.control_req_valid),
    .control_req_ready_o(response.control_req_ready),
    .control_req_owner_id_i(request.control_req_owner_id),
    .control_req_instance_id_i(request.control_req_instance_id),
    .control_req_epoch_i(request.control_req_epoch),
    .control_req_task_id_i(request.control_req_task_id),
    .control_req_request_seq_i(request.control_req_request_seq),
    .control_req_context_id_i(request.control_req_context_id),
    .control_req_generation_i(request.control_req_generation),
    .control_req_service_version_i(request.control_req_service_version),
    .control_req_request_id_i(request.control_req_request_id),
    .control_req_operation_i(request.control_req_operation),
    .control_req_staging_ref_i(request.control_req_staging_ref),
    .control_req_length_i(request.control_req_length),
    .control_req_policy_epoch_i(request.control_req_policy_epoch),
    .control_req_auth_valid_i(request.control_req_auth_valid),
    .control_req_auth_ok_i(request.control_req_auth_ok),
    .control_rsp_valid_o(response.control_rsp_valid),
    .control_rsp_ready_i(request.control_rsp_ready),
    .control_rsp_owner_id_o(response.control_rsp_owner_id),
    .control_rsp_instance_id_o(response.control_rsp_instance_id),
    .control_rsp_epoch_o(response.control_rsp_epoch),
    .control_rsp_task_id_o(response.control_rsp_task_id),
    .control_rsp_request_seq_o(response.control_rsp_request_seq),
    .control_rsp_context_id_o(response.control_rsp_context_id),
    .control_rsp_generation_o(response.control_rsp_generation),
    .control_rsp_request_id_o(response.control_rsp_request_id),
    .control_rsp_status_o(response.control_rsp_status),
    .control_rsp_state_o(response.control_rsp_state),
    .control_rsp_cleanup_done_o(response.control_rsp_cleanup_done)
  );
  function automatic logic [1449:0] pattern(input int seed);
    int unsigned state; state=32'h9e3779b9 ^ (32'h85ebca6b * seed);
    for (int i=0;i<1450;i++) begin
      state=1664525*state+1013904223; pattern[i]=state[31];
    end
  endfunction
  task automatic compare_paths;
    if (observed !== request) $fatal(1,"crypto_staging W128 forward wiring");
    if (response !== expected) $fatal(1,"crypto_staging W128 reverse wiring");
  endtask
  initial begin
    done=0; request='0; expected='0;
    if ($bits(request)!=1450 || $bits(response)!=823) $fatal(1,"aggregate width");
    if ($bits(link.req_valid)!=1) $fatal(1,"req_valid width");
    if ($bits(link.req_ready)!=1) $fatal(1,"req_ready width");
    if ($bits(link.req_owner_id)!=32) $fatal(1,"req_owner_id width");
    if ($bits(link.req_instance_id)!=16) $fatal(1,"req_instance_id width");
    if ($bits(link.req_epoch)!=32) $fatal(1,"req_epoch width");
    if ($bits(link.req_task_id)!=32) $fatal(1,"req_task_id width");
    if ($bits(link.req_request_seq)!=64) $fatal(1,"req_request_seq width");
    if ($bits(link.req_context_id)!=16) $fatal(1,"req_context_id width");
    if ($bits(link.req_generation)!=32) $fatal(1,"req_generation width");
    if ($bits(link.req_service_version)!=16) $fatal(1,"req_service_version width");
    if ($bits(link.req_request_id)!=64) $fatal(1,"req_request_id width");
    if ($bits(link.req_operation)!=8) $fatal(1,"req_operation width");
    if ($bits(link.req_staging_ref)!=64) $fatal(1,"req_staging_ref width");
    if ($bits(link.req_length)!=64) $fatal(1,"req_length width");
    if ($bits(link.req_policy_epoch)!=32) $fatal(1,"req_policy_epoch width");
    if ($bits(link.req_auth_valid)!=1) $fatal(1,"req_auth_valid width");
    if ($bits(link.req_auth_ok)!=1) $fatal(1,"req_auth_ok width");
    if ($bits(link.rsp_valid)!=1) $fatal(1,"rsp_valid width");
    if ($bits(link.rsp_ready)!=1) $fatal(1,"rsp_ready width");
    if ($bits(link.rsp_owner_id)!=32) $fatal(1,"rsp_owner_id width");
    if ($bits(link.rsp_instance_id)!=16) $fatal(1,"rsp_instance_id width");
    if ($bits(link.rsp_epoch)!=32) $fatal(1,"rsp_epoch width");
    if ($bits(link.rsp_task_id)!=32) $fatal(1,"rsp_task_id width");
    if ($bits(link.rsp_request_seq)!=64) $fatal(1,"rsp_request_seq width");
    if ($bits(link.rsp_context_id)!=16) $fatal(1,"rsp_context_id width");
    if ($bits(link.rsp_generation)!=32) $fatal(1,"rsp_generation width");
    if ($bits(link.rsp_request_id)!=64) $fatal(1,"rsp_request_id width");
    if ($bits(link.rsp_status)!=16) $fatal(1,"rsp_status width");
    if ($bits(link.rsp_staging_ref)!=64) $fatal(1,"rsp_staging_ref width");
    if ($bits(link.rsp_reserved_bytes)!=64) $fatal(1,"rsp_reserved_bytes width");
    if ($bits(link.rsp_written_bytes)!=64) $fatal(1,"rsp_written_bytes width");
    if ($bits(link.rsp_state)!=8) $fatal(1,"rsp_state width");
    if ($bits(link.rsp_cleanup_done)!=1) $fatal(1,"rsp_cleanup_done width");
    if ($bits(link.write_valid)!=1) $fatal(1,"write_valid width");
    if ($bits(link.write_ready)!=1) $fatal(1,"write_ready width");
    if ($bits(link.write_owner_id)!=32) $fatal(1,"write_owner_id width");
    if ($bits(link.write_instance_id)!=16) $fatal(1,"write_instance_id width");
    if ($bits(link.write_epoch)!=32) $fatal(1,"write_epoch width");
    if ($bits(link.write_task_id)!=32) $fatal(1,"write_task_id width");
    if ($bits(link.write_request_seq)!=64) $fatal(1,"write_request_seq width");
    if ($bits(link.write_context_id)!=16) $fatal(1,"write_context_id width");
    if ($bits(link.write_generation)!=32) $fatal(1,"write_generation width");
    if ($bits(link.write_staging_ref)!=64) $fatal(1,"write_staging_ref width");
    if ($bits(link.write_offset)!=64) $fatal(1,"write_offset width");
    if ($bits(link.write_data)!=128) $fatal(1,"write_data width");
    if ($bits(link.write_keep)!=16) $fatal(1,"write_keep width");
    if ($bits(link.write_last)!=1) $fatal(1,"write_last width");
    if ($bits(link.control_req_valid)!=1) $fatal(1,"control_req_valid width");
    if ($bits(link.control_req_ready)!=1) $fatal(1,"control_req_ready width");
    if ($bits(link.control_req_owner_id)!=32) $fatal(1,"control_req_owner_id width");
    if ($bits(link.control_req_instance_id)!=16) $fatal(1,"control_req_instance_id width");
    if ($bits(link.control_req_epoch)!=32) $fatal(1,"control_req_epoch width");
    if ($bits(link.control_req_task_id)!=32) $fatal(1,"control_req_task_id width");
    if ($bits(link.control_req_request_seq)!=64) $fatal(1,"control_req_request_seq width");
    if ($bits(link.control_req_context_id)!=16) $fatal(1,"control_req_context_id width");
    if ($bits(link.control_req_generation)!=32) $fatal(1,"control_req_generation width");
    if ($bits(link.control_req_service_version)!=16) $fatal(1,"control_req_service_version width");
    if ($bits(link.control_req_request_id)!=64) $fatal(1,"control_req_request_id width");
    if ($bits(link.control_req_operation)!=8) $fatal(1,"control_req_operation width");
    if ($bits(link.control_req_staging_ref)!=64) $fatal(1,"control_req_staging_ref width");
    if ($bits(link.control_req_length)!=64) $fatal(1,"control_req_length width");
    if ($bits(link.control_req_policy_epoch)!=32) $fatal(1,"control_req_policy_epoch width");
    if ($bits(link.control_req_auth_valid)!=1) $fatal(1,"control_req_auth_valid width");
    if ($bits(link.control_req_auth_ok)!=1) $fatal(1,"control_req_auth_ok width");
    if ($bits(link.control_rsp_valid)!=1) $fatal(1,"control_rsp_valid width");
    if ($bits(link.control_rsp_ready)!=1) $fatal(1,"control_rsp_ready width");
    if ($bits(link.control_rsp_owner_id)!=32) $fatal(1,"control_rsp_owner_id width");
    if ($bits(link.control_rsp_instance_id)!=16) $fatal(1,"control_rsp_instance_id width");
    if ($bits(link.control_rsp_epoch)!=32) $fatal(1,"control_rsp_epoch width");
    if ($bits(link.control_rsp_task_id)!=32) $fatal(1,"control_rsp_task_id width");
    if ($bits(link.control_rsp_request_seq)!=64) $fatal(1,"control_rsp_request_seq width");
    if ($bits(link.control_rsp_context_id)!=16) $fatal(1,"control_rsp_context_id width");
    if ($bits(link.control_rsp_generation)!=32) $fatal(1,"control_rsp_generation width");
    if ($bits(link.control_rsp_request_id)!=64) $fatal(1,"control_rsp_request_id width");
    if ($bits(link.control_rsp_status)!=16) $fatal(1,"control_rsp_status width");
    if ($bits(link.control_rsp_state)!=8) $fatal(1,"control_rsp_state width");
    if ($bits(link.control_rsp_cleanup_done)!=1) $fatal(1,"control_rsp_cleanup_done width");
    if ($bits(aix_crypto_staging_w128_req_payload_t)!=474) $fatal(1,"payload width");
    if ($bits(aix_crypto_staging_w128_rsp_payload_t)!=505) $fatal(1,"payload width");
    if ($bits(aix_crypto_staging_w128_write_payload_t)!=497) $fatal(1,"payload width");
    if ($bits(aix_crypto_staging_w128_control_req_payload_t)!=474) $fatal(1,"payload width");
    if ($bits(aix_crypto_staging_w128_control_rsp_payload_t)!=313) $fatal(1,"payload width");
    if ($bits(aix_crypto_staging_req_t)!=1450 || $bits(aix_crypto_staging_rsp_t)!=823) $fatal(1,"default aliases");
    if (OPERATION_RESERVE!=1) $fatal(1,"OPERATION_RESERVE encoding");
    if (OPERATION_PREPARE!=2) $fatal(1,"OPERATION_PREPARE encoding");
    if (OPERATION_COMMIT!=3) $fatal(1,"OPERATION_COMMIT encoding");
    if (OPERATION_DESTROY!=4) $fatal(1,"OPERATION_DESTROY encoding");
    if (OPERATION_QUERY!=5) $fatal(1,"OPERATION_QUERY encoding");
    if (STATE_NONE!=0) $fatal(1,"STATE_NONE encoding");
    if (STATE_RESERVED!=1) $fatal(1,"STATE_RESERVED encoding");
    if (STATE_WRITTEN!=2) $fatal(1,"STATE_WRITTEN encoding");
    if (STATE_PREPARED!=3) $fatal(1,"STATE_PREPARED encoding");
    if (STATE_COMMITTED!=4) $fatal(1,"STATE_COMMITTED encoding");
    if (STATE_DESTROYED!=5) $fatal(1,"STATE_DESTROYED encoding");
    if (STATE_LOCKED!=6) $fatal(1,"STATE_LOCKED encoding");
    if (STATE_UNKNOWN!=7) $fatal(1,"STATE_UNKNOWN encoding");
    wait(reset_n); #1; compare_paths();
    request='1; expected='1; #1; compare_paths();
    for (int sample=1;sample<=128;sample++) begin
      request=1450'(pattern(sample)); expected=823'(pattern(sample+271));
      #1; compare_paths();
    end
    for (int bitno=0;bitno<1450;bitno++) begin
      request='0; request[bitno]=1'b1; #1; compare_paths(); end
    for (int bitno=0;bitno<823;bitno++) begin
      expected='0; expected[bitno]=1'b1; #1; compare_paths(); end
    $display("PASS crypto_staging DATA_W=128 fields=77"); done=1;
  end
endmodule
module crypto_staging_peer_256(aix_crypto_staging_if.staging link,
  input logic [822:0] response, output logic [1593:0] observed);
  assign link.req_ready = response[822 +: 1];
  assign link.rsp_valid = response[821 +: 1];
  assign link.rsp_owner_id = response[789 +: 32];
  assign link.rsp_instance_id = response[773 +: 16];
  assign link.rsp_epoch = response[741 +: 32];
  assign link.rsp_task_id = response[709 +: 32];
  assign link.rsp_request_seq = response[645 +: 64];
  assign link.rsp_context_id = response[629 +: 16];
  assign link.rsp_generation = response[597 +: 32];
  assign link.rsp_request_id = response[533 +: 64];
  assign link.rsp_status = response[517 +: 16];
  assign link.rsp_staging_ref = response[453 +: 64];
  assign link.rsp_reserved_bytes = response[389 +: 64];
  assign link.rsp_written_bytes = response[325 +: 64];
  assign link.rsp_state = response[317 +: 8];
  assign link.rsp_cleanup_done = response[316 +: 1];
  assign link.write_ready = response[315 +: 1];
  assign link.control_req_ready = response[314 +: 1];
  assign link.control_rsp_valid = response[313 +: 1];
  assign link.control_rsp_owner_id = response[281 +: 32];
  assign link.control_rsp_instance_id = response[265 +: 16];
  assign link.control_rsp_epoch = response[233 +: 32];
  assign link.control_rsp_task_id = response[201 +: 32];
  assign link.control_rsp_request_seq = response[137 +: 64];
  assign link.control_rsp_context_id = response[121 +: 16];
  assign link.control_rsp_generation = response[89 +: 32];
  assign link.control_rsp_request_id = response[25 +: 64];
  assign link.control_rsp_status = response[9 +: 16];
  assign link.control_rsp_state = response[1 +: 8];
  assign link.control_rsp_cleanup_done = response[0 +: 1];
  assign observed = {link.req_valid, link.req_owner_id, link.req_instance_id, link.req_epoch, link.req_task_id, link.req_request_seq, link.req_context_id, link.req_generation, link.req_service_version, link.req_request_id, link.req_operation, link.req_staging_ref, link.req_length, link.req_policy_epoch, link.req_auth_valid, link.req_auth_ok, link.rsp_ready, link.write_valid, link.write_owner_id, link.write_instance_id, link.write_epoch, link.write_task_id, link.write_request_seq, link.write_context_id, link.write_generation, link.write_staging_ref, link.write_offset, link.write_data, link.write_keep, link.write_last, link.control_req_valid, link.control_req_owner_id, link.control_req_instance_id, link.control_req_epoch, link.control_req_task_id, link.control_req_request_seq, link.control_req_context_id, link.control_req_generation, link.control_req_service_version, link.control_req_request_id, link.control_req_operation, link.control_req_staging_ref, link.control_req_length, link.control_req_policy_epoch, link.control_req_auth_valid, link.control_req_auth_ok, link.control_rsp_ready};
  always @(posedge link.clk) if (link.reset_n !== 1'b0 && link.reset_n !== 1'b1) $fatal(1,"reset modport");
endmodule
module crypto_staging_case_256(input logic clk, reset_n, output logic done);
  import aix_crypto_staging_pkg::*;
  aix_crypto_staging_w256_req_t request;
  aix_crypto_staging_w256_rsp_t response;
  logic [822:0] expected;
  logic [1593:0] observed;
  aix_crypto_staging_if #(.DATA_W(256)) link (.clk(clk), .reset_n(reset_n));
  crypto_staging_peer_256 peer(link, expected, observed);
  aix_crypto_staging_flat_wrapper #(.DATA_W(256)) bridge(.link(link),
    .req_valid_i(request.req_valid),
    .req_ready_o(response.req_ready),
    .req_owner_id_i(request.req_owner_id),
    .req_instance_id_i(request.req_instance_id),
    .req_epoch_i(request.req_epoch),
    .req_task_id_i(request.req_task_id),
    .req_request_seq_i(request.req_request_seq),
    .req_context_id_i(request.req_context_id),
    .req_generation_i(request.req_generation),
    .req_service_version_i(request.req_service_version),
    .req_request_id_i(request.req_request_id),
    .req_operation_i(request.req_operation),
    .req_staging_ref_i(request.req_staging_ref),
    .req_length_i(request.req_length),
    .req_policy_epoch_i(request.req_policy_epoch),
    .req_auth_valid_i(request.req_auth_valid),
    .req_auth_ok_i(request.req_auth_ok),
    .rsp_valid_o(response.rsp_valid),
    .rsp_ready_i(request.rsp_ready),
    .rsp_owner_id_o(response.rsp_owner_id),
    .rsp_instance_id_o(response.rsp_instance_id),
    .rsp_epoch_o(response.rsp_epoch),
    .rsp_task_id_o(response.rsp_task_id),
    .rsp_request_seq_o(response.rsp_request_seq),
    .rsp_context_id_o(response.rsp_context_id),
    .rsp_generation_o(response.rsp_generation),
    .rsp_request_id_o(response.rsp_request_id),
    .rsp_status_o(response.rsp_status),
    .rsp_staging_ref_o(response.rsp_staging_ref),
    .rsp_reserved_bytes_o(response.rsp_reserved_bytes),
    .rsp_written_bytes_o(response.rsp_written_bytes),
    .rsp_state_o(response.rsp_state),
    .rsp_cleanup_done_o(response.rsp_cleanup_done),
    .write_valid_i(request.write_valid),
    .write_ready_o(response.write_ready),
    .write_owner_id_i(request.write_owner_id),
    .write_instance_id_i(request.write_instance_id),
    .write_epoch_i(request.write_epoch),
    .write_task_id_i(request.write_task_id),
    .write_request_seq_i(request.write_request_seq),
    .write_context_id_i(request.write_context_id),
    .write_generation_i(request.write_generation),
    .write_staging_ref_i(request.write_staging_ref),
    .write_offset_i(request.write_offset),
    .write_data_i(request.write_data),
    .write_keep_i(request.write_keep),
    .write_last_i(request.write_last),
    .control_req_valid_i(request.control_req_valid),
    .control_req_ready_o(response.control_req_ready),
    .control_req_owner_id_i(request.control_req_owner_id),
    .control_req_instance_id_i(request.control_req_instance_id),
    .control_req_epoch_i(request.control_req_epoch),
    .control_req_task_id_i(request.control_req_task_id),
    .control_req_request_seq_i(request.control_req_request_seq),
    .control_req_context_id_i(request.control_req_context_id),
    .control_req_generation_i(request.control_req_generation),
    .control_req_service_version_i(request.control_req_service_version),
    .control_req_request_id_i(request.control_req_request_id),
    .control_req_operation_i(request.control_req_operation),
    .control_req_staging_ref_i(request.control_req_staging_ref),
    .control_req_length_i(request.control_req_length),
    .control_req_policy_epoch_i(request.control_req_policy_epoch),
    .control_req_auth_valid_i(request.control_req_auth_valid),
    .control_req_auth_ok_i(request.control_req_auth_ok),
    .control_rsp_valid_o(response.control_rsp_valid),
    .control_rsp_ready_i(request.control_rsp_ready),
    .control_rsp_owner_id_o(response.control_rsp_owner_id),
    .control_rsp_instance_id_o(response.control_rsp_instance_id),
    .control_rsp_epoch_o(response.control_rsp_epoch),
    .control_rsp_task_id_o(response.control_rsp_task_id),
    .control_rsp_request_seq_o(response.control_rsp_request_seq),
    .control_rsp_context_id_o(response.control_rsp_context_id),
    .control_rsp_generation_o(response.control_rsp_generation),
    .control_rsp_request_id_o(response.control_rsp_request_id),
    .control_rsp_status_o(response.control_rsp_status),
    .control_rsp_state_o(response.control_rsp_state),
    .control_rsp_cleanup_done_o(response.control_rsp_cleanup_done)
  );
  function automatic logic [1593:0] pattern(input int seed);
    int unsigned state; state=32'h9e3779b9 ^ (32'h85ebca6b * seed);
    for (int i=0;i<1594;i++) begin
      state=1664525*state+1013904223; pattern[i]=state[31];
    end
  endfunction
  task automatic compare_paths;
    if (observed !== request) $fatal(1,"crypto_staging W256 forward wiring");
    if (response !== expected) $fatal(1,"crypto_staging W256 reverse wiring");
  endtask
  initial begin
    done=0; request='0; expected='0;
    if ($bits(request)!=1594 || $bits(response)!=823) $fatal(1,"aggregate width");
    if ($bits(link.req_valid)!=1) $fatal(1,"req_valid width");
    if ($bits(link.req_ready)!=1) $fatal(1,"req_ready width");
    if ($bits(link.req_owner_id)!=32) $fatal(1,"req_owner_id width");
    if ($bits(link.req_instance_id)!=16) $fatal(1,"req_instance_id width");
    if ($bits(link.req_epoch)!=32) $fatal(1,"req_epoch width");
    if ($bits(link.req_task_id)!=32) $fatal(1,"req_task_id width");
    if ($bits(link.req_request_seq)!=64) $fatal(1,"req_request_seq width");
    if ($bits(link.req_context_id)!=16) $fatal(1,"req_context_id width");
    if ($bits(link.req_generation)!=32) $fatal(1,"req_generation width");
    if ($bits(link.req_service_version)!=16) $fatal(1,"req_service_version width");
    if ($bits(link.req_request_id)!=64) $fatal(1,"req_request_id width");
    if ($bits(link.req_operation)!=8) $fatal(1,"req_operation width");
    if ($bits(link.req_staging_ref)!=64) $fatal(1,"req_staging_ref width");
    if ($bits(link.req_length)!=64) $fatal(1,"req_length width");
    if ($bits(link.req_policy_epoch)!=32) $fatal(1,"req_policy_epoch width");
    if ($bits(link.req_auth_valid)!=1) $fatal(1,"req_auth_valid width");
    if ($bits(link.req_auth_ok)!=1) $fatal(1,"req_auth_ok width");
    if ($bits(link.rsp_valid)!=1) $fatal(1,"rsp_valid width");
    if ($bits(link.rsp_ready)!=1) $fatal(1,"rsp_ready width");
    if ($bits(link.rsp_owner_id)!=32) $fatal(1,"rsp_owner_id width");
    if ($bits(link.rsp_instance_id)!=16) $fatal(1,"rsp_instance_id width");
    if ($bits(link.rsp_epoch)!=32) $fatal(1,"rsp_epoch width");
    if ($bits(link.rsp_task_id)!=32) $fatal(1,"rsp_task_id width");
    if ($bits(link.rsp_request_seq)!=64) $fatal(1,"rsp_request_seq width");
    if ($bits(link.rsp_context_id)!=16) $fatal(1,"rsp_context_id width");
    if ($bits(link.rsp_generation)!=32) $fatal(1,"rsp_generation width");
    if ($bits(link.rsp_request_id)!=64) $fatal(1,"rsp_request_id width");
    if ($bits(link.rsp_status)!=16) $fatal(1,"rsp_status width");
    if ($bits(link.rsp_staging_ref)!=64) $fatal(1,"rsp_staging_ref width");
    if ($bits(link.rsp_reserved_bytes)!=64) $fatal(1,"rsp_reserved_bytes width");
    if ($bits(link.rsp_written_bytes)!=64) $fatal(1,"rsp_written_bytes width");
    if ($bits(link.rsp_state)!=8) $fatal(1,"rsp_state width");
    if ($bits(link.rsp_cleanup_done)!=1) $fatal(1,"rsp_cleanup_done width");
    if ($bits(link.write_valid)!=1) $fatal(1,"write_valid width");
    if ($bits(link.write_ready)!=1) $fatal(1,"write_ready width");
    if ($bits(link.write_owner_id)!=32) $fatal(1,"write_owner_id width");
    if ($bits(link.write_instance_id)!=16) $fatal(1,"write_instance_id width");
    if ($bits(link.write_epoch)!=32) $fatal(1,"write_epoch width");
    if ($bits(link.write_task_id)!=32) $fatal(1,"write_task_id width");
    if ($bits(link.write_request_seq)!=64) $fatal(1,"write_request_seq width");
    if ($bits(link.write_context_id)!=16) $fatal(1,"write_context_id width");
    if ($bits(link.write_generation)!=32) $fatal(1,"write_generation width");
    if ($bits(link.write_staging_ref)!=64) $fatal(1,"write_staging_ref width");
    if ($bits(link.write_offset)!=64) $fatal(1,"write_offset width");
    if ($bits(link.write_data)!=256) $fatal(1,"write_data width");
    if ($bits(link.write_keep)!=32) $fatal(1,"write_keep width");
    if ($bits(link.write_last)!=1) $fatal(1,"write_last width");
    if ($bits(link.control_req_valid)!=1) $fatal(1,"control_req_valid width");
    if ($bits(link.control_req_ready)!=1) $fatal(1,"control_req_ready width");
    if ($bits(link.control_req_owner_id)!=32) $fatal(1,"control_req_owner_id width");
    if ($bits(link.control_req_instance_id)!=16) $fatal(1,"control_req_instance_id width");
    if ($bits(link.control_req_epoch)!=32) $fatal(1,"control_req_epoch width");
    if ($bits(link.control_req_task_id)!=32) $fatal(1,"control_req_task_id width");
    if ($bits(link.control_req_request_seq)!=64) $fatal(1,"control_req_request_seq width");
    if ($bits(link.control_req_context_id)!=16) $fatal(1,"control_req_context_id width");
    if ($bits(link.control_req_generation)!=32) $fatal(1,"control_req_generation width");
    if ($bits(link.control_req_service_version)!=16) $fatal(1,"control_req_service_version width");
    if ($bits(link.control_req_request_id)!=64) $fatal(1,"control_req_request_id width");
    if ($bits(link.control_req_operation)!=8) $fatal(1,"control_req_operation width");
    if ($bits(link.control_req_staging_ref)!=64) $fatal(1,"control_req_staging_ref width");
    if ($bits(link.control_req_length)!=64) $fatal(1,"control_req_length width");
    if ($bits(link.control_req_policy_epoch)!=32) $fatal(1,"control_req_policy_epoch width");
    if ($bits(link.control_req_auth_valid)!=1) $fatal(1,"control_req_auth_valid width");
    if ($bits(link.control_req_auth_ok)!=1) $fatal(1,"control_req_auth_ok width");
    if ($bits(link.control_rsp_valid)!=1) $fatal(1,"control_rsp_valid width");
    if ($bits(link.control_rsp_ready)!=1) $fatal(1,"control_rsp_ready width");
    if ($bits(link.control_rsp_owner_id)!=32) $fatal(1,"control_rsp_owner_id width");
    if ($bits(link.control_rsp_instance_id)!=16) $fatal(1,"control_rsp_instance_id width");
    if ($bits(link.control_rsp_epoch)!=32) $fatal(1,"control_rsp_epoch width");
    if ($bits(link.control_rsp_task_id)!=32) $fatal(1,"control_rsp_task_id width");
    if ($bits(link.control_rsp_request_seq)!=64) $fatal(1,"control_rsp_request_seq width");
    if ($bits(link.control_rsp_context_id)!=16) $fatal(1,"control_rsp_context_id width");
    if ($bits(link.control_rsp_generation)!=32) $fatal(1,"control_rsp_generation width");
    if ($bits(link.control_rsp_request_id)!=64) $fatal(1,"control_rsp_request_id width");
    if ($bits(link.control_rsp_status)!=16) $fatal(1,"control_rsp_status width");
    if ($bits(link.control_rsp_state)!=8) $fatal(1,"control_rsp_state width");
    if ($bits(link.control_rsp_cleanup_done)!=1) $fatal(1,"control_rsp_cleanup_done width");
    if ($bits(aix_crypto_staging_w256_req_payload_t)!=474) $fatal(1,"payload width");
    if ($bits(aix_crypto_staging_w256_rsp_payload_t)!=505) $fatal(1,"payload width");
    if ($bits(aix_crypto_staging_w256_write_payload_t)!=641) $fatal(1,"payload width");
    if ($bits(aix_crypto_staging_w256_control_req_payload_t)!=474) $fatal(1,"payload width");
    if ($bits(aix_crypto_staging_w256_control_rsp_payload_t)!=313) $fatal(1,"payload width");
    if (OPERATION_RESERVE!=1) $fatal(1,"OPERATION_RESERVE encoding");
    if (OPERATION_PREPARE!=2) $fatal(1,"OPERATION_PREPARE encoding");
    if (OPERATION_COMMIT!=3) $fatal(1,"OPERATION_COMMIT encoding");
    if (OPERATION_DESTROY!=4) $fatal(1,"OPERATION_DESTROY encoding");
    if (OPERATION_QUERY!=5) $fatal(1,"OPERATION_QUERY encoding");
    if (STATE_NONE!=0) $fatal(1,"STATE_NONE encoding");
    if (STATE_RESERVED!=1) $fatal(1,"STATE_RESERVED encoding");
    if (STATE_WRITTEN!=2) $fatal(1,"STATE_WRITTEN encoding");
    if (STATE_PREPARED!=3) $fatal(1,"STATE_PREPARED encoding");
    if (STATE_COMMITTED!=4) $fatal(1,"STATE_COMMITTED encoding");
    if (STATE_DESTROYED!=5) $fatal(1,"STATE_DESTROYED encoding");
    if (STATE_LOCKED!=6) $fatal(1,"STATE_LOCKED encoding");
    if (STATE_UNKNOWN!=7) $fatal(1,"STATE_UNKNOWN encoding");
    wait(reset_n); #1; compare_paths();
    request='1; expected='1; #1; compare_paths();
    for (int sample=1;sample<=128;sample++) begin
      request=1594'(pattern(sample)); expected=823'(pattern(sample+271));
      #1; compare_paths();
    end
    for (int bitno=0;bitno<1594;bitno++) begin
      request='0; request[bitno]=1'b1; #1; compare_paths(); end
    for (int bitno=0;bitno<823;bitno++) begin
      expected='0; expected[bitno]=1'b1; #1; compare_paths(); end
    $display("PASS crypto_staging DATA_W=256 fields=77"); done=1;
  end
endmodule
module crypto_staging_peer_512(aix_crypto_staging_if.staging link,
  input logic [822:0] response, output logic [1881:0] observed);
  assign link.req_ready = response[822 +: 1];
  assign link.rsp_valid = response[821 +: 1];
  assign link.rsp_owner_id = response[789 +: 32];
  assign link.rsp_instance_id = response[773 +: 16];
  assign link.rsp_epoch = response[741 +: 32];
  assign link.rsp_task_id = response[709 +: 32];
  assign link.rsp_request_seq = response[645 +: 64];
  assign link.rsp_context_id = response[629 +: 16];
  assign link.rsp_generation = response[597 +: 32];
  assign link.rsp_request_id = response[533 +: 64];
  assign link.rsp_status = response[517 +: 16];
  assign link.rsp_staging_ref = response[453 +: 64];
  assign link.rsp_reserved_bytes = response[389 +: 64];
  assign link.rsp_written_bytes = response[325 +: 64];
  assign link.rsp_state = response[317 +: 8];
  assign link.rsp_cleanup_done = response[316 +: 1];
  assign link.write_ready = response[315 +: 1];
  assign link.control_req_ready = response[314 +: 1];
  assign link.control_rsp_valid = response[313 +: 1];
  assign link.control_rsp_owner_id = response[281 +: 32];
  assign link.control_rsp_instance_id = response[265 +: 16];
  assign link.control_rsp_epoch = response[233 +: 32];
  assign link.control_rsp_task_id = response[201 +: 32];
  assign link.control_rsp_request_seq = response[137 +: 64];
  assign link.control_rsp_context_id = response[121 +: 16];
  assign link.control_rsp_generation = response[89 +: 32];
  assign link.control_rsp_request_id = response[25 +: 64];
  assign link.control_rsp_status = response[9 +: 16];
  assign link.control_rsp_state = response[1 +: 8];
  assign link.control_rsp_cleanup_done = response[0 +: 1];
  assign observed = {link.req_valid, link.req_owner_id, link.req_instance_id, link.req_epoch, link.req_task_id, link.req_request_seq, link.req_context_id, link.req_generation, link.req_service_version, link.req_request_id, link.req_operation, link.req_staging_ref, link.req_length, link.req_policy_epoch, link.req_auth_valid, link.req_auth_ok, link.rsp_ready, link.write_valid, link.write_owner_id, link.write_instance_id, link.write_epoch, link.write_task_id, link.write_request_seq, link.write_context_id, link.write_generation, link.write_staging_ref, link.write_offset, link.write_data, link.write_keep, link.write_last, link.control_req_valid, link.control_req_owner_id, link.control_req_instance_id, link.control_req_epoch, link.control_req_task_id, link.control_req_request_seq, link.control_req_context_id, link.control_req_generation, link.control_req_service_version, link.control_req_request_id, link.control_req_operation, link.control_req_staging_ref, link.control_req_length, link.control_req_policy_epoch, link.control_req_auth_valid, link.control_req_auth_ok, link.control_rsp_ready};
  always @(posedge link.clk) if (link.reset_n !== 1'b0 && link.reset_n !== 1'b1) $fatal(1,"reset modport");
endmodule
module crypto_staging_case_512(input logic clk, reset_n, output logic done);
  import aix_crypto_staging_pkg::*;
  aix_crypto_staging_w512_req_t request;
  aix_crypto_staging_w512_rsp_t response;
  logic [822:0] expected;
  logic [1881:0] observed;
  aix_crypto_staging_if #(.DATA_W(512)) link (.clk(clk), .reset_n(reset_n));
  crypto_staging_peer_512 peer(link, expected, observed);
  aix_crypto_staging_flat_wrapper #(.DATA_W(512)) bridge(.link(link),
    .req_valid_i(request.req_valid),
    .req_ready_o(response.req_ready),
    .req_owner_id_i(request.req_owner_id),
    .req_instance_id_i(request.req_instance_id),
    .req_epoch_i(request.req_epoch),
    .req_task_id_i(request.req_task_id),
    .req_request_seq_i(request.req_request_seq),
    .req_context_id_i(request.req_context_id),
    .req_generation_i(request.req_generation),
    .req_service_version_i(request.req_service_version),
    .req_request_id_i(request.req_request_id),
    .req_operation_i(request.req_operation),
    .req_staging_ref_i(request.req_staging_ref),
    .req_length_i(request.req_length),
    .req_policy_epoch_i(request.req_policy_epoch),
    .req_auth_valid_i(request.req_auth_valid),
    .req_auth_ok_i(request.req_auth_ok),
    .rsp_valid_o(response.rsp_valid),
    .rsp_ready_i(request.rsp_ready),
    .rsp_owner_id_o(response.rsp_owner_id),
    .rsp_instance_id_o(response.rsp_instance_id),
    .rsp_epoch_o(response.rsp_epoch),
    .rsp_task_id_o(response.rsp_task_id),
    .rsp_request_seq_o(response.rsp_request_seq),
    .rsp_context_id_o(response.rsp_context_id),
    .rsp_generation_o(response.rsp_generation),
    .rsp_request_id_o(response.rsp_request_id),
    .rsp_status_o(response.rsp_status),
    .rsp_staging_ref_o(response.rsp_staging_ref),
    .rsp_reserved_bytes_o(response.rsp_reserved_bytes),
    .rsp_written_bytes_o(response.rsp_written_bytes),
    .rsp_state_o(response.rsp_state),
    .rsp_cleanup_done_o(response.rsp_cleanup_done),
    .write_valid_i(request.write_valid),
    .write_ready_o(response.write_ready),
    .write_owner_id_i(request.write_owner_id),
    .write_instance_id_i(request.write_instance_id),
    .write_epoch_i(request.write_epoch),
    .write_task_id_i(request.write_task_id),
    .write_request_seq_i(request.write_request_seq),
    .write_context_id_i(request.write_context_id),
    .write_generation_i(request.write_generation),
    .write_staging_ref_i(request.write_staging_ref),
    .write_offset_i(request.write_offset),
    .write_data_i(request.write_data),
    .write_keep_i(request.write_keep),
    .write_last_i(request.write_last),
    .control_req_valid_i(request.control_req_valid),
    .control_req_ready_o(response.control_req_ready),
    .control_req_owner_id_i(request.control_req_owner_id),
    .control_req_instance_id_i(request.control_req_instance_id),
    .control_req_epoch_i(request.control_req_epoch),
    .control_req_task_id_i(request.control_req_task_id),
    .control_req_request_seq_i(request.control_req_request_seq),
    .control_req_context_id_i(request.control_req_context_id),
    .control_req_generation_i(request.control_req_generation),
    .control_req_service_version_i(request.control_req_service_version),
    .control_req_request_id_i(request.control_req_request_id),
    .control_req_operation_i(request.control_req_operation),
    .control_req_staging_ref_i(request.control_req_staging_ref),
    .control_req_length_i(request.control_req_length),
    .control_req_policy_epoch_i(request.control_req_policy_epoch),
    .control_req_auth_valid_i(request.control_req_auth_valid),
    .control_req_auth_ok_i(request.control_req_auth_ok),
    .control_rsp_valid_o(response.control_rsp_valid),
    .control_rsp_ready_i(request.control_rsp_ready),
    .control_rsp_owner_id_o(response.control_rsp_owner_id),
    .control_rsp_instance_id_o(response.control_rsp_instance_id),
    .control_rsp_epoch_o(response.control_rsp_epoch),
    .control_rsp_task_id_o(response.control_rsp_task_id),
    .control_rsp_request_seq_o(response.control_rsp_request_seq),
    .control_rsp_context_id_o(response.control_rsp_context_id),
    .control_rsp_generation_o(response.control_rsp_generation),
    .control_rsp_request_id_o(response.control_rsp_request_id),
    .control_rsp_status_o(response.control_rsp_status),
    .control_rsp_state_o(response.control_rsp_state),
    .control_rsp_cleanup_done_o(response.control_rsp_cleanup_done)
  );
  function automatic logic [1881:0] pattern(input int seed);
    int unsigned state; state=32'h9e3779b9 ^ (32'h85ebca6b * seed);
    for (int i=0;i<1882;i++) begin
      state=1664525*state+1013904223; pattern[i]=state[31];
    end
  endfunction
  task automatic compare_paths;
    if (observed !== request) $fatal(1,"crypto_staging W512 forward wiring");
    if (response !== expected) $fatal(1,"crypto_staging W512 reverse wiring");
  endtask
  initial begin
    done=0; request='0; expected='0;
    if ($bits(request)!=1882 || $bits(response)!=823) $fatal(1,"aggregate width");
    if ($bits(link.req_valid)!=1) $fatal(1,"req_valid width");
    if ($bits(link.req_ready)!=1) $fatal(1,"req_ready width");
    if ($bits(link.req_owner_id)!=32) $fatal(1,"req_owner_id width");
    if ($bits(link.req_instance_id)!=16) $fatal(1,"req_instance_id width");
    if ($bits(link.req_epoch)!=32) $fatal(1,"req_epoch width");
    if ($bits(link.req_task_id)!=32) $fatal(1,"req_task_id width");
    if ($bits(link.req_request_seq)!=64) $fatal(1,"req_request_seq width");
    if ($bits(link.req_context_id)!=16) $fatal(1,"req_context_id width");
    if ($bits(link.req_generation)!=32) $fatal(1,"req_generation width");
    if ($bits(link.req_service_version)!=16) $fatal(1,"req_service_version width");
    if ($bits(link.req_request_id)!=64) $fatal(1,"req_request_id width");
    if ($bits(link.req_operation)!=8) $fatal(1,"req_operation width");
    if ($bits(link.req_staging_ref)!=64) $fatal(1,"req_staging_ref width");
    if ($bits(link.req_length)!=64) $fatal(1,"req_length width");
    if ($bits(link.req_policy_epoch)!=32) $fatal(1,"req_policy_epoch width");
    if ($bits(link.req_auth_valid)!=1) $fatal(1,"req_auth_valid width");
    if ($bits(link.req_auth_ok)!=1) $fatal(1,"req_auth_ok width");
    if ($bits(link.rsp_valid)!=1) $fatal(1,"rsp_valid width");
    if ($bits(link.rsp_ready)!=1) $fatal(1,"rsp_ready width");
    if ($bits(link.rsp_owner_id)!=32) $fatal(1,"rsp_owner_id width");
    if ($bits(link.rsp_instance_id)!=16) $fatal(1,"rsp_instance_id width");
    if ($bits(link.rsp_epoch)!=32) $fatal(1,"rsp_epoch width");
    if ($bits(link.rsp_task_id)!=32) $fatal(1,"rsp_task_id width");
    if ($bits(link.rsp_request_seq)!=64) $fatal(1,"rsp_request_seq width");
    if ($bits(link.rsp_context_id)!=16) $fatal(1,"rsp_context_id width");
    if ($bits(link.rsp_generation)!=32) $fatal(1,"rsp_generation width");
    if ($bits(link.rsp_request_id)!=64) $fatal(1,"rsp_request_id width");
    if ($bits(link.rsp_status)!=16) $fatal(1,"rsp_status width");
    if ($bits(link.rsp_staging_ref)!=64) $fatal(1,"rsp_staging_ref width");
    if ($bits(link.rsp_reserved_bytes)!=64) $fatal(1,"rsp_reserved_bytes width");
    if ($bits(link.rsp_written_bytes)!=64) $fatal(1,"rsp_written_bytes width");
    if ($bits(link.rsp_state)!=8) $fatal(1,"rsp_state width");
    if ($bits(link.rsp_cleanup_done)!=1) $fatal(1,"rsp_cleanup_done width");
    if ($bits(link.write_valid)!=1) $fatal(1,"write_valid width");
    if ($bits(link.write_ready)!=1) $fatal(1,"write_ready width");
    if ($bits(link.write_owner_id)!=32) $fatal(1,"write_owner_id width");
    if ($bits(link.write_instance_id)!=16) $fatal(1,"write_instance_id width");
    if ($bits(link.write_epoch)!=32) $fatal(1,"write_epoch width");
    if ($bits(link.write_task_id)!=32) $fatal(1,"write_task_id width");
    if ($bits(link.write_request_seq)!=64) $fatal(1,"write_request_seq width");
    if ($bits(link.write_context_id)!=16) $fatal(1,"write_context_id width");
    if ($bits(link.write_generation)!=32) $fatal(1,"write_generation width");
    if ($bits(link.write_staging_ref)!=64) $fatal(1,"write_staging_ref width");
    if ($bits(link.write_offset)!=64) $fatal(1,"write_offset width");
    if ($bits(link.write_data)!=512) $fatal(1,"write_data width");
    if ($bits(link.write_keep)!=64) $fatal(1,"write_keep width");
    if ($bits(link.write_last)!=1) $fatal(1,"write_last width");
    if ($bits(link.control_req_valid)!=1) $fatal(1,"control_req_valid width");
    if ($bits(link.control_req_ready)!=1) $fatal(1,"control_req_ready width");
    if ($bits(link.control_req_owner_id)!=32) $fatal(1,"control_req_owner_id width");
    if ($bits(link.control_req_instance_id)!=16) $fatal(1,"control_req_instance_id width");
    if ($bits(link.control_req_epoch)!=32) $fatal(1,"control_req_epoch width");
    if ($bits(link.control_req_task_id)!=32) $fatal(1,"control_req_task_id width");
    if ($bits(link.control_req_request_seq)!=64) $fatal(1,"control_req_request_seq width");
    if ($bits(link.control_req_context_id)!=16) $fatal(1,"control_req_context_id width");
    if ($bits(link.control_req_generation)!=32) $fatal(1,"control_req_generation width");
    if ($bits(link.control_req_service_version)!=16) $fatal(1,"control_req_service_version width");
    if ($bits(link.control_req_request_id)!=64) $fatal(1,"control_req_request_id width");
    if ($bits(link.control_req_operation)!=8) $fatal(1,"control_req_operation width");
    if ($bits(link.control_req_staging_ref)!=64) $fatal(1,"control_req_staging_ref width");
    if ($bits(link.control_req_length)!=64) $fatal(1,"control_req_length width");
    if ($bits(link.control_req_policy_epoch)!=32) $fatal(1,"control_req_policy_epoch width");
    if ($bits(link.control_req_auth_valid)!=1) $fatal(1,"control_req_auth_valid width");
    if ($bits(link.control_req_auth_ok)!=1) $fatal(1,"control_req_auth_ok width");
    if ($bits(link.control_rsp_valid)!=1) $fatal(1,"control_rsp_valid width");
    if ($bits(link.control_rsp_ready)!=1) $fatal(1,"control_rsp_ready width");
    if ($bits(link.control_rsp_owner_id)!=32) $fatal(1,"control_rsp_owner_id width");
    if ($bits(link.control_rsp_instance_id)!=16) $fatal(1,"control_rsp_instance_id width");
    if ($bits(link.control_rsp_epoch)!=32) $fatal(1,"control_rsp_epoch width");
    if ($bits(link.control_rsp_task_id)!=32) $fatal(1,"control_rsp_task_id width");
    if ($bits(link.control_rsp_request_seq)!=64) $fatal(1,"control_rsp_request_seq width");
    if ($bits(link.control_rsp_context_id)!=16) $fatal(1,"control_rsp_context_id width");
    if ($bits(link.control_rsp_generation)!=32) $fatal(1,"control_rsp_generation width");
    if ($bits(link.control_rsp_request_id)!=64) $fatal(1,"control_rsp_request_id width");
    if ($bits(link.control_rsp_status)!=16) $fatal(1,"control_rsp_status width");
    if ($bits(link.control_rsp_state)!=8) $fatal(1,"control_rsp_state width");
    if ($bits(link.control_rsp_cleanup_done)!=1) $fatal(1,"control_rsp_cleanup_done width");
    if ($bits(aix_crypto_staging_w512_req_payload_t)!=474) $fatal(1,"payload width");
    if ($bits(aix_crypto_staging_w512_rsp_payload_t)!=505) $fatal(1,"payload width");
    if ($bits(aix_crypto_staging_w512_write_payload_t)!=929) $fatal(1,"payload width");
    if ($bits(aix_crypto_staging_w512_control_req_payload_t)!=474) $fatal(1,"payload width");
    if ($bits(aix_crypto_staging_w512_control_rsp_payload_t)!=313) $fatal(1,"payload width");
    if (OPERATION_RESERVE!=1) $fatal(1,"OPERATION_RESERVE encoding");
    if (OPERATION_PREPARE!=2) $fatal(1,"OPERATION_PREPARE encoding");
    if (OPERATION_COMMIT!=3) $fatal(1,"OPERATION_COMMIT encoding");
    if (OPERATION_DESTROY!=4) $fatal(1,"OPERATION_DESTROY encoding");
    if (OPERATION_QUERY!=5) $fatal(1,"OPERATION_QUERY encoding");
    if (STATE_NONE!=0) $fatal(1,"STATE_NONE encoding");
    if (STATE_RESERVED!=1) $fatal(1,"STATE_RESERVED encoding");
    if (STATE_WRITTEN!=2) $fatal(1,"STATE_WRITTEN encoding");
    if (STATE_PREPARED!=3) $fatal(1,"STATE_PREPARED encoding");
    if (STATE_COMMITTED!=4) $fatal(1,"STATE_COMMITTED encoding");
    if (STATE_DESTROYED!=5) $fatal(1,"STATE_DESTROYED encoding");
    if (STATE_LOCKED!=6) $fatal(1,"STATE_LOCKED encoding");
    if (STATE_UNKNOWN!=7) $fatal(1,"STATE_UNKNOWN encoding");
    wait(reset_n); #1; compare_paths();
    request='1; expected='1; #1; compare_paths();
    for (int sample=1;sample<=128;sample++) begin
      request=1882'(pattern(sample)); expected=823'(pattern(sample+271));
      #1; compare_paths();
    end
    for (int bitno=0;bitno<1882;bitno++) begin
      request='0; request[bitno]=1'b1; #1; compare_paths(); end
    for (int bitno=0;bitno<823;bitno++) begin
      expected='0; expected[bitno]=1'b1; #1; compare_paths(); end
    $display("PASS crypto_staging DATA_W=512 fields=77"); done=1;
  end
endmodule
module tb_crypto_staging;
  logic clk=0; logic reset_n=0;
  logic [4:0] done;
  always #5 clk=~clk;
  initial begin #20; reset_n=1; end
  crypto_staging_case_32 case_32(clk,reset_n,done[0]);
  crypto_staging_case_64 case_64(clk,reset_n,done[1]);
  crypto_staging_case_128 case_128(clk,reset_n,done[2]);
  crypto_staging_case_256 case_256(clk,reset_n,done[3]);
  crypto_staging_case_512 case_512(clk,reset_n,done[4]);
  initial begin wait (&done); $display("HWIF_SMOKE_PASS crypto_staging"); $finish; end
  initial begin #100000; $fatal(1,"timeout"); end
endmodule
