// SPDX-License-Identifier: Apache-2.0
// Generated from the interface contract. Do not edit.
module aix_cci_flat_wrapper #(parameter int unsigned DATA_W = 128)(
  aix_cci_if.client link,
  input logic [(1)-1:0] cmd_valid_i,
  output logic [(1)-1:0] cmd_ready_o,
  input logic [(32)-1:0] cmd_owner_id_i,
  input logic [(16)-1:0] cmd_instance_id_i,
  input logic [(32)-1:0] cmd_epoch_i,
  input logic [(32)-1:0] cmd_task_id_i,
  input logic [(64)-1:0] cmd_request_seq_i,
  input logic [(16)-1:0] cmd_context_id_i,
  input logic [(32)-1:0] cmd_generation_i,
  input logic [(16)-1:0] cmd_operation_i,
  input logic [(8)-1:0] cmd_mode_i,
  input logic [(8)-1:0] cmd_direction_i,
  input logic [(8)-1:0] cmd_action_i,
  input logic [(1)-1:0] cmd_inherit_i,
  input logic [(32)-1:0] cmd_policy_epoch_i,
  input logic [(8)-1:0] cmd_key_count_i,
  input logic [(32)-1:0] cmd_key_bits_i,
  input logic [(416)-1:0] cmd_key_bindings_i,
  input logic [(64)-1:0] cmd_out_len_i,
  input logic [(32)-1:0] cmd_tag_len_i,
  input logic [(1)-1:0] cmd_message_total_known_i,
  input logic [(64)-1:0] cmd_message_total_len_i,
  input logic [(1)-1:0] cmd_aad_total_known_i,
  input logic [(64)-1:0] cmd_aad_total_len_i,
  input logic [(8)-1:0] cmd_segment_count_i,
  input logic [(1456)-1:0] cmd_segments_i,
  input logic [(1)-1:0] din_valid_i,
  output logic [(1)-1:0] din_ready_o,
  input logic [(32)-1:0] din_owner_id_i,
  input logic [(16)-1:0] din_instance_id_i,
  input logic [(32)-1:0] din_epoch_i,
  input logic [(32)-1:0] din_task_id_i,
  input logic [(64)-1:0] din_request_seq_i,
  input logic [(16)-1:0] din_context_id_i,
  input logic [(32)-1:0] din_generation_i,
  input logic [(16)-1:0] din_segment_index_i,
  input logic [(DATA_W)-1:0] din_data_i,
  input logic [(DATA_W/8)-1:0] din_keep_i,
  input logic [(1)-1:0] din_last_i,
  output logic [(1)-1:0] dout_valid_o,
  input logic [(1)-1:0] dout_ready_i,
  output logic [(32)-1:0] dout_owner_id_o,
  output logic [(16)-1:0] dout_instance_id_o,
  output logic [(32)-1:0] dout_epoch_o,
  output logic [(32)-1:0] dout_task_id_o,
  output logic [(64)-1:0] dout_request_seq_o,
  output logic [(16)-1:0] dout_context_id_o,
  output logic [(32)-1:0] dout_generation_o,
  output logic [(16)-1:0] dout_segment_index_o,
  output logic [(8)-1:0] dout_segment_kind_o,
  output logic [(DATA_W)-1:0] dout_data_o,
  output logic [(DATA_W/8)-1:0] dout_keep_o,
  output logic [(1)-1:0] dout_last_o,
  output logic [(1)-1:0] dout_provisional_o,
  output logic [(1)-1:0] dout_secret_o,
  output logic [(1)-1:0] cpl_valid_o,
  input logic [(1)-1:0] cpl_ready_i,
  output logic [(32)-1:0] cpl_owner_id_o,
  output logic [(16)-1:0] cpl_instance_id_o,
  output logic [(32)-1:0] cpl_epoch_o,
  output logic [(32)-1:0] cpl_task_id_o,
  output logic [(64)-1:0] cpl_request_seq_o,
  output logic [(16)-1:0] cpl_context_id_o,
  output logic [(32)-1:0] cpl_generation_o,
  output logic [(16)-1:0] cpl_status_o,
  output logic [(16)-1:0] cpl_detail_o,
  output logic [(1)-1:0] cpl_auth_valid_o,
  output logic [(1)-1:0] cpl_auth_ok_o,
  output logic [(64)-1:0] cpl_consumed_o,
  output logic [(64)-1:0] cpl_produced_o,
  output logic [(64)-1:0] cpl_delivered_o,
  output logic [(1)-1:0] cpl_context_alive_o,
  output logic [(1)-1:0] cpl_cleanup_done_o,
  output logic [(64)-1:0] cpl_result_ref_o,
  output logic [(64)-1:0] cpl_secret_result_bytes_o,
  output logic [(64)-1:0] cpl_replay_bytes_o,
  input logic [(1)-1:0] mgmt_req_valid_i,
  output logic [(1)-1:0] mgmt_req_ready_o,
  input logic [(32)-1:0] mgmt_req_owner_id_i,
  input logic [(16)-1:0] mgmt_req_instance_id_i,
  input logic [(32)-1:0] mgmt_req_epoch_i,
  input logic [(32)-1:0] mgmt_req_task_id_i,
  input logic [(64)-1:0] mgmt_req_request_seq_i,
  input logic [(16)-1:0] mgmt_req_context_id_i,
  input logic [(32)-1:0] mgmt_req_generation_i,
  input logic [(32)-1:0] mgmt_req_request_id_i,
  input logic [(8)-1:0] mgmt_req_operation_i,
  input logic [(8)-1:0] mgmt_req_scope_i,
  input logic [(64)-1:0] mgmt_req_key_ref_i,
  input logic [(32)-1:0] mgmt_req_key_epoch_i,
  output logic [(1)-1:0] mgmt_rsp_valid_o,
  input logic [(1)-1:0] mgmt_rsp_ready_i,
  output logic [(32)-1:0] mgmt_rsp_owner_id_o,
  output logic [(16)-1:0] mgmt_rsp_instance_id_o,
  output logic [(32)-1:0] mgmt_rsp_epoch_o,
  output logic [(32)-1:0] mgmt_rsp_task_id_o,
  output logic [(64)-1:0] mgmt_rsp_request_seq_o,
  output logic [(16)-1:0] mgmt_rsp_context_id_o,
  output logic [(32)-1:0] mgmt_rsp_generation_o,
  output logic [(32)-1:0] mgmt_rsp_request_id_o,
  output logic [(16)-1:0] mgmt_rsp_status_o,
  output logic [(1)-1:0] mgmt_rsp_drain_done_o,
  output logic [(1)-1:0] mgmt_rsp_cleanup_done_o,
  output logic [(1)-1:0] mgmt_rsp_committed_o,
  input logic [(1)-1:0] cap_req_valid_i,
  output logic [(1)-1:0] cap_req_ready_o,
  input logic [(32)-1:0] cap_req_request_id_i,
  input logic [(32)-1:0] cap_req_word_index_i,
  output logic [(1)-1:0] cap_rsp_valid_o,
  input logic [(1)-1:0] cap_rsp_ready_i,
  output logic [(32)-1:0] cap_rsp_request_id_o,
  output logic [(32)-1:0] cap_rsp_word_index_o,
  output logic [(16)-1:0] cap_rsp_status_o,
  output logic [(32)-1:0] cap_rsp_data_o,
  output logic [(1)-1:0] cap_rsp_last_o
);
  assign link.cmd_valid = cmd_valid_i;
  assign cmd_ready_o = link.cmd_ready;
  assign link.cmd_owner_id = cmd_owner_id_i;
  assign link.cmd_instance_id = cmd_instance_id_i;
  assign link.cmd_epoch = cmd_epoch_i;
  assign link.cmd_task_id = cmd_task_id_i;
  assign link.cmd_request_seq = cmd_request_seq_i;
  assign link.cmd_context_id = cmd_context_id_i;
  assign link.cmd_generation = cmd_generation_i;
  assign link.cmd_operation = cmd_operation_i;
  assign link.cmd_mode = cmd_mode_i;
  assign link.cmd_direction = cmd_direction_i;
  assign link.cmd_action = cmd_action_i;
  assign link.cmd_inherit = cmd_inherit_i;
  assign link.cmd_policy_epoch = cmd_policy_epoch_i;
  assign link.cmd_key_count = cmd_key_count_i;
  assign link.cmd_key_bits = cmd_key_bits_i;
  assign link.cmd_key_bindings = cmd_key_bindings_i;
  assign link.cmd_out_len = cmd_out_len_i;
  assign link.cmd_tag_len = cmd_tag_len_i;
  assign link.cmd_message_total_known = cmd_message_total_known_i;
  assign link.cmd_message_total_len = cmd_message_total_len_i;
  assign link.cmd_aad_total_known = cmd_aad_total_known_i;
  assign link.cmd_aad_total_len = cmd_aad_total_len_i;
  assign link.cmd_segment_count = cmd_segment_count_i;
  assign link.cmd_segments = cmd_segments_i;
  assign link.din_valid = din_valid_i;
  assign din_ready_o = link.din_ready;
  assign link.din_owner_id = din_owner_id_i;
  assign link.din_instance_id = din_instance_id_i;
  assign link.din_epoch = din_epoch_i;
  assign link.din_task_id = din_task_id_i;
  assign link.din_request_seq = din_request_seq_i;
  assign link.din_context_id = din_context_id_i;
  assign link.din_generation = din_generation_i;
  assign link.din_segment_index = din_segment_index_i;
  assign link.din_data = din_data_i;
  assign link.din_keep = din_keep_i;
  assign link.din_last = din_last_i;
  assign dout_valid_o = link.dout_valid;
  assign link.dout_ready = dout_ready_i;
  assign dout_owner_id_o = link.dout_owner_id;
  assign dout_instance_id_o = link.dout_instance_id;
  assign dout_epoch_o = link.dout_epoch;
  assign dout_task_id_o = link.dout_task_id;
  assign dout_request_seq_o = link.dout_request_seq;
  assign dout_context_id_o = link.dout_context_id;
  assign dout_generation_o = link.dout_generation;
  assign dout_segment_index_o = link.dout_segment_index;
  assign dout_segment_kind_o = link.dout_segment_kind;
  assign dout_data_o = link.dout_data;
  assign dout_keep_o = link.dout_keep;
  assign dout_last_o = link.dout_last;
  assign dout_provisional_o = link.dout_provisional;
  assign dout_secret_o = link.dout_secret;
  assign cpl_valid_o = link.cpl_valid;
  assign link.cpl_ready = cpl_ready_i;
  assign cpl_owner_id_o = link.cpl_owner_id;
  assign cpl_instance_id_o = link.cpl_instance_id;
  assign cpl_epoch_o = link.cpl_epoch;
  assign cpl_task_id_o = link.cpl_task_id;
  assign cpl_request_seq_o = link.cpl_request_seq;
  assign cpl_context_id_o = link.cpl_context_id;
  assign cpl_generation_o = link.cpl_generation;
  assign cpl_status_o = link.cpl_status;
  assign cpl_detail_o = link.cpl_detail;
  assign cpl_auth_valid_o = link.cpl_auth_valid;
  assign cpl_auth_ok_o = link.cpl_auth_ok;
  assign cpl_consumed_o = link.cpl_consumed;
  assign cpl_produced_o = link.cpl_produced;
  assign cpl_delivered_o = link.cpl_delivered;
  assign cpl_context_alive_o = link.cpl_context_alive;
  assign cpl_cleanup_done_o = link.cpl_cleanup_done;
  assign cpl_result_ref_o = link.cpl_result_ref;
  assign cpl_secret_result_bytes_o = link.cpl_secret_result_bytes;
  assign cpl_replay_bytes_o = link.cpl_replay_bytes;
  assign link.mgmt_req_valid = mgmt_req_valid_i;
  assign mgmt_req_ready_o = link.mgmt_req_ready;
  assign link.mgmt_req_owner_id = mgmt_req_owner_id_i;
  assign link.mgmt_req_instance_id = mgmt_req_instance_id_i;
  assign link.mgmt_req_epoch = mgmt_req_epoch_i;
  assign link.mgmt_req_task_id = mgmt_req_task_id_i;
  assign link.mgmt_req_request_seq = mgmt_req_request_seq_i;
  assign link.mgmt_req_context_id = mgmt_req_context_id_i;
  assign link.mgmt_req_generation = mgmt_req_generation_i;
  assign link.mgmt_req_request_id = mgmt_req_request_id_i;
  assign link.mgmt_req_operation = mgmt_req_operation_i;
  assign link.mgmt_req_scope = mgmt_req_scope_i;
  assign link.mgmt_req_key_ref = mgmt_req_key_ref_i;
  assign link.mgmt_req_key_epoch = mgmt_req_key_epoch_i;
  assign mgmt_rsp_valid_o = link.mgmt_rsp_valid;
  assign link.mgmt_rsp_ready = mgmt_rsp_ready_i;
  assign mgmt_rsp_owner_id_o = link.mgmt_rsp_owner_id;
  assign mgmt_rsp_instance_id_o = link.mgmt_rsp_instance_id;
  assign mgmt_rsp_epoch_o = link.mgmt_rsp_epoch;
  assign mgmt_rsp_task_id_o = link.mgmt_rsp_task_id;
  assign mgmt_rsp_request_seq_o = link.mgmt_rsp_request_seq;
  assign mgmt_rsp_context_id_o = link.mgmt_rsp_context_id;
  assign mgmt_rsp_generation_o = link.mgmt_rsp_generation;
  assign mgmt_rsp_request_id_o = link.mgmt_rsp_request_id;
  assign mgmt_rsp_status_o = link.mgmt_rsp_status;
  assign mgmt_rsp_drain_done_o = link.mgmt_rsp_drain_done;
  assign mgmt_rsp_cleanup_done_o = link.mgmt_rsp_cleanup_done;
  assign mgmt_rsp_committed_o = link.mgmt_rsp_committed;
  assign link.cap_req_valid = cap_req_valid_i;
  assign cap_req_ready_o = link.cap_req_ready;
  assign link.cap_req_request_id = cap_req_request_id_i;
  assign link.cap_req_word_index = cap_req_word_index_i;
  assign cap_rsp_valid_o = link.cap_rsp_valid;
  assign link.cap_rsp_ready = cap_rsp_ready_i;
  assign cap_rsp_request_id_o = link.cap_rsp_request_id;
  assign cap_rsp_word_index_o = link.cap_rsp_word_index;
  assign cap_rsp_status_o = link.cap_rsp_status;
  assign cap_rsp_data_o = link.cap_rsp_data;
  assign cap_rsp_last_o = link.cap_rsp_last;
endmodule
