// SPDX-License-Identifier: Apache-2.0
// Generated from the interface contract. Do not edit.

package aix_cci_pkg;
  localparam int unsigned DATA_W = 128;
  localparam int unsigned OPERATION_SM3_DIGEST = 1;
  localparam int unsigned OPERATION_HMAC_SM3_GENERATE = 2;
  localparam int unsigned OPERATION_HMAC_SM3_VERIFY = 3;
  localparam int unsigned OPERATION_AES_GCM = 16;
  localparam int unsigned MODE_NONE = 0;
  localparam int unsigned MODE_GCM_BASE = 1;
  localparam int unsigned MODE_GCM_EXT = 2;
  localparam int unsigned DIRECTION_NONE = 0;
  localparam int unsigned DIRECTION_ENCRYPT = 1;
  localparam int unsigned DIRECTION_DECRYPT = 2;
  localparam int unsigned ACTION_ONESHOT = 0;
  localparam int unsigned ACTION_INIT = 1;
  localparam int unsigned ACTION_UPDATE = 2;
  localparam int unsigned ACTION_FINAL = 3;
  localparam int unsigned SEGMENT_PAYLOAD = 1;
  localparam int unsigned SEGMENT_AAD = 2;
  localparam int unsigned SEGMENT_NONCE_IV = 3;
  localparam int unsigned SEGMENT_EXPECTED_TAG = 4;
  localparam int unsigned SEGMENT_DIGEST_TAG = 5;
  localparam int unsigned STATUS_OK = 0;
  localparam int unsigned STATUS_UNSUPPORTED = 1;
  localparam int unsigned STATUS_INVALID_PARAM = 2;
  localparam int unsigned STATUS_SEGMENT_ERROR = 3;
  localparam int unsigned STATUS_LENGTH_ERROR = 4;
  localparam int unsigned STATUS_KEY_DENIED = 5;
  localparam int unsigned STATUS_AUTH_FAIL = 6;
  localparam int unsigned STATUS_CANCELLED = 7;
  localparam int unsigned STATUS_ENTROPY_ERROR = 8;
  localparam int unsigned STATUS_INTERNAL_ERROR = 9;
  localparam int unsigned STATUS_SERVICE_TIMEOUT = 10;
  localparam int unsigned STATUS_DELIVERY_ERROR = 11;
  localparam int unsigned STATUS_DELIVERY_UNKNOWN = 12;
  localparam int unsigned STATUS_TOO_LATE = 13;
  localparam int unsigned STATUS_BUSY = 14;
  localparam int unsigned DETAIL_NONE = 0;
  localparam int unsigned DETAIL_ID_CONFLICT = 1;
  localparam int unsigned MANAGEMENT_CANCEL = 1;
  localparam int unsigned MANAGEMENT_ZEROIZE = 2;
  localparam int unsigned MANAGEMENT_QUIESCE = 3;
  localparam int unsigned MANAGEMENT_REVOKE = 4;
  localparam int unsigned MANAGEMENT_QUERY = 5;
  localparam int unsigned SCOPE_COMMAND = 0;
  localparam int unsigned SCOPE_CONTEXT = 1;
  localparam int unsigned SCOPE_INSTANCE = 2;
  localparam int unsigned SCOPE_OWNER = 3;
  localparam int unsigned SCOPE_KEY_EPOCH = 4;
  typedef struct packed {
    logic [0:0] cmd_valid;
    logic [31:0] cmd_owner_id;
    logic [15:0] cmd_instance_id;
    logic [31:0] cmd_epoch;
    logic [31:0] cmd_task_id;
    logic [63:0] cmd_request_seq;
    logic [15:0] cmd_context_id;
    logic [31:0] cmd_generation;
    logic [15:0] cmd_operation;
    logic [7:0] cmd_mode;
    logic [7:0] cmd_direction;
    logic [7:0] cmd_action;
    logic [0:0] cmd_inherit;
    logic [31:0] cmd_policy_epoch;
    logic [7:0] cmd_key_count;
    logic [31:0] cmd_key_bits;
    logic [415:0] cmd_key_bindings;
    logic [63:0] cmd_out_len;
    logic [31:0] cmd_tag_len;
    logic [0:0] cmd_message_total_known;
    logic [63:0] cmd_message_total_len;
    logic [0:0] cmd_aad_total_known;
    logic [63:0] cmd_aad_total_len;
    logic [7:0] cmd_segment_count;
    logic [1455:0] cmd_segments;
    logic [0:0] din_valid;
    logic [31:0] din_owner_id;
    logic [15:0] din_instance_id;
    logic [31:0] din_epoch;
    logic [31:0] din_task_id;
    logic [63:0] din_request_seq;
    logic [15:0] din_context_id;
    logic [31:0] din_generation;
    logic [15:0] din_segment_index;
    logic [31:0] din_data;
    logic [3:0] din_keep;
    logic [0:0] din_last;
    logic [0:0] dout_ready;
    logic [0:0] cpl_ready;
    logic [0:0] mgmt_req_valid;
    logic [31:0] mgmt_req_owner_id;
    logic [15:0] mgmt_req_instance_id;
    logic [31:0] mgmt_req_epoch;
    logic [31:0] mgmt_req_task_id;
    logic [63:0] mgmt_req_request_seq;
    logic [15:0] mgmt_req_context_id;
    logic [31:0] mgmt_req_generation;
    logic [31:0] mgmt_req_request_id;
    logic [7:0] mgmt_req_operation;
    logic [7:0] mgmt_req_scope;
    logic [63:0] mgmt_req_key_ref;
    logic [31:0] mgmt_req_key_epoch;
    logic [0:0] mgmt_rsp_ready;
    logic [0:0] cap_req_valid;
    logic [31:0] cap_req_request_id;
    logic [31:0] cap_req_word_index;
    logic [0:0] cap_rsp_ready;
  } aix_cci_w32_req_t;
  typedef struct packed {
    logic [0:0] cmd_ready;
    logic [0:0] din_ready;
    logic [0:0] dout_valid;
    logic [31:0] dout_owner_id;
    logic [15:0] dout_instance_id;
    logic [31:0] dout_epoch;
    logic [31:0] dout_task_id;
    logic [63:0] dout_request_seq;
    logic [15:0] dout_context_id;
    logic [31:0] dout_generation;
    logic [15:0] dout_segment_index;
    logic [7:0] dout_segment_kind;
    logic [31:0] dout_data;
    logic [3:0] dout_keep;
    logic [0:0] dout_last;
    logic [0:0] dout_provisional;
    logic [0:0] dout_secret;
    logic [0:0] cpl_valid;
    logic [31:0] cpl_owner_id;
    logic [15:0] cpl_instance_id;
    logic [31:0] cpl_epoch;
    logic [31:0] cpl_task_id;
    logic [63:0] cpl_request_seq;
    logic [15:0] cpl_context_id;
    logic [31:0] cpl_generation;
    logic [15:0] cpl_status;
    logic [15:0] cpl_detail;
    logic [0:0] cpl_auth_valid;
    logic [0:0] cpl_auth_ok;
    logic [63:0] cpl_consumed;
    logic [63:0] cpl_produced;
    logic [63:0] cpl_delivered;
    logic [0:0] cpl_context_alive;
    logic [0:0] cpl_cleanup_done;
    logic [63:0] cpl_result_ref;
    logic [63:0] cpl_secret_result_bytes;
    logic [63:0] cpl_replay_bytes;
    logic [0:0] mgmt_req_ready;
    logic [0:0] mgmt_rsp_valid;
    logic [31:0] mgmt_rsp_owner_id;
    logic [15:0] mgmt_rsp_instance_id;
    logic [31:0] mgmt_rsp_epoch;
    logic [31:0] mgmt_rsp_task_id;
    logic [63:0] mgmt_rsp_request_seq;
    logic [15:0] mgmt_rsp_context_id;
    logic [31:0] mgmt_rsp_generation;
    logic [31:0] mgmt_rsp_request_id;
    logic [15:0] mgmt_rsp_status;
    logic [0:0] mgmt_rsp_drain_done;
    logic [0:0] mgmt_rsp_cleanup_done;
    logic [0:0] mgmt_rsp_committed;
    logic [0:0] cap_req_ready;
    logic [0:0] cap_rsp_valid;
    logic [31:0] cap_rsp_request_id;
    logic [31:0] cap_rsp_word_index;
    logic [15:0] cap_rsp_status;
    logic [31:0] cap_rsp_data;
    logic [0:0] cap_rsp_last;
  } aix_cci_w32_rsp_t;
  typedef struct packed {
    logic [31:0] cmd_owner_id;
    logic [15:0] cmd_instance_id;
    logic [31:0] cmd_epoch;
    logic [31:0] cmd_task_id;
    logic [63:0] cmd_request_seq;
    logic [15:0] cmd_context_id;
    logic [31:0] cmd_generation;
    logic [15:0] cmd_operation;
    logic [7:0] cmd_mode;
    logic [7:0] cmd_direction;
    logic [7:0] cmd_action;
    logic [0:0] cmd_inherit;
    logic [31:0] cmd_policy_epoch;
    logic [7:0] cmd_key_count;
    logic [31:0] cmd_key_bits;
    logic [415:0] cmd_key_bindings;
    logic [63:0] cmd_out_len;
    logic [31:0] cmd_tag_len;
    logic [0:0] cmd_message_total_known;
    logic [63:0] cmd_message_total_len;
    logic [0:0] cmd_aad_total_known;
    logic [63:0] cmd_aad_total_len;
    logic [7:0] cmd_segment_count;
    logic [1455:0] cmd_segments;
  } aix_cci_w32_cmd_payload_t;
  typedef struct packed {
    logic [31:0] din_owner_id;
    logic [15:0] din_instance_id;
    logic [31:0] din_epoch;
    logic [31:0] din_task_id;
    logic [63:0] din_request_seq;
    logic [15:0] din_context_id;
    logic [31:0] din_generation;
    logic [15:0] din_segment_index;
    logic [31:0] din_data;
    logic [3:0] din_keep;
    logic [0:0] din_last;
  } aix_cci_w32_din_payload_t;
  typedef struct packed {
    logic [31:0] dout_owner_id;
    logic [15:0] dout_instance_id;
    logic [31:0] dout_epoch;
    logic [31:0] dout_task_id;
    logic [63:0] dout_request_seq;
    logic [15:0] dout_context_id;
    logic [31:0] dout_generation;
    logic [15:0] dout_segment_index;
    logic [7:0] dout_segment_kind;
    logic [31:0] dout_data;
    logic [3:0] dout_keep;
    logic [0:0] dout_last;
    logic [0:0] dout_provisional;
    logic [0:0] dout_secret;
  } aix_cci_w32_dout_payload_t;
  typedef struct packed {
    logic [31:0] cpl_owner_id;
    logic [15:0] cpl_instance_id;
    logic [31:0] cpl_epoch;
    logic [31:0] cpl_task_id;
    logic [63:0] cpl_request_seq;
    logic [15:0] cpl_context_id;
    logic [31:0] cpl_generation;
    logic [15:0] cpl_status;
    logic [15:0] cpl_detail;
    logic [0:0] cpl_auth_valid;
    logic [0:0] cpl_auth_ok;
    logic [63:0] cpl_consumed;
    logic [63:0] cpl_produced;
    logic [63:0] cpl_delivered;
    logic [0:0] cpl_context_alive;
    logic [0:0] cpl_cleanup_done;
    logic [63:0] cpl_result_ref;
    logic [63:0] cpl_secret_result_bytes;
    logic [63:0] cpl_replay_bytes;
  } aix_cci_w32_cpl_payload_t;
  typedef struct packed {
    logic [31:0] mgmt_req_owner_id;
    logic [15:0] mgmt_req_instance_id;
    logic [31:0] mgmt_req_epoch;
    logic [31:0] mgmt_req_task_id;
    logic [63:0] mgmt_req_request_seq;
    logic [15:0] mgmt_req_context_id;
    logic [31:0] mgmt_req_generation;
    logic [31:0] mgmt_req_request_id;
    logic [7:0] mgmt_req_operation;
    logic [7:0] mgmt_req_scope;
    logic [63:0] mgmt_req_key_ref;
    logic [31:0] mgmt_req_key_epoch;
  } aix_cci_w32_mgmt_req_payload_t;
  typedef struct packed {
    logic [31:0] mgmt_rsp_owner_id;
    logic [15:0] mgmt_rsp_instance_id;
    logic [31:0] mgmt_rsp_epoch;
    logic [31:0] mgmt_rsp_task_id;
    logic [63:0] mgmt_rsp_request_seq;
    logic [15:0] mgmt_rsp_context_id;
    logic [31:0] mgmt_rsp_generation;
    logic [31:0] mgmt_rsp_request_id;
    logic [15:0] mgmt_rsp_status;
    logic [0:0] mgmt_rsp_drain_done;
    logic [0:0] mgmt_rsp_cleanup_done;
    logic [0:0] mgmt_rsp_committed;
  } aix_cci_w32_mgmt_rsp_payload_t;
  typedef struct packed {
    logic [31:0] cap_req_request_id;
    logic [31:0] cap_req_word_index;
  } aix_cci_w32_cap_req_payload_t;
  typedef struct packed {
    logic [31:0] cap_rsp_request_id;
    logic [31:0] cap_rsp_word_index;
    logic [15:0] cap_rsp_status;
    logic [31:0] cap_rsp_data;
    logic [0:0] cap_rsp_last;
  } aix_cci_w32_cap_rsp_payload_t;
  typedef struct packed {
    logic [0:0] cmd_valid;
    logic [31:0] cmd_owner_id;
    logic [15:0] cmd_instance_id;
    logic [31:0] cmd_epoch;
    logic [31:0] cmd_task_id;
    logic [63:0] cmd_request_seq;
    logic [15:0] cmd_context_id;
    logic [31:0] cmd_generation;
    logic [15:0] cmd_operation;
    logic [7:0] cmd_mode;
    logic [7:0] cmd_direction;
    logic [7:0] cmd_action;
    logic [0:0] cmd_inherit;
    logic [31:0] cmd_policy_epoch;
    logic [7:0] cmd_key_count;
    logic [31:0] cmd_key_bits;
    logic [415:0] cmd_key_bindings;
    logic [63:0] cmd_out_len;
    logic [31:0] cmd_tag_len;
    logic [0:0] cmd_message_total_known;
    logic [63:0] cmd_message_total_len;
    logic [0:0] cmd_aad_total_known;
    logic [63:0] cmd_aad_total_len;
    logic [7:0] cmd_segment_count;
    logic [1455:0] cmd_segments;
    logic [0:0] din_valid;
    logic [31:0] din_owner_id;
    logic [15:0] din_instance_id;
    logic [31:0] din_epoch;
    logic [31:0] din_task_id;
    logic [63:0] din_request_seq;
    logic [15:0] din_context_id;
    logic [31:0] din_generation;
    logic [15:0] din_segment_index;
    logic [63:0] din_data;
    logic [7:0] din_keep;
    logic [0:0] din_last;
    logic [0:0] dout_ready;
    logic [0:0] cpl_ready;
    logic [0:0] mgmt_req_valid;
    logic [31:0] mgmt_req_owner_id;
    logic [15:0] mgmt_req_instance_id;
    logic [31:0] mgmt_req_epoch;
    logic [31:0] mgmt_req_task_id;
    logic [63:0] mgmt_req_request_seq;
    logic [15:0] mgmt_req_context_id;
    logic [31:0] mgmt_req_generation;
    logic [31:0] mgmt_req_request_id;
    logic [7:0] mgmt_req_operation;
    logic [7:0] mgmt_req_scope;
    logic [63:0] mgmt_req_key_ref;
    logic [31:0] mgmt_req_key_epoch;
    logic [0:0] mgmt_rsp_ready;
    logic [0:0] cap_req_valid;
    logic [31:0] cap_req_request_id;
    logic [31:0] cap_req_word_index;
    logic [0:0] cap_rsp_ready;
  } aix_cci_w64_req_t;
  typedef struct packed {
    logic [0:0] cmd_ready;
    logic [0:0] din_ready;
    logic [0:0] dout_valid;
    logic [31:0] dout_owner_id;
    logic [15:0] dout_instance_id;
    logic [31:0] dout_epoch;
    logic [31:0] dout_task_id;
    logic [63:0] dout_request_seq;
    logic [15:0] dout_context_id;
    logic [31:0] dout_generation;
    logic [15:0] dout_segment_index;
    logic [7:0] dout_segment_kind;
    logic [63:0] dout_data;
    logic [7:0] dout_keep;
    logic [0:0] dout_last;
    logic [0:0] dout_provisional;
    logic [0:0] dout_secret;
    logic [0:0] cpl_valid;
    logic [31:0] cpl_owner_id;
    logic [15:0] cpl_instance_id;
    logic [31:0] cpl_epoch;
    logic [31:0] cpl_task_id;
    logic [63:0] cpl_request_seq;
    logic [15:0] cpl_context_id;
    logic [31:0] cpl_generation;
    logic [15:0] cpl_status;
    logic [15:0] cpl_detail;
    logic [0:0] cpl_auth_valid;
    logic [0:0] cpl_auth_ok;
    logic [63:0] cpl_consumed;
    logic [63:0] cpl_produced;
    logic [63:0] cpl_delivered;
    logic [0:0] cpl_context_alive;
    logic [0:0] cpl_cleanup_done;
    logic [63:0] cpl_result_ref;
    logic [63:0] cpl_secret_result_bytes;
    logic [63:0] cpl_replay_bytes;
    logic [0:0] mgmt_req_ready;
    logic [0:0] mgmt_rsp_valid;
    logic [31:0] mgmt_rsp_owner_id;
    logic [15:0] mgmt_rsp_instance_id;
    logic [31:0] mgmt_rsp_epoch;
    logic [31:0] mgmt_rsp_task_id;
    logic [63:0] mgmt_rsp_request_seq;
    logic [15:0] mgmt_rsp_context_id;
    logic [31:0] mgmt_rsp_generation;
    logic [31:0] mgmt_rsp_request_id;
    logic [15:0] mgmt_rsp_status;
    logic [0:0] mgmt_rsp_drain_done;
    logic [0:0] mgmt_rsp_cleanup_done;
    logic [0:0] mgmt_rsp_committed;
    logic [0:0] cap_req_ready;
    logic [0:0] cap_rsp_valid;
    logic [31:0] cap_rsp_request_id;
    logic [31:0] cap_rsp_word_index;
    logic [15:0] cap_rsp_status;
    logic [31:0] cap_rsp_data;
    logic [0:0] cap_rsp_last;
  } aix_cci_w64_rsp_t;
  typedef struct packed {
    logic [31:0] cmd_owner_id;
    logic [15:0] cmd_instance_id;
    logic [31:0] cmd_epoch;
    logic [31:0] cmd_task_id;
    logic [63:0] cmd_request_seq;
    logic [15:0] cmd_context_id;
    logic [31:0] cmd_generation;
    logic [15:0] cmd_operation;
    logic [7:0] cmd_mode;
    logic [7:0] cmd_direction;
    logic [7:0] cmd_action;
    logic [0:0] cmd_inherit;
    logic [31:0] cmd_policy_epoch;
    logic [7:0] cmd_key_count;
    logic [31:0] cmd_key_bits;
    logic [415:0] cmd_key_bindings;
    logic [63:0] cmd_out_len;
    logic [31:0] cmd_tag_len;
    logic [0:0] cmd_message_total_known;
    logic [63:0] cmd_message_total_len;
    logic [0:0] cmd_aad_total_known;
    logic [63:0] cmd_aad_total_len;
    logic [7:0] cmd_segment_count;
    logic [1455:0] cmd_segments;
  } aix_cci_w64_cmd_payload_t;
  typedef struct packed {
    logic [31:0] din_owner_id;
    logic [15:0] din_instance_id;
    logic [31:0] din_epoch;
    logic [31:0] din_task_id;
    logic [63:0] din_request_seq;
    logic [15:0] din_context_id;
    logic [31:0] din_generation;
    logic [15:0] din_segment_index;
    logic [63:0] din_data;
    logic [7:0] din_keep;
    logic [0:0] din_last;
  } aix_cci_w64_din_payload_t;
  typedef struct packed {
    logic [31:0] dout_owner_id;
    logic [15:0] dout_instance_id;
    logic [31:0] dout_epoch;
    logic [31:0] dout_task_id;
    logic [63:0] dout_request_seq;
    logic [15:0] dout_context_id;
    logic [31:0] dout_generation;
    logic [15:0] dout_segment_index;
    logic [7:0] dout_segment_kind;
    logic [63:0] dout_data;
    logic [7:0] dout_keep;
    logic [0:0] dout_last;
    logic [0:0] dout_provisional;
    logic [0:0] dout_secret;
  } aix_cci_w64_dout_payload_t;
  typedef struct packed {
    logic [31:0] cpl_owner_id;
    logic [15:0] cpl_instance_id;
    logic [31:0] cpl_epoch;
    logic [31:0] cpl_task_id;
    logic [63:0] cpl_request_seq;
    logic [15:0] cpl_context_id;
    logic [31:0] cpl_generation;
    logic [15:0] cpl_status;
    logic [15:0] cpl_detail;
    logic [0:0] cpl_auth_valid;
    logic [0:0] cpl_auth_ok;
    logic [63:0] cpl_consumed;
    logic [63:0] cpl_produced;
    logic [63:0] cpl_delivered;
    logic [0:0] cpl_context_alive;
    logic [0:0] cpl_cleanup_done;
    logic [63:0] cpl_result_ref;
    logic [63:0] cpl_secret_result_bytes;
    logic [63:0] cpl_replay_bytes;
  } aix_cci_w64_cpl_payload_t;
  typedef struct packed {
    logic [31:0] mgmt_req_owner_id;
    logic [15:0] mgmt_req_instance_id;
    logic [31:0] mgmt_req_epoch;
    logic [31:0] mgmt_req_task_id;
    logic [63:0] mgmt_req_request_seq;
    logic [15:0] mgmt_req_context_id;
    logic [31:0] mgmt_req_generation;
    logic [31:0] mgmt_req_request_id;
    logic [7:0] mgmt_req_operation;
    logic [7:0] mgmt_req_scope;
    logic [63:0] mgmt_req_key_ref;
    logic [31:0] mgmt_req_key_epoch;
  } aix_cci_w64_mgmt_req_payload_t;
  typedef struct packed {
    logic [31:0] mgmt_rsp_owner_id;
    logic [15:0] mgmt_rsp_instance_id;
    logic [31:0] mgmt_rsp_epoch;
    logic [31:0] mgmt_rsp_task_id;
    logic [63:0] mgmt_rsp_request_seq;
    logic [15:0] mgmt_rsp_context_id;
    logic [31:0] mgmt_rsp_generation;
    logic [31:0] mgmt_rsp_request_id;
    logic [15:0] mgmt_rsp_status;
    logic [0:0] mgmt_rsp_drain_done;
    logic [0:0] mgmt_rsp_cleanup_done;
    logic [0:0] mgmt_rsp_committed;
  } aix_cci_w64_mgmt_rsp_payload_t;
  typedef struct packed {
    logic [31:0] cap_req_request_id;
    logic [31:0] cap_req_word_index;
  } aix_cci_w64_cap_req_payload_t;
  typedef struct packed {
    logic [31:0] cap_rsp_request_id;
    logic [31:0] cap_rsp_word_index;
    logic [15:0] cap_rsp_status;
    logic [31:0] cap_rsp_data;
    logic [0:0] cap_rsp_last;
  } aix_cci_w64_cap_rsp_payload_t;
  typedef struct packed {
    logic [0:0] cmd_valid;
    logic [31:0] cmd_owner_id;
    logic [15:0] cmd_instance_id;
    logic [31:0] cmd_epoch;
    logic [31:0] cmd_task_id;
    logic [63:0] cmd_request_seq;
    logic [15:0] cmd_context_id;
    logic [31:0] cmd_generation;
    logic [15:0] cmd_operation;
    logic [7:0] cmd_mode;
    logic [7:0] cmd_direction;
    logic [7:0] cmd_action;
    logic [0:0] cmd_inherit;
    logic [31:0] cmd_policy_epoch;
    logic [7:0] cmd_key_count;
    logic [31:0] cmd_key_bits;
    logic [415:0] cmd_key_bindings;
    logic [63:0] cmd_out_len;
    logic [31:0] cmd_tag_len;
    logic [0:0] cmd_message_total_known;
    logic [63:0] cmd_message_total_len;
    logic [0:0] cmd_aad_total_known;
    logic [63:0] cmd_aad_total_len;
    logic [7:0] cmd_segment_count;
    logic [1455:0] cmd_segments;
    logic [0:0] din_valid;
    logic [31:0] din_owner_id;
    logic [15:0] din_instance_id;
    logic [31:0] din_epoch;
    logic [31:0] din_task_id;
    logic [63:0] din_request_seq;
    logic [15:0] din_context_id;
    logic [31:0] din_generation;
    logic [15:0] din_segment_index;
    logic [127:0] din_data;
    logic [15:0] din_keep;
    logic [0:0] din_last;
    logic [0:0] dout_ready;
    logic [0:0] cpl_ready;
    logic [0:0] mgmt_req_valid;
    logic [31:0] mgmt_req_owner_id;
    logic [15:0] mgmt_req_instance_id;
    logic [31:0] mgmt_req_epoch;
    logic [31:0] mgmt_req_task_id;
    logic [63:0] mgmt_req_request_seq;
    logic [15:0] mgmt_req_context_id;
    logic [31:0] mgmt_req_generation;
    logic [31:0] mgmt_req_request_id;
    logic [7:0] mgmt_req_operation;
    logic [7:0] mgmt_req_scope;
    logic [63:0] mgmt_req_key_ref;
    logic [31:0] mgmt_req_key_epoch;
    logic [0:0] mgmt_rsp_ready;
    logic [0:0] cap_req_valid;
    logic [31:0] cap_req_request_id;
    logic [31:0] cap_req_word_index;
    logic [0:0] cap_rsp_ready;
  } aix_cci_w128_req_t;
  typedef struct packed {
    logic [0:0] cmd_ready;
    logic [0:0] din_ready;
    logic [0:0] dout_valid;
    logic [31:0] dout_owner_id;
    logic [15:0] dout_instance_id;
    logic [31:0] dout_epoch;
    logic [31:0] dout_task_id;
    logic [63:0] dout_request_seq;
    logic [15:0] dout_context_id;
    logic [31:0] dout_generation;
    logic [15:0] dout_segment_index;
    logic [7:0] dout_segment_kind;
    logic [127:0] dout_data;
    logic [15:0] dout_keep;
    logic [0:0] dout_last;
    logic [0:0] dout_provisional;
    logic [0:0] dout_secret;
    logic [0:0] cpl_valid;
    logic [31:0] cpl_owner_id;
    logic [15:0] cpl_instance_id;
    logic [31:0] cpl_epoch;
    logic [31:0] cpl_task_id;
    logic [63:0] cpl_request_seq;
    logic [15:0] cpl_context_id;
    logic [31:0] cpl_generation;
    logic [15:0] cpl_status;
    logic [15:0] cpl_detail;
    logic [0:0] cpl_auth_valid;
    logic [0:0] cpl_auth_ok;
    logic [63:0] cpl_consumed;
    logic [63:0] cpl_produced;
    logic [63:0] cpl_delivered;
    logic [0:0] cpl_context_alive;
    logic [0:0] cpl_cleanup_done;
    logic [63:0] cpl_result_ref;
    logic [63:0] cpl_secret_result_bytes;
    logic [63:0] cpl_replay_bytes;
    logic [0:0] mgmt_req_ready;
    logic [0:0] mgmt_rsp_valid;
    logic [31:0] mgmt_rsp_owner_id;
    logic [15:0] mgmt_rsp_instance_id;
    logic [31:0] mgmt_rsp_epoch;
    logic [31:0] mgmt_rsp_task_id;
    logic [63:0] mgmt_rsp_request_seq;
    logic [15:0] mgmt_rsp_context_id;
    logic [31:0] mgmt_rsp_generation;
    logic [31:0] mgmt_rsp_request_id;
    logic [15:0] mgmt_rsp_status;
    logic [0:0] mgmt_rsp_drain_done;
    logic [0:0] mgmt_rsp_cleanup_done;
    logic [0:0] mgmt_rsp_committed;
    logic [0:0] cap_req_ready;
    logic [0:0] cap_rsp_valid;
    logic [31:0] cap_rsp_request_id;
    logic [31:0] cap_rsp_word_index;
    logic [15:0] cap_rsp_status;
    logic [31:0] cap_rsp_data;
    logic [0:0] cap_rsp_last;
  } aix_cci_w128_rsp_t;
  typedef struct packed {
    logic [31:0] cmd_owner_id;
    logic [15:0] cmd_instance_id;
    logic [31:0] cmd_epoch;
    logic [31:0] cmd_task_id;
    logic [63:0] cmd_request_seq;
    logic [15:0] cmd_context_id;
    logic [31:0] cmd_generation;
    logic [15:0] cmd_operation;
    logic [7:0] cmd_mode;
    logic [7:0] cmd_direction;
    logic [7:0] cmd_action;
    logic [0:0] cmd_inherit;
    logic [31:0] cmd_policy_epoch;
    logic [7:0] cmd_key_count;
    logic [31:0] cmd_key_bits;
    logic [415:0] cmd_key_bindings;
    logic [63:0] cmd_out_len;
    logic [31:0] cmd_tag_len;
    logic [0:0] cmd_message_total_known;
    logic [63:0] cmd_message_total_len;
    logic [0:0] cmd_aad_total_known;
    logic [63:0] cmd_aad_total_len;
    logic [7:0] cmd_segment_count;
    logic [1455:0] cmd_segments;
  } aix_cci_w128_cmd_payload_t;
  typedef struct packed {
    logic [31:0] din_owner_id;
    logic [15:0] din_instance_id;
    logic [31:0] din_epoch;
    logic [31:0] din_task_id;
    logic [63:0] din_request_seq;
    logic [15:0] din_context_id;
    logic [31:0] din_generation;
    logic [15:0] din_segment_index;
    logic [127:0] din_data;
    logic [15:0] din_keep;
    logic [0:0] din_last;
  } aix_cci_w128_din_payload_t;
  typedef struct packed {
    logic [31:0] dout_owner_id;
    logic [15:0] dout_instance_id;
    logic [31:0] dout_epoch;
    logic [31:0] dout_task_id;
    logic [63:0] dout_request_seq;
    logic [15:0] dout_context_id;
    logic [31:0] dout_generation;
    logic [15:0] dout_segment_index;
    logic [7:0] dout_segment_kind;
    logic [127:0] dout_data;
    logic [15:0] dout_keep;
    logic [0:0] dout_last;
    logic [0:0] dout_provisional;
    logic [0:0] dout_secret;
  } aix_cci_w128_dout_payload_t;
  typedef struct packed {
    logic [31:0] cpl_owner_id;
    logic [15:0] cpl_instance_id;
    logic [31:0] cpl_epoch;
    logic [31:0] cpl_task_id;
    logic [63:0] cpl_request_seq;
    logic [15:0] cpl_context_id;
    logic [31:0] cpl_generation;
    logic [15:0] cpl_status;
    logic [15:0] cpl_detail;
    logic [0:0] cpl_auth_valid;
    logic [0:0] cpl_auth_ok;
    logic [63:0] cpl_consumed;
    logic [63:0] cpl_produced;
    logic [63:0] cpl_delivered;
    logic [0:0] cpl_context_alive;
    logic [0:0] cpl_cleanup_done;
    logic [63:0] cpl_result_ref;
    logic [63:0] cpl_secret_result_bytes;
    logic [63:0] cpl_replay_bytes;
  } aix_cci_w128_cpl_payload_t;
  typedef struct packed {
    logic [31:0] mgmt_req_owner_id;
    logic [15:0] mgmt_req_instance_id;
    logic [31:0] mgmt_req_epoch;
    logic [31:0] mgmt_req_task_id;
    logic [63:0] mgmt_req_request_seq;
    logic [15:0] mgmt_req_context_id;
    logic [31:0] mgmt_req_generation;
    logic [31:0] mgmt_req_request_id;
    logic [7:0] mgmt_req_operation;
    logic [7:0] mgmt_req_scope;
    logic [63:0] mgmt_req_key_ref;
    logic [31:0] mgmt_req_key_epoch;
  } aix_cci_w128_mgmt_req_payload_t;
  typedef struct packed {
    logic [31:0] mgmt_rsp_owner_id;
    logic [15:0] mgmt_rsp_instance_id;
    logic [31:0] mgmt_rsp_epoch;
    logic [31:0] mgmt_rsp_task_id;
    logic [63:0] mgmt_rsp_request_seq;
    logic [15:0] mgmt_rsp_context_id;
    logic [31:0] mgmt_rsp_generation;
    logic [31:0] mgmt_rsp_request_id;
    logic [15:0] mgmt_rsp_status;
    logic [0:0] mgmt_rsp_drain_done;
    logic [0:0] mgmt_rsp_cleanup_done;
    logic [0:0] mgmt_rsp_committed;
  } aix_cci_w128_mgmt_rsp_payload_t;
  typedef struct packed {
    logic [31:0] cap_req_request_id;
    logic [31:0] cap_req_word_index;
  } aix_cci_w128_cap_req_payload_t;
  typedef struct packed {
    logic [31:0] cap_rsp_request_id;
    logic [31:0] cap_rsp_word_index;
    logic [15:0] cap_rsp_status;
    logic [31:0] cap_rsp_data;
    logic [0:0] cap_rsp_last;
  } aix_cci_w128_cap_rsp_payload_t;
  typedef struct packed {
    logic [0:0] cmd_valid;
    logic [31:0] cmd_owner_id;
    logic [15:0] cmd_instance_id;
    logic [31:0] cmd_epoch;
    logic [31:0] cmd_task_id;
    logic [63:0] cmd_request_seq;
    logic [15:0] cmd_context_id;
    logic [31:0] cmd_generation;
    logic [15:0] cmd_operation;
    logic [7:0] cmd_mode;
    logic [7:0] cmd_direction;
    logic [7:0] cmd_action;
    logic [0:0] cmd_inherit;
    logic [31:0] cmd_policy_epoch;
    logic [7:0] cmd_key_count;
    logic [31:0] cmd_key_bits;
    logic [415:0] cmd_key_bindings;
    logic [63:0] cmd_out_len;
    logic [31:0] cmd_tag_len;
    logic [0:0] cmd_message_total_known;
    logic [63:0] cmd_message_total_len;
    logic [0:0] cmd_aad_total_known;
    logic [63:0] cmd_aad_total_len;
    logic [7:0] cmd_segment_count;
    logic [1455:0] cmd_segments;
    logic [0:0] din_valid;
    logic [31:0] din_owner_id;
    logic [15:0] din_instance_id;
    logic [31:0] din_epoch;
    logic [31:0] din_task_id;
    logic [63:0] din_request_seq;
    logic [15:0] din_context_id;
    logic [31:0] din_generation;
    logic [15:0] din_segment_index;
    logic [255:0] din_data;
    logic [31:0] din_keep;
    logic [0:0] din_last;
    logic [0:0] dout_ready;
    logic [0:0] cpl_ready;
    logic [0:0] mgmt_req_valid;
    logic [31:0] mgmt_req_owner_id;
    logic [15:0] mgmt_req_instance_id;
    logic [31:0] mgmt_req_epoch;
    logic [31:0] mgmt_req_task_id;
    logic [63:0] mgmt_req_request_seq;
    logic [15:0] mgmt_req_context_id;
    logic [31:0] mgmt_req_generation;
    logic [31:0] mgmt_req_request_id;
    logic [7:0] mgmt_req_operation;
    logic [7:0] mgmt_req_scope;
    logic [63:0] mgmt_req_key_ref;
    logic [31:0] mgmt_req_key_epoch;
    logic [0:0] mgmt_rsp_ready;
    logic [0:0] cap_req_valid;
    logic [31:0] cap_req_request_id;
    logic [31:0] cap_req_word_index;
    logic [0:0] cap_rsp_ready;
  } aix_cci_w256_req_t;
  typedef struct packed {
    logic [0:0] cmd_ready;
    logic [0:0] din_ready;
    logic [0:0] dout_valid;
    logic [31:0] dout_owner_id;
    logic [15:0] dout_instance_id;
    logic [31:0] dout_epoch;
    logic [31:0] dout_task_id;
    logic [63:0] dout_request_seq;
    logic [15:0] dout_context_id;
    logic [31:0] dout_generation;
    logic [15:0] dout_segment_index;
    logic [7:0] dout_segment_kind;
    logic [255:0] dout_data;
    logic [31:0] dout_keep;
    logic [0:0] dout_last;
    logic [0:0] dout_provisional;
    logic [0:0] dout_secret;
    logic [0:0] cpl_valid;
    logic [31:0] cpl_owner_id;
    logic [15:0] cpl_instance_id;
    logic [31:0] cpl_epoch;
    logic [31:0] cpl_task_id;
    logic [63:0] cpl_request_seq;
    logic [15:0] cpl_context_id;
    logic [31:0] cpl_generation;
    logic [15:0] cpl_status;
    logic [15:0] cpl_detail;
    logic [0:0] cpl_auth_valid;
    logic [0:0] cpl_auth_ok;
    logic [63:0] cpl_consumed;
    logic [63:0] cpl_produced;
    logic [63:0] cpl_delivered;
    logic [0:0] cpl_context_alive;
    logic [0:0] cpl_cleanup_done;
    logic [63:0] cpl_result_ref;
    logic [63:0] cpl_secret_result_bytes;
    logic [63:0] cpl_replay_bytes;
    logic [0:0] mgmt_req_ready;
    logic [0:0] mgmt_rsp_valid;
    logic [31:0] mgmt_rsp_owner_id;
    logic [15:0] mgmt_rsp_instance_id;
    logic [31:0] mgmt_rsp_epoch;
    logic [31:0] mgmt_rsp_task_id;
    logic [63:0] mgmt_rsp_request_seq;
    logic [15:0] mgmt_rsp_context_id;
    logic [31:0] mgmt_rsp_generation;
    logic [31:0] mgmt_rsp_request_id;
    logic [15:0] mgmt_rsp_status;
    logic [0:0] mgmt_rsp_drain_done;
    logic [0:0] mgmt_rsp_cleanup_done;
    logic [0:0] mgmt_rsp_committed;
    logic [0:0] cap_req_ready;
    logic [0:0] cap_rsp_valid;
    logic [31:0] cap_rsp_request_id;
    logic [31:0] cap_rsp_word_index;
    logic [15:0] cap_rsp_status;
    logic [31:0] cap_rsp_data;
    logic [0:0] cap_rsp_last;
  } aix_cci_w256_rsp_t;
  typedef struct packed {
    logic [31:0] cmd_owner_id;
    logic [15:0] cmd_instance_id;
    logic [31:0] cmd_epoch;
    logic [31:0] cmd_task_id;
    logic [63:0] cmd_request_seq;
    logic [15:0] cmd_context_id;
    logic [31:0] cmd_generation;
    logic [15:0] cmd_operation;
    logic [7:0] cmd_mode;
    logic [7:0] cmd_direction;
    logic [7:0] cmd_action;
    logic [0:0] cmd_inherit;
    logic [31:0] cmd_policy_epoch;
    logic [7:0] cmd_key_count;
    logic [31:0] cmd_key_bits;
    logic [415:0] cmd_key_bindings;
    logic [63:0] cmd_out_len;
    logic [31:0] cmd_tag_len;
    logic [0:0] cmd_message_total_known;
    logic [63:0] cmd_message_total_len;
    logic [0:0] cmd_aad_total_known;
    logic [63:0] cmd_aad_total_len;
    logic [7:0] cmd_segment_count;
    logic [1455:0] cmd_segments;
  } aix_cci_w256_cmd_payload_t;
  typedef struct packed {
    logic [31:0] din_owner_id;
    logic [15:0] din_instance_id;
    logic [31:0] din_epoch;
    logic [31:0] din_task_id;
    logic [63:0] din_request_seq;
    logic [15:0] din_context_id;
    logic [31:0] din_generation;
    logic [15:0] din_segment_index;
    logic [255:0] din_data;
    logic [31:0] din_keep;
    logic [0:0] din_last;
  } aix_cci_w256_din_payload_t;
  typedef struct packed {
    logic [31:0] dout_owner_id;
    logic [15:0] dout_instance_id;
    logic [31:0] dout_epoch;
    logic [31:0] dout_task_id;
    logic [63:0] dout_request_seq;
    logic [15:0] dout_context_id;
    logic [31:0] dout_generation;
    logic [15:0] dout_segment_index;
    logic [7:0] dout_segment_kind;
    logic [255:0] dout_data;
    logic [31:0] dout_keep;
    logic [0:0] dout_last;
    logic [0:0] dout_provisional;
    logic [0:0] dout_secret;
  } aix_cci_w256_dout_payload_t;
  typedef struct packed {
    logic [31:0] cpl_owner_id;
    logic [15:0] cpl_instance_id;
    logic [31:0] cpl_epoch;
    logic [31:0] cpl_task_id;
    logic [63:0] cpl_request_seq;
    logic [15:0] cpl_context_id;
    logic [31:0] cpl_generation;
    logic [15:0] cpl_status;
    logic [15:0] cpl_detail;
    logic [0:0] cpl_auth_valid;
    logic [0:0] cpl_auth_ok;
    logic [63:0] cpl_consumed;
    logic [63:0] cpl_produced;
    logic [63:0] cpl_delivered;
    logic [0:0] cpl_context_alive;
    logic [0:0] cpl_cleanup_done;
    logic [63:0] cpl_result_ref;
    logic [63:0] cpl_secret_result_bytes;
    logic [63:0] cpl_replay_bytes;
  } aix_cci_w256_cpl_payload_t;
  typedef struct packed {
    logic [31:0] mgmt_req_owner_id;
    logic [15:0] mgmt_req_instance_id;
    logic [31:0] mgmt_req_epoch;
    logic [31:0] mgmt_req_task_id;
    logic [63:0] mgmt_req_request_seq;
    logic [15:0] mgmt_req_context_id;
    logic [31:0] mgmt_req_generation;
    logic [31:0] mgmt_req_request_id;
    logic [7:0] mgmt_req_operation;
    logic [7:0] mgmt_req_scope;
    logic [63:0] mgmt_req_key_ref;
    logic [31:0] mgmt_req_key_epoch;
  } aix_cci_w256_mgmt_req_payload_t;
  typedef struct packed {
    logic [31:0] mgmt_rsp_owner_id;
    logic [15:0] mgmt_rsp_instance_id;
    logic [31:0] mgmt_rsp_epoch;
    logic [31:0] mgmt_rsp_task_id;
    logic [63:0] mgmt_rsp_request_seq;
    logic [15:0] mgmt_rsp_context_id;
    logic [31:0] mgmt_rsp_generation;
    logic [31:0] mgmt_rsp_request_id;
    logic [15:0] mgmt_rsp_status;
    logic [0:0] mgmt_rsp_drain_done;
    logic [0:0] mgmt_rsp_cleanup_done;
    logic [0:0] mgmt_rsp_committed;
  } aix_cci_w256_mgmt_rsp_payload_t;
  typedef struct packed {
    logic [31:0] cap_req_request_id;
    logic [31:0] cap_req_word_index;
  } aix_cci_w256_cap_req_payload_t;
  typedef struct packed {
    logic [31:0] cap_rsp_request_id;
    logic [31:0] cap_rsp_word_index;
    logic [15:0] cap_rsp_status;
    logic [31:0] cap_rsp_data;
    logic [0:0] cap_rsp_last;
  } aix_cci_w256_cap_rsp_payload_t;
  typedef struct packed {
    logic [0:0] cmd_valid;
    logic [31:0] cmd_owner_id;
    logic [15:0] cmd_instance_id;
    logic [31:0] cmd_epoch;
    logic [31:0] cmd_task_id;
    logic [63:0] cmd_request_seq;
    logic [15:0] cmd_context_id;
    logic [31:0] cmd_generation;
    logic [15:0] cmd_operation;
    logic [7:0] cmd_mode;
    logic [7:0] cmd_direction;
    logic [7:0] cmd_action;
    logic [0:0] cmd_inherit;
    logic [31:0] cmd_policy_epoch;
    logic [7:0] cmd_key_count;
    logic [31:0] cmd_key_bits;
    logic [415:0] cmd_key_bindings;
    logic [63:0] cmd_out_len;
    logic [31:0] cmd_tag_len;
    logic [0:0] cmd_message_total_known;
    logic [63:0] cmd_message_total_len;
    logic [0:0] cmd_aad_total_known;
    logic [63:0] cmd_aad_total_len;
    logic [7:0] cmd_segment_count;
    logic [1455:0] cmd_segments;
    logic [0:0] din_valid;
    logic [31:0] din_owner_id;
    logic [15:0] din_instance_id;
    logic [31:0] din_epoch;
    logic [31:0] din_task_id;
    logic [63:0] din_request_seq;
    logic [15:0] din_context_id;
    logic [31:0] din_generation;
    logic [15:0] din_segment_index;
    logic [511:0] din_data;
    logic [63:0] din_keep;
    logic [0:0] din_last;
    logic [0:0] dout_ready;
    logic [0:0] cpl_ready;
    logic [0:0] mgmt_req_valid;
    logic [31:0] mgmt_req_owner_id;
    logic [15:0] mgmt_req_instance_id;
    logic [31:0] mgmt_req_epoch;
    logic [31:0] mgmt_req_task_id;
    logic [63:0] mgmt_req_request_seq;
    logic [15:0] mgmt_req_context_id;
    logic [31:0] mgmt_req_generation;
    logic [31:0] mgmt_req_request_id;
    logic [7:0] mgmt_req_operation;
    logic [7:0] mgmt_req_scope;
    logic [63:0] mgmt_req_key_ref;
    logic [31:0] mgmt_req_key_epoch;
    logic [0:0] mgmt_rsp_ready;
    logic [0:0] cap_req_valid;
    logic [31:0] cap_req_request_id;
    logic [31:0] cap_req_word_index;
    logic [0:0] cap_rsp_ready;
  } aix_cci_w512_req_t;
  typedef struct packed {
    logic [0:0] cmd_ready;
    logic [0:0] din_ready;
    logic [0:0] dout_valid;
    logic [31:0] dout_owner_id;
    logic [15:0] dout_instance_id;
    logic [31:0] dout_epoch;
    logic [31:0] dout_task_id;
    logic [63:0] dout_request_seq;
    logic [15:0] dout_context_id;
    logic [31:0] dout_generation;
    logic [15:0] dout_segment_index;
    logic [7:0] dout_segment_kind;
    logic [511:0] dout_data;
    logic [63:0] dout_keep;
    logic [0:0] dout_last;
    logic [0:0] dout_provisional;
    logic [0:0] dout_secret;
    logic [0:0] cpl_valid;
    logic [31:0] cpl_owner_id;
    logic [15:0] cpl_instance_id;
    logic [31:0] cpl_epoch;
    logic [31:0] cpl_task_id;
    logic [63:0] cpl_request_seq;
    logic [15:0] cpl_context_id;
    logic [31:0] cpl_generation;
    logic [15:0] cpl_status;
    logic [15:0] cpl_detail;
    logic [0:0] cpl_auth_valid;
    logic [0:0] cpl_auth_ok;
    logic [63:0] cpl_consumed;
    logic [63:0] cpl_produced;
    logic [63:0] cpl_delivered;
    logic [0:0] cpl_context_alive;
    logic [0:0] cpl_cleanup_done;
    logic [63:0] cpl_result_ref;
    logic [63:0] cpl_secret_result_bytes;
    logic [63:0] cpl_replay_bytes;
    logic [0:0] mgmt_req_ready;
    logic [0:0] mgmt_rsp_valid;
    logic [31:0] mgmt_rsp_owner_id;
    logic [15:0] mgmt_rsp_instance_id;
    logic [31:0] mgmt_rsp_epoch;
    logic [31:0] mgmt_rsp_task_id;
    logic [63:0] mgmt_rsp_request_seq;
    logic [15:0] mgmt_rsp_context_id;
    logic [31:0] mgmt_rsp_generation;
    logic [31:0] mgmt_rsp_request_id;
    logic [15:0] mgmt_rsp_status;
    logic [0:0] mgmt_rsp_drain_done;
    logic [0:0] mgmt_rsp_cleanup_done;
    logic [0:0] mgmt_rsp_committed;
    logic [0:0] cap_req_ready;
    logic [0:0] cap_rsp_valid;
    logic [31:0] cap_rsp_request_id;
    logic [31:0] cap_rsp_word_index;
    logic [15:0] cap_rsp_status;
    logic [31:0] cap_rsp_data;
    logic [0:0] cap_rsp_last;
  } aix_cci_w512_rsp_t;
  typedef struct packed {
    logic [31:0] cmd_owner_id;
    logic [15:0] cmd_instance_id;
    logic [31:0] cmd_epoch;
    logic [31:0] cmd_task_id;
    logic [63:0] cmd_request_seq;
    logic [15:0] cmd_context_id;
    logic [31:0] cmd_generation;
    logic [15:0] cmd_operation;
    logic [7:0] cmd_mode;
    logic [7:0] cmd_direction;
    logic [7:0] cmd_action;
    logic [0:0] cmd_inherit;
    logic [31:0] cmd_policy_epoch;
    logic [7:0] cmd_key_count;
    logic [31:0] cmd_key_bits;
    logic [415:0] cmd_key_bindings;
    logic [63:0] cmd_out_len;
    logic [31:0] cmd_tag_len;
    logic [0:0] cmd_message_total_known;
    logic [63:0] cmd_message_total_len;
    logic [0:0] cmd_aad_total_known;
    logic [63:0] cmd_aad_total_len;
    logic [7:0] cmd_segment_count;
    logic [1455:0] cmd_segments;
  } aix_cci_w512_cmd_payload_t;
  typedef struct packed {
    logic [31:0] din_owner_id;
    logic [15:0] din_instance_id;
    logic [31:0] din_epoch;
    logic [31:0] din_task_id;
    logic [63:0] din_request_seq;
    logic [15:0] din_context_id;
    logic [31:0] din_generation;
    logic [15:0] din_segment_index;
    logic [511:0] din_data;
    logic [63:0] din_keep;
    logic [0:0] din_last;
  } aix_cci_w512_din_payload_t;
  typedef struct packed {
    logic [31:0] dout_owner_id;
    logic [15:0] dout_instance_id;
    logic [31:0] dout_epoch;
    logic [31:0] dout_task_id;
    logic [63:0] dout_request_seq;
    logic [15:0] dout_context_id;
    logic [31:0] dout_generation;
    logic [15:0] dout_segment_index;
    logic [7:0] dout_segment_kind;
    logic [511:0] dout_data;
    logic [63:0] dout_keep;
    logic [0:0] dout_last;
    logic [0:0] dout_provisional;
    logic [0:0] dout_secret;
  } aix_cci_w512_dout_payload_t;
  typedef struct packed {
    logic [31:0] cpl_owner_id;
    logic [15:0] cpl_instance_id;
    logic [31:0] cpl_epoch;
    logic [31:0] cpl_task_id;
    logic [63:0] cpl_request_seq;
    logic [15:0] cpl_context_id;
    logic [31:0] cpl_generation;
    logic [15:0] cpl_status;
    logic [15:0] cpl_detail;
    logic [0:0] cpl_auth_valid;
    logic [0:0] cpl_auth_ok;
    logic [63:0] cpl_consumed;
    logic [63:0] cpl_produced;
    logic [63:0] cpl_delivered;
    logic [0:0] cpl_context_alive;
    logic [0:0] cpl_cleanup_done;
    logic [63:0] cpl_result_ref;
    logic [63:0] cpl_secret_result_bytes;
    logic [63:0] cpl_replay_bytes;
  } aix_cci_w512_cpl_payload_t;
  typedef struct packed {
    logic [31:0] mgmt_req_owner_id;
    logic [15:0] mgmt_req_instance_id;
    logic [31:0] mgmt_req_epoch;
    logic [31:0] mgmt_req_task_id;
    logic [63:0] mgmt_req_request_seq;
    logic [15:0] mgmt_req_context_id;
    logic [31:0] mgmt_req_generation;
    logic [31:0] mgmt_req_request_id;
    logic [7:0] mgmt_req_operation;
    logic [7:0] mgmt_req_scope;
    logic [63:0] mgmt_req_key_ref;
    logic [31:0] mgmt_req_key_epoch;
  } aix_cci_w512_mgmt_req_payload_t;
  typedef struct packed {
    logic [31:0] mgmt_rsp_owner_id;
    logic [15:0] mgmt_rsp_instance_id;
    logic [31:0] mgmt_rsp_epoch;
    logic [31:0] mgmt_rsp_task_id;
    logic [63:0] mgmt_rsp_request_seq;
    logic [15:0] mgmt_rsp_context_id;
    logic [31:0] mgmt_rsp_generation;
    logic [31:0] mgmt_rsp_request_id;
    logic [15:0] mgmt_rsp_status;
    logic [0:0] mgmt_rsp_drain_done;
    logic [0:0] mgmt_rsp_cleanup_done;
    logic [0:0] mgmt_rsp_committed;
  } aix_cci_w512_mgmt_rsp_payload_t;
  typedef struct packed {
    logic [31:0] cap_req_request_id;
    logic [31:0] cap_req_word_index;
  } aix_cci_w512_cap_req_payload_t;
  typedef struct packed {
    logic [31:0] cap_rsp_request_id;
    logic [31:0] cap_rsp_word_index;
    logic [15:0] cap_rsp_status;
    logic [31:0] cap_rsp_data;
    logic [0:0] cap_rsp_last;
  } aix_cci_w512_cap_rsp_payload_t;
  typedef aix_cci_w128_req_t aix_cci_req_t;
  typedef aix_cci_w128_rsp_t aix_cci_rsp_t;
  typedef aix_cci_w128_cmd_payload_t aix_cci_cmd_payload_t;
  typedef aix_cci_w128_din_payload_t aix_cci_din_payload_t;
  typedef aix_cci_w128_dout_payload_t aix_cci_dout_payload_t;
  typedef aix_cci_w128_cpl_payload_t aix_cci_cpl_payload_t;
  typedef aix_cci_w128_mgmt_req_payload_t aix_cci_mgmt_req_payload_t;
  typedef aix_cci_w128_mgmt_rsp_payload_t aix_cci_mgmt_rsp_payload_t;
  typedef aix_cci_w128_cap_req_payload_t aix_cci_cap_req_payload_t;
  typedef aix_cci_w128_cap_rsp_payload_t aix_cci_cap_rsp_payload_t;
endpackage : aix_cci_pkg
