// SPDX-License-Identifier: Apache-2.0
// Generated from the interface contract. Do not edit.
module aix_crypto_mac_call_flat_wrapper #(parameter int unsigned DATA_W = 128)(
  aix_crypto_mac_call_if.caller link,
  input logic [(1)-1:0] req_valid_i,
  output logic [(1)-1:0] req_ready_o,
  input logic [(32)-1:0] req_owner_id_i,
  input logic [(16)-1:0] req_instance_id_i,
  input logic [(32)-1:0] req_epoch_i,
  input logic [(32)-1:0] req_task_id_i,
  input logic [(64)-1:0] req_request_seq_i,
  input logic [(16)-1:0] req_context_id_i,
  input logic [(32)-1:0] req_generation_i,
  input logic [(64)-1:0] req_invocation_id_i,
  input logic [(8)-1:0] req_action_i,
  input logic [(64)-1:0] req_lease_token_i,
  input logic [(3)-1:0] req_algorithm_i,
  input logic [(16)-1:0] req_operation_i,
  input logic [(8)-1:0] req_template_i,
  input logic [(32)-1:0] req_policy_epoch_i,
  input logic [(8)-1:0] req_key_source_i,
  input logic [(64)-1:0] req_key_ref_i,
  input logic [(32)-1:0] req_key_epoch_i,
  input logic [(32)-1:0] req_key_length_i,
  input logic [(32)-1:0] req_tag_length_i,
  input logic [(8)-1:0] req_part_count_i,
  input logic [(696)-1:0] req_message_parts_i,
  input logic [(8)-1:0] req_iteration_i,
  input logic [(64)-1:0] req_result_sink_ref_i,
  output logic [(1)-1:0] rsp_valid_o,
  input logic [(1)-1:0] rsp_ready_i,
  output logic [(32)-1:0] rsp_owner_id_o,
  output logic [(16)-1:0] rsp_instance_id_o,
  output logic [(32)-1:0] rsp_epoch_o,
  output logic [(32)-1:0] rsp_task_id_o,
  output logic [(64)-1:0] rsp_request_seq_o,
  output logic [(16)-1:0] rsp_context_id_o,
  output logic [(32)-1:0] rsp_generation_o,
  output logic [(64)-1:0] rsp_invocation_id_o,
  output logic [(8)-1:0] rsp_action_o,
  output logic [(64)-1:0] rsp_lease_token_o,
  output logic [(16)-1:0] rsp_status_o,
  output logic [(1)-1:0] rsp_auth_valid_o,
  output logic [(1)-1:0] rsp_auth_ok_o,
  output logic [(64)-1:0] rsp_result_ref_o,
  output logic [(32)-1:0] rsp_result_epoch_o,
  output logic [(64)-1:0] rsp_result_bytes_o,
  output logic [(64)-1:0] rsp_consumed_public_o,
  output logic [(64)-1:0] rsp_consumed_secret_o,
  output logic [(64)-1:0] rsp_produced_o,
  output logic [(1)-1:0] rsp_cleanup_done_o,
  output logic [(8)-1:0] rsp_object_state_o,
  input logic [(1)-1:0] public_data_valid_i,
  output logic [(1)-1:0] public_data_ready_o,
  input logic [(32)-1:0] public_data_owner_id_i,
  input logic [(16)-1:0] public_data_instance_id_i,
  input logic [(32)-1:0] public_data_epoch_i,
  input logic [(32)-1:0] public_data_task_id_i,
  input logic [(64)-1:0] public_data_request_seq_i,
  input logic [(16)-1:0] public_data_context_id_i,
  input logic [(32)-1:0] public_data_generation_i,
  input logic [(64)-1:0] public_data_invocation_id_i,
  input logic [(64)-1:0] public_data_lease_token_i,
  input logic [(8)-1:0] public_data_source_i,
  input logic [(64)-1:0] public_data_offset_i,
  input logic [(DATA_W)-1:0] public_data_data_i,
  input logic [(DATA_W/8)-1:0] public_data_keep_i,
  input logic [(1)-1:0] public_data_last_i,
  input logic [(1)-1:0] control_req_valid_i,
  output logic [(1)-1:0] control_req_ready_o,
  input logic [(32)-1:0] control_req_owner_id_i,
  input logic [(16)-1:0] control_req_instance_id_i,
  input logic [(32)-1:0] control_req_epoch_i,
  input logic [(32)-1:0] control_req_task_id_i,
  input logic [(64)-1:0] control_req_request_seq_i,
  input logic [(16)-1:0] control_req_context_id_i,
  input logic [(32)-1:0] control_req_generation_i,
  input logic [(64)-1:0] control_req_invocation_id_i,
  input logic [(64)-1:0] control_req_lease_token_i,
  input logic [(8)-1:0] control_req_action_i,
  input logic [(64)-1:0] control_req_control_id_i,
  output logic [(1)-1:0] control_rsp_valid_o,
  input logic [(1)-1:0] control_rsp_ready_i,
  output logic [(32)-1:0] control_rsp_owner_id_o,
  output logic [(16)-1:0] control_rsp_instance_id_o,
  output logic [(32)-1:0] control_rsp_epoch_o,
  output logic [(32)-1:0] control_rsp_task_id_o,
  output logic [(64)-1:0] control_rsp_request_seq_o,
  output logic [(16)-1:0] control_rsp_context_id_o,
  output logic [(32)-1:0] control_rsp_generation_o,
  output logic [(64)-1:0] control_rsp_invocation_id_o,
  output logic [(64)-1:0] control_rsp_lease_token_o,
  output logic [(64)-1:0] control_rsp_control_id_o,
  output logic [(16)-1:0] control_rsp_status_o,
  output logic [(1)-1:0] control_rsp_committed_o,
  output logic [(1)-1:0] control_rsp_cleanup_done_o,
  output logic [(8)-1:0] control_rsp_object_state_o
);
  assign link.req_valid = req_valid_i;
  assign req_ready_o = link.req_ready;
  assign link.req_owner_id = req_owner_id_i;
  assign link.req_instance_id = req_instance_id_i;
  assign link.req_epoch = req_epoch_i;
  assign link.req_task_id = req_task_id_i;
  assign link.req_request_seq = req_request_seq_i;
  assign link.req_context_id = req_context_id_i;
  assign link.req_generation = req_generation_i;
  assign link.req_invocation_id = req_invocation_id_i;
  assign link.req_action = req_action_i;
  assign link.req_lease_token = req_lease_token_i;
  assign link.req_algorithm = req_algorithm_i;
  assign link.req_operation = req_operation_i;
  assign link.req_template = req_template_i;
  assign link.req_policy_epoch = req_policy_epoch_i;
  assign link.req_key_source = req_key_source_i;
  assign link.req_key_ref = req_key_ref_i;
  assign link.req_key_epoch = req_key_epoch_i;
  assign link.req_key_length = req_key_length_i;
  assign link.req_tag_length = req_tag_length_i;
  assign link.req_part_count = req_part_count_i;
  assign link.req_message_parts = req_message_parts_i;
  assign link.req_iteration = req_iteration_i;
  assign link.req_result_sink_ref = req_result_sink_ref_i;
  assign rsp_valid_o = link.rsp_valid;
  assign link.rsp_ready = rsp_ready_i;
  assign rsp_owner_id_o = link.rsp_owner_id;
  assign rsp_instance_id_o = link.rsp_instance_id;
  assign rsp_epoch_o = link.rsp_epoch;
  assign rsp_task_id_o = link.rsp_task_id;
  assign rsp_request_seq_o = link.rsp_request_seq;
  assign rsp_context_id_o = link.rsp_context_id;
  assign rsp_generation_o = link.rsp_generation;
  assign rsp_invocation_id_o = link.rsp_invocation_id;
  assign rsp_action_o = link.rsp_action;
  assign rsp_lease_token_o = link.rsp_lease_token;
  assign rsp_status_o = link.rsp_status;
  assign rsp_auth_valid_o = link.rsp_auth_valid;
  assign rsp_auth_ok_o = link.rsp_auth_ok;
  assign rsp_result_ref_o = link.rsp_result_ref;
  assign rsp_result_epoch_o = link.rsp_result_epoch;
  assign rsp_result_bytes_o = link.rsp_result_bytes;
  assign rsp_consumed_public_o = link.rsp_consumed_public;
  assign rsp_consumed_secret_o = link.rsp_consumed_secret;
  assign rsp_produced_o = link.rsp_produced;
  assign rsp_cleanup_done_o = link.rsp_cleanup_done;
  assign rsp_object_state_o = link.rsp_object_state;
  assign link.public_data_valid = public_data_valid_i;
  assign public_data_ready_o = link.public_data_ready;
  assign link.public_data_owner_id = public_data_owner_id_i;
  assign link.public_data_instance_id = public_data_instance_id_i;
  assign link.public_data_epoch = public_data_epoch_i;
  assign link.public_data_task_id = public_data_task_id_i;
  assign link.public_data_request_seq = public_data_request_seq_i;
  assign link.public_data_context_id = public_data_context_id_i;
  assign link.public_data_generation = public_data_generation_i;
  assign link.public_data_invocation_id = public_data_invocation_id_i;
  assign link.public_data_lease_token = public_data_lease_token_i;
  assign link.public_data_source = public_data_source_i;
  assign link.public_data_offset = public_data_offset_i;
  assign link.public_data_data = public_data_data_i;
  assign link.public_data_keep = public_data_keep_i;
  assign link.public_data_last = public_data_last_i;
  assign link.control_req_valid = control_req_valid_i;
  assign control_req_ready_o = link.control_req_ready;
  assign link.control_req_owner_id = control_req_owner_id_i;
  assign link.control_req_instance_id = control_req_instance_id_i;
  assign link.control_req_epoch = control_req_epoch_i;
  assign link.control_req_task_id = control_req_task_id_i;
  assign link.control_req_request_seq = control_req_request_seq_i;
  assign link.control_req_context_id = control_req_context_id_i;
  assign link.control_req_generation = control_req_generation_i;
  assign link.control_req_invocation_id = control_req_invocation_id_i;
  assign link.control_req_lease_token = control_req_lease_token_i;
  assign link.control_req_action = control_req_action_i;
  assign link.control_req_control_id = control_req_control_id_i;
  assign control_rsp_valid_o = link.control_rsp_valid;
  assign link.control_rsp_ready = control_rsp_ready_i;
  assign control_rsp_owner_id_o = link.control_rsp_owner_id;
  assign control_rsp_instance_id_o = link.control_rsp_instance_id;
  assign control_rsp_epoch_o = link.control_rsp_epoch;
  assign control_rsp_task_id_o = link.control_rsp_task_id;
  assign control_rsp_request_seq_o = link.control_rsp_request_seq;
  assign control_rsp_context_id_o = link.control_rsp_context_id;
  assign control_rsp_generation_o = link.control_rsp_generation;
  assign control_rsp_invocation_id_o = link.control_rsp_invocation_id;
  assign control_rsp_lease_token_o = link.control_rsp_lease_token;
  assign control_rsp_control_id_o = link.control_rsp_control_id;
  assign control_rsp_status_o = link.control_rsp_status;
  assign control_rsp_committed_o = link.control_rsp_committed;
  assign control_rsp_cleanup_done_o = link.control_rsp_cleanup_done;
  assign control_rsp_object_state_o = link.control_rsp_object_state;
endmodule
