// SPDX-License-Identifier: Apache-2.0
// Generated from the interface contract. Do not edit.

package aix_crypto_entropy_pkg;
  localparam int unsigned DATA_W = 128;
  typedef struct packed {
    logic [0:0] req_valid;
    logic [31:0] req_owner_id;
    logic [15:0] req_instance_id;
    logic [31:0] req_epoch;
    logic [31:0] req_task_id;
    logic [63:0] req_request_seq;
    logic [15:0] req_context_id;
    logic [31:0] req_generation;
    logic [63:0] req_request_id;
    logic [31:0] req_length;
    logic [0:0] rsp_ready;
  } aix_crypto_entropy_w32_req_t;
  typedef struct packed {
    logic [0:0] req_ready;
    logic [0:0] rsp_valid;
    logic [31:0] rsp_owner_id;
    logic [15:0] rsp_instance_id;
    logic [31:0] rsp_epoch;
    logic [31:0] rsp_task_id;
    logic [63:0] rsp_request_seq;
    logic [15:0] rsp_context_id;
    logic [31:0] rsp_generation;
    logic [63:0] rsp_request_id;
    logic [15:0] rsp_status;
    logic [31:0] rsp_data;
    logic [3:0] rsp_keep;
    logic [0:0] rsp_last;
    logic [0:0] rsp_health_ok;
  } aix_crypto_entropy_w32_rsp_t;
  typedef struct packed {
    logic [31:0] req_owner_id;
    logic [15:0] req_instance_id;
    logic [31:0] req_epoch;
    logic [31:0] req_task_id;
    logic [63:0] req_request_seq;
    logic [15:0] req_context_id;
    logic [31:0] req_generation;
    logic [63:0] req_request_id;
    logic [31:0] req_length;
  } aix_crypto_entropy_w32_req_payload_t;
  typedef struct packed {
    logic [31:0] rsp_owner_id;
    logic [15:0] rsp_instance_id;
    logic [31:0] rsp_epoch;
    logic [31:0] rsp_task_id;
    logic [63:0] rsp_request_seq;
    logic [15:0] rsp_context_id;
    logic [31:0] rsp_generation;
    logic [63:0] rsp_request_id;
    logic [15:0] rsp_status;
    logic [31:0] rsp_data;
    logic [3:0] rsp_keep;
    logic [0:0] rsp_last;
    logic [0:0] rsp_health_ok;
  } aix_crypto_entropy_w32_rsp_payload_t;
  typedef struct packed {
    logic [0:0] req_valid;
    logic [31:0] req_owner_id;
    logic [15:0] req_instance_id;
    logic [31:0] req_epoch;
    logic [31:0] req_task_id;
    logic [63:0] req_request_seq;
    logic [15:0] req_context_id;
    logic [31:0] req_generation;
    logic [63:0] req_request_id;
    logic [31:0] req_length;
    logic [0:0] rsp_ready;
  } aix_crypto_entropy_w64_req_t;
  typedef struct packed {
    logic [0:0] req_ready;
    logic [0:0] rsp_valid;
    logic [31:0] rsp_owner_id;
    logic [15:0] rsp_instance_id;
    logic [31:0] rsp_epoch;
    logic [31:0] rsp_task_id;
    logic [63:0] rsp_request_seq;
    logic [15:0] rsp_context_id;
    logic [31:0] rsp_generation;
    logic [63:0] rsp_request_id;
    logic [15:0] rsp_status;
    logic [63:0] rsp_data;
    logic [7:0] rsp_keep;
    logic [0:0] rsp_last;
    logic [0:0] rsp_health_ok;
  } aix_crypto_entropy_w64_rsp_t;
  typedef struct packed {
    logic [31:0] req_owner_id;
    logic [15:0] req_instance_id;
    logic [31:0] req_epoch;
    logic [31:0] req_task_id;
    logic [63:0] req_request_seq;
    logic [15:0] req_context_id;
    logic [31:0] req_generation;
    logic [63:0] req_request_id;
    logic [31:0] req_length;
  } aix_crypto_entropy_w64_req_payload_t;
  typedef struct packed {
    logic [31:0] rsp_owner_id;
    logic [15:0] rsp_instance_id;
    logic [31:0] rsp_epoch;
    logic [31:0] rsp_task_id;
    logic [63:0] rsp_request_seq;
    logic [15:0] rsp_context_id;
    logic [31:0] rsp_generation;
    logic [63:0] rsp_request_id;
    logic [15:0] rsp_status;
    logic [63:0] rsp_data;
    logic [7:0] rsp_keep;
    logic [0:0] rsp_last;
    logic [0:0] rsp_health_ok;
  } aix_crypto_entropy_w64_rsp_payload_t;
  typedef struct packed {
    logic [0:0] req_valid;
    logic [31:0] req_owner_id;
    logic [15:0] req_instance_id;
    logic [31:0] req_epoch;
    logic [31:0] req_task_id;
    logic [63:0] req_request_seq;
    logic [15:0] req_context_id;
    logic [31:0] req_generation;
    logic [63:0] req_request_id;
    logic [31:0] req_length;
    logic [0:0] rsp_ready;
  } aix_crypto_entropy_w128_req_t;
  typedef struct packed {
    logic [0:0] req_ready;
    logic [0:0] rsp_valid;
    logic [31:0] rsp_owner_id;
    logic [15:0] rsp_instance_id;
    logic [31:0] rsp_epoch;
    logic [31:0] rsp_task_id;
    logic [63:0] rsp_request_seq;
    logic [15:0] rsp_context_id;
    logic [31:0] rsp_generation;
    logic [63:0] rsp_request_id;
    logic [15:0] rsp_status;
    logic [127:0] rsp_data;
    logic [15:0] rsp_keep;
    logic [0:0] rsp_last;
    logic [0:0] rsp_health_ok;
  } aix_crypto_entropy_w128_rsp_t;
  typedef struct packed {
    logic [31:0] req_owner_id;
    logic [15:0] req_instance_id;
    logic [31:0] req_epoch;
    logic [31:0] req_task_id;
    logic [63:0] req_request_seq;
    logic [15:0] req_context_id;
    logic [31:0] req_generation;
    logic [63:0] req_request_id;
    logic [31:0] req_length;
  } aix_crypto_entropy_w128_req_payload_t;
  typedef struct packed {
    logic [31:0] rsp_owner_id;
    logic [15:0] rsp_instance_id;
    logic [31:0] rsp_epoch;
    logic [31:0] rsp_task_id;
    logic [63:0] rsp_request_seq;
    logic [15:0] rsp_context_id;
    logic [31:0] rsp_generation;
    logic [63:0] rsp_request_id;
    logic [15:0] rsp_status;
    logic [127:0] rsp_data;
    logic [15:0] rsp_keep;
    logic [0:0] rsp_last;
    logic [0:0] rsp_health_ok;
  } aix_crypto_entropy_w128_rsp_payload_t;
  typedef struct packed {
    logic [0:0] req_valid;
    logic [31:0] req_owner_id;
    logic [15:0] req_instance_id;
    logic [31:0] req_epoch;
    logic [31:0] req_task_id;
    logic [63:0] req_request_seq;
    logic [15:0] req_context_id;
    logic [31:0] req_generation;
    logic [63:0] req_request_id;
    logic [31:0] req_length;
    logic [0:0] rsp_ready;
  } aix_crypto_entropy_w256_req_t;
  typedef struct packed {
    logic [0:0] req_ready;
    logic [0:0] rsp_valid;
    logic [31:0] rsp_owner_id;
    logic [15:0] rsp_instance_id;
    logic [31:0] rsp_epoch;
    logic [31:0] rsp_task_id;
    logic [63:0] rsp_request_seq;
    logic [15:0] rsp_context_id;
    logic [31:0] rsp_generation;
    logic [63:0] rsp_request_id;
    logic [15:0] rsp_status;
    logic [255:0] rsp_data;
    logic [31:0] rsp_keep;
    logic [0:0] rsp_last;
    logic [0:0] rsp_health_ok;
  } aix_crypto_entropy_w256_rsp_t;
  typedef struct packed {
    logic [31:0] req_owner_id;
    logic [15:0] req_instance_id;
    logic [31:0] req_epoch;
    logic [31:0] req_task_id;
    logic [63:0] req_request_seq;
    logic [15:0] req_context_id;
    logic [31:0] req_generation;
    logic [63:0] req_request_id;
    logic [31:0] req_length;
  } aix_crypto_entropy_w256_req_payload_t;
  typedef struct packed {
    logic [31:0] rsp_owner_id;
    logic [15:0] rsp_instance_id;
    logic [31:0] rsp_epoch;
    logic [31:0] rsp_task_id;
    logic [63:0] rsp_request_seq;
    logic [15:0] rsp_context_id;
    logic [31:0] rsp_generation;
    logic [63:0] rsp_request_id;
    logic [15:0] rsp_status;
    logic [255:0] rsp_data;
    logic [31:0] rsp_keep;
    logic [0:0] rsp_last;
    logic [0:0] rsp_health_ok;
  } aix_crypto_entropy_w256_rsp_payload_t;
  typedef struct packed {
    logic [0:0] req_valid;
    logic [31:0] req_owner_id;
    logic [15:0] req_instance_id;
    logic [31:0] req_epoch;
    logic [31:0] req_task_id;
    logic [63:0] req_request_seq;
    logic [15:0] req_context_id;
    logic [31:0] req_generation;
    logic [63:0] req_request_id;
    logic [31:0] req_length;
    logic [0:0] rsp_ready;
  } aix_crypto_entropy_w512_req_t;
  typedef struct packed {
    logic [0:0] req_ready;
    logic [0:0] rsp_valid;
    logic [31:0] rsp_owner_id;
    logic [15:0] rsp_instance_id;
    logic [31:0] rsp_epoch;
    logic [31:0] rsp_task_id;
    logic [63:0] rsp_request_seq;
    logic [15:0] rsp_context_id;
    logic [31:0] rsp_generation;
    logic [63:0] rsp_request_id;
    logic [15:0] rsp_status;
    logic [511:0] rsp_data;
    logic [63:0] rsp_keep;
    logic [0:0] rsp_last;
    logic [0:0] rsp_health_ok;
  } aix_crypto_entropy_w512_rsp_t;
  typedef struct packed {
    logic [31:0] req_owner_id;
    logic [15:0] req_instance_id;
    logic [31:0] req_epoch;
    logic [31:0] req_task_id;
    logic [63:0] req_request_seq;
    logic [15:0] req_context_id;
    logic [31:0] req_generation;
    logic [63:0] req_request_id;
    logic [31:0] req_length;
  } aix_crypto_entropy_w512_req_payload_t;
  typedef struct packed {
    logic [31:0] rsp_owner_id;
    logic [15:0] rsp_instance_id;
    logic [31:0] rsp_epoch;
    logic [31:0] rsp_task_id;
    logic [63:0] rsp_request_seq;
    logic [15:0] rsp_context_id;
    logic [31:0] rsp_generation;
    logic [63:0] rsp_request_id;
    logic [15:0] rsp_status;
    logic [511:0] rsp_data;
    logic [63:0] rsp_keep;
    logic [0:0] rsp_last;
    logic [0:0] rsp_health_ok;
  } aix_crypto_entropy_w512_rsp_payload_t;
  typedef aix_crypto_entropy_w128_req_t aix_crypto_entropy_req_t;
  typedef aix_crypto_entropy_w128_rsp_t aix_crypto_entropy_rsp_t;
  typedef aix_crypto_entropy_w128_req_payload_t aix_crypto_entropy_req_payload_t;
  typedef aix_crypto_entropy_w128_rsp_payload_t aix_crypto_entropy_rsp_payload_t;
endpackage : aix_crypto_entropy_pkg
