// SPDX-License-Identifier: Apache-2.0
// Generated by examples/crypto_interfaces/generate_smoke.py; no service model.
// Contract SHA256: fde0a6acff44d3a2fbcf2fdc59e8c4fc3fbec38a2d90750b1e78b05638b55ca8
`timescale 1ns/1ps
module crypto_entropy_peer_32(aix_crypto_entropy_if.source link,
  input logic [343:0] response, output logic [321:0] observed);
  assign link.req_ready = response[343 +: 1];
  assign link.rsp_valid = response[342 +: 1];
  assign link.rsp_owner_id = response[310 +: 32];
  assign link.rsp_instance_id = response[294 +: 16];
  assign link.rsp_epoch = response[262 +: 32];
  assign link.rsp_task_id = response[230 +: 32];
  assign link.rsp_request_seq = response[166 +: 64];
  assign link.rsp_context_id = response[150 +: 16];
  assign link.rsp_generation = response[118 +: 32];
  assign link.rsp_request_id = response[54 +: 64];
  assign link.rsp_status = response[38 +: 16];
  assign link.rsp_data = response[6 +: 32];
  assign link.rsp_keep = response[2 +: 4];
  assign link.rsp_last = response[1 +: 1];
  assign link.rsp_health_ok = response[0 +: 1];
  assign observed = {link.req_valid, link.req_owner_id, link.req_instance_id, link.req_epoch, link.req_task_id, link.req_request_seq, link.req_context_id, link.req_generation, link.req_request_id, link.req_length, link.rsp_ready};
  always @(posedge link.clk) if (link.reset_n !== 1'b0 && link.reset_n !== 1'b1) $fatal(1,"reset modport");
endmodule
module crypto_entropy_case_32(input logic clk, reset_n, output logic done);
  import aix_crypto_entropy_pkg::*;
  aix_crypto_entropy_w32_req_t request;
  aix_crypto_entropy_w32_rsp_t response;
  logic [343:0] expected;
  logic [321:0] observed;
  aix_crypto_entropy_if #(.DATA_W(32)) link (.clk(clk), .reset_n(reset_n));
  crypto_entropy_peer_32 peer(link, expected, observed);
  aix_crypto_entropy_flat_wrapper #(.DATA_W(32)) bridge(.link(link),
    .req_valid_i(request.req_valid),
    .req_ready_o(response.req_ready),
    .req_owner_id_i(request.req_owner_id),
    .req_instance_id_i(request.req_instance_id),
    .req_epoch_i(request.req_epoch),
    .req_task_id_i(request.req_task_id),
    .req_request_seq_i(request.req_request_seq),
    .req_context_id_i(request.req_context_id),
    .req_generation_i(request.req_generation),
    .req_request_id_i(request.req_request_id),
    .req_length_i(request.req_length),
    .rsp_valid_o(response.rsp_valid),
    .rsp_ready_i(request.rsp_ready),
    .rsp_owner_id_o(response.rsp_owner_id),
    .rsp_instance_id_o(response.rsp_instance_id),
    .rsp_epoch_o(response.rsp_epoch),
    .rsp_task_id_o(response.rsp_task_id),
    .rsp_request_seq_o(response.rsp_request_seq),
    .rsp_context_id_o(response.rsp_context_id),
    .rsp_generation_o(response.rsp_generation),
    .rsp_request_id_o(response.rsp_request_id),
    .rsp_status_o(response.rsp_status),
    .rsp_data_o(response.rsp_data),
    .rsp_keep_o(response.rsp_keep),
    .rsp_last_o(response.rsp_last),
    .rsp_health_ok_o(response.rsp_health_ok)
  );
  function automatic logic [343:0] pattern(input int seed);
    int unsigned state; state=32'h9e3779b9 ^ (32'h85ebca6b * seed);
    for (int i=0;i<344;i++) begin
      state=1664525*state+1013904223; pattern[i]=state[31];
    end
  endfunction
  task automatic compare_paths;
    if (observed !== request) $fatal(1,"crypto_entropy W32 forward wiring");
    if (response !== expected) $fatal(1,"crypto_entropy W32 reverse wiring");
  endtask
  initial begin
    done=0; request='0; expected='0;
    if ($bits(request)!=322 || $bits(response)!=344) $fatal(1,"aggregate width");
    if ($bits(link.req_valid)!=1) $fatal(1,"req_valid width");
    if ($bits(link.req_ready)!=1) $fatal(1,"req_ready width");
    if ($bits(link.req_owner_id)!=32) $fatal(1,"req_owner_id width");
    if ($bits(link.req_instance_id)!=16) $fatal(1,"req_instance_id width");
    if ($bits(link.req_epoch)!=32) $fatal(1,"req_epoch width");
    if ($bits(link.req_task_id)!=32) $fatal(1,"req_task_id width");
    if ($bits(link.req_request_seq)!=64) $fatal(1,"req_request_seq width");
    if ($bits(link.req_context_id)!=16) $fatal(1,"req_context_id width");
    if ($bits(link.req_generation)!=32) $fatal(1,"req_generation width");
    if ($bits(link.req_request_id)!=64) $fatal(1,"req_request_id width");
    if ($bits(link.req_length)!=32) $fatal(1,"req_length width");
    if ($bits(link.rsp_valid)!=1) $fatal(1,"rsp_valid width");
    if ($bits(link.rsp_ready)!=1) $fatal(1,"rsp_ready width");
    if ($bits(link.rsp_owner_id)!=32) $fatal(1,"rsp_owner_id width");
    if ($bits(link.rsp_instance_id)!=16) $fatal(1,"rsp_instance_id width");
    if ($bits(link.rsp_epoch)!=32) $fatal(1,"rsp_epoch width");
    if ($bits(link.rsp_task_id)!=32) $fatal(1,"rsp_task_id width");
    if ($bits(link.rsp_request_seq)!=64) $fatal(1,"rsp_request_seq width");
    if ($bits(link.rsp_context_id)!=16) $fatal(1,"rsp_context_id width");
    if ($bits(link.rsp_generation)!=32) $fatal(1,"rsp_generation width");
    if ($bits(link.rsp_request_id)!=64) $fatal(1,"rsp_request_id width");
    if ($bits(link.rsp_status)!=16) $fatal(1,"rsp_status width");
    if ($bits(link.rsp_data)!=32) $fatal(1,"rsp_data width");
    if ($bits(link.rsp_keep)!=4) $fatal(1,"rsp_keep width");
    if ($bits(link.rsp_last)!=1) $fatal(1,"rsp_last width");
    if ($bits(link.rsp_health_ok)!=1) $fatal(1,"rsp_health_ok width");
    if ($bits(aix_crypto_entropy_w32_req_payload_t)!=320) $fatal(1,"payload width");
    if ($bits(aix_crypto_entropy_w32_rsp_payload_t)!=342) $fatal(1,"payload width");
    wait(reset_n); #1; compare_paths();
    request='1; expected='1; #1; compare_paths();
    for (int sample=1;sample<=128;sample++) begin
      request=322'(pattern(sample)); expected=344'(pattern(sample+271));
      #1; compare_paths();
    end
    for (int bitno=0;bitno<322;bitno++) begin
      request='0; request[bitno]=1'b1; #1; compare_paths(); end
    for (int bitno=0;bitno<344;bitno++) begin
      expected='0; expected[bitno]=1'b1; #1; compare_paths(); end
    $display("PASS crypto_entropy DATA_W=32 fields=26"); done=1;
  end
endmodule
module crypto_entropy_peer_64(aix_crypto_entropy_if.source link,
  input logic [379:0] response, output logic [321:0] observed);
  assign link.req_ready = response[379 +: 1];
  assign link.rsp_valid = response[378 +: 1];
  assign link.rsp_owner_id = response[346 +: 32];
  assign link.rsp_instance_id = response[330 +: 16];
  assign link.rsp_epoch = response[298 +: 32];
  assign link.rsp_task_id = response[266 +: 32];
  assign link.rsp_request_seq = response[202 +: 64];
  assign link.rsp_context_id = response[186 +: 16];
  assign link.rsp_generation = response[154 +: 32];
  assign link.rsp_request_id = response[90 +: 64];
  assign link.rsp_status = response[74 +: 16];
  assign link.rsp_data = response[10 +: 64];
  assign link.rsp_keep = response[2 +: 8];
  assign link.rsp_last = response[1 +: 1];
  assign link.rsp_health_ok = response[0 +: 1];
  assign observed = {link.req_valid, link.req_owner_id, link.req_instance_id, link.req_epoch, link.req_task_id, link.req_request_seq, link.req_context_id, link.req_generation, link.req_request_id, link.req_length, link.rsp_ready};
  always @(posedge link.clk) if (link.reset_n !== 1'b0 && link.reset_n !== 1'b1) $fatal(1,"reset modport");
endmodule
module crypto_entropy_case_64(input logic clk, reset_n, output logic done);
  import aix_crypto_entropy_pkg::*;
  aix_crypto_entropy_w64_req_t request;
  aix_crypto_entropy_w64_rsp_t response;
  logic [379:0] expected;
  logic [321:0] observed;
  aix_crypto_entropy_if #(.DATA_W(64)) link (.clk(clk), .reset_n(reset_n));
  crypto_entropy_peer_64 peer(link, expected, observed);
  aix_crypto_entropy_flat_wrapper #(.DATA_W(64)) bridge(.link(link),
    .req_valid_i(request.req_valid),
    .req_ready_o(response.req_ready),
    .req_owner_id_i(request.req_owner_id),
    .req_instance_id_i(request.req_instance_id),
    .req_epoch_i(request.req_epoch),
    .req_task_id_i(request.req_task_id),
    .req_request_seq_i(request.req_request_seq),
    .req_context_id_i(request.req_context_id),
    .req_generation_i(request.req_generation),
    .req_request_id_i(request.req_request_id),
    .req_length_i(request.req_length),
    .rsp_valid_o(response.rsp_valid),
    .rsp_ready_i(request.rsp_ready),
    .rsp_owner_id_o(response.rsp_owner_id),
    .rsp_instance_id_o(response.rsp_instance_id),
    .rsp_epoch_o(response.rsp_epoch),
    .rsp_task_id_o(response.rsp_task_id),
    .rsp_request_seq_o(response.rsp_request_seq),
    .rsp_context_id_o(response.rsp_context_id),
    .rsp_generation_o(response.rsp_generation),
    .rsp_request_id_o(response.rsp_request_id),
    .rsp_status_o(response.rsp_status),
    .rsp_data_o(response.rsp_data),
    .rsp_keep_o(response.rsp_keep),
    .rsp_last_o(response.rsp_last),
    .rsp_health_ok_o(response.rsp_health_ok)
  );
  function automatic logic [379:0] pattern(input int seed);
    int unsigned state; state=32'h9e3779b9 ^ (32'h85ebca6b * seed);
    for (int i=0;i<380;i++) begin
      state=1664525*state+1013904223; pattern[i]=state[31];
    end
  endfunction
  task automatic compare_paths;
    if (observed !== request) $fatal(1,"crypto_entropy W64 forward wiring");
    if (response !== expected) $fatal(1,"crypto_entropy W64 reverse wiring");
  endtask
  initial begin
    done=0; request='0; expected='0;
    if ($bits(request)!=322 || $bits(response)!=380) $fatal(1,"aggregate width");
    if ($bits(link.req_valid)!=1) $fatal(1,"req_valid width");
    if ($bits(link.req_ready)!=1) $fatal(1,"req_ready width");
    if ($bits(link.req_owner_id)!=32) $fatal(1,"req_owner_id width");
    if ($bits(link.req_instance_id)!=16) $fatal(1,"req_instance_id width");
    if ($bits(link.req_epoch)!=32) $fatal(1,"req_epoch width");
    if ($bits(link.req_task_id)!=32) $fatal(1,"req_task_id width");
    if ($bits(link.req_request_seq)!=64) $fatal(1,"req_request_seq width");
    if ($bits(link.req_context_id)!=16) $fatal(1,"req_context_id width");
    if ($bits(link.req_generation)!=32) $fatal(1,"req_generation width");
    if ($bits(link.req_request_id)!=64) $fatal(1,"req_request_id width");
    if ($bits(link.req_length)!=32) $fatal(1,"req_length width");
    if ($bits(link.rsp_valid)!=1) $fatal(1,"rsp_valid width");
    if ($bits(link.rsp_ready)!=1) $fatal(1,"rsp_ready width");
    if ($bits(link.rsp_owner_id)!=32) $fatal(1,"rsp_owner_id width");
    if ($bits(link.rsp_instance_id)!=16) $fatal(1,"rsp_instance_id width");
    if ($bits(link.rsp_epoch)!=32) $fatal(1,"rsp_epoch width");
    if ($bits(link.rsp_task_id)!=32) $fatal(1,"rsp_task_id width");
    if ($bits(link.rsp_request_seq)!=64) $fatal(1,"rsp_request_seq width");
    if ($bits(link.rsp_context_id)!=16) $fatal(1,"rsp_context_id width");
    if ($bits(link.rsp_generation)!=32) $fatal(1,"rsp_generation width");
    if ($bits(link.rsp_request_id)!=64) $fatal(1,"rsp_request_id width");
    if ($bits(link.rsp_status)!=16) $fatal(1,"rsp_status width");
    if ($bits(link.rsp_data)!=64) $fatal(1,"rsp_data width");
    if ($bits(link.rsp_keep)!=8) $fatal(1,"rsp_keep width");
    if ($bits(link.rsp_last)!=1) $fatal(1,"rsp_last width");
    if ($bits(link.rsp_health_ok)!=1) $fatal(1,"rsp_health_ok width");
    if ($bits(aix_crypto_entropy_w64_req_payload_t)!=320) $fatal(1,"payload width");
    if ($bits(aix_crypto_entropy_w64_rsp_payload_t)!=378) $fatal(1,"payload width");
    wait(reset_n); #1; compare_paths();
    request='1; expected='1; #1; compare_paths();
    for (int sample=1;sample<=128;sample++) begin
      request=322'(pattern(sample)); expected=380'(pattern(sample+271));
      #1; compare_paths();
    end
    for (int bitno=0;bitno<322;bitno++) begin
      request='0; request[bitno]=1'b1; #1; compare_paths(); end
    for (int bitno=0;bitno<380;bitno++) begin
      expected='0; expected[bitno]=1'b1; #1; compare_paths(); end
    $display("PASS crypto_entropy DATA_W=64 fields=26"); done=1;
  end
endmodule
module crypto_entropy_peer_128(aix_crypto_entropy_if.source link,
  input logic [451:0] response, output logic [321:0] observed);
  assign link.req_ready = response[451 +: 1];
  assign link.rsp_valid = response[450 +: 1];
  assign link.rsp_owner_id = response[418 +: 32];
  assign link.rsp_instance_id = response[402 +: 16];
  assign link.rsp_epoch = response[370 +: 32];
  assign link.rsp_task_id = response[338 +: 32];
  assign link.rsp_request_seq = response[274 +: 64];
  assign link.rsp_context_id = response[258 +: 16];
  assign link.rsp_generation = response[226 +: 32];
  assign link.rsp_request_id = response[162 +: 64];
  assign link.rsp_status = response[146 +: 16];
  assign link.rsp_data = response[18 +: 128];
  assign link.rsp_keep = response[2 +: 16];
  assign link.rsp_last = response[1 +: 1];
  assign link.rsp_health_ok = response[0 +: 1];
  assign observed = {link.req_valid, link.req_owner_id, link.req_instance_id, link.req_epoch, link.req_task_id, link.req_request_seq, link.req_context_id, link.req_generation, link.req_request_id, link.req_length, link.rsp_ready};
  always @(posedge link.clk) if (link.reset_n !== 1'b0 && link.reset_n !== 1'b1) $fatal(1,"reset modport");
endmodule
module crypto_entropy_case_128(input logic clk, reset_n, output logic done);
  import aix_crypto_entropy_pkg::*;
  aix_crypto_entropy_w128_req_t request;
  aix_crypto_entropy_w128_rsp_t response;
  logic [451:0] expected;
  logic [321:0] observed;
  aix_crypto_entropy_if #(.DATA_W(128)) link (.clk(clk), .reset_n(reset_n));
  crypto_entropy_peer_128 peer(link, expected, observed);
  aix_crypto_entropy_flat_wrapper #(.DATA_W(128)) bridge(.link(link),
    .req_valid_i(request.req_valid),
    .req_ready_o(response.req_ready),
    .req_owner_id_i(request.req_owner_id),
    .req_instance_id_i(request.req_instance_id),
    .req_epoch_i(request.req_epoch),
    .req_task_id_i(request.req_task_id),
    .req_request_seq_i(request.req_request_seq),
    .req_context_id_i(request.req_context_id),
    .req_generation_i(request.req_generation),
    .req_request_id_i(request.req_request_id),
    .req_length_i(request.req_length),
    .rsp_valid_o(response.rsp_valid),
    .rsp_ready_i(request.rsp_ready),
    .rsp_owner_id_o(response.rsp_owner_id),
    .rsp_instance_id_o(response.rsp_instance_id),
    .rsp_epoch_o(response.rsp_epoch),
    .rsp_task_id_o(response.rsp_task_id),
    .rsp_request_seq_o(response.rsp_request_seq),
    .rsp_context_id_o(response.rsp_context_id),
    .rsp_generation_o(response.rsp_generation),
    .rsp_request_id_o(response.rsp_request_id),
    .rsp_status_o(response.rsp_status),
    .rsp_data_o(response.rsp_data),
    .rsp_keep_o(response.rsp_keep),
    .rsp_last_o(response.rsp_last),
    .rsp_health_ok_o(response.rsp_health_ok)
  );
  function automatic logic [451:0] pattern(input int seed);
    int unsigned state; state=32'h9e3779b9 ^ (32'h85ebca6b * seed);
    for (int i=0;i<452;i++) begin
      state=1664525*state+1013904223; pattern[i]=state[31];
    end
  endfunction
  task automatic compare_paths;
    if (observed !== request) $fatal(1,"crypto_entropy W128 forward wiring");
    if (response !== expected) $fatal(1,"crypto_entropy W128 reverse wiring");
  endtask
  initial begin
    done=0; request='0; expected='0;
    if ($bits(request)!=322 || $bits(response)!=452) $fatal(1,"aggregate width");
    if ($bits(link.req_valid)!=1) $fatal(1,"req_valid width");
    if ($bits(link.req_ready)!=1) $fatal(1,"req_ready width");
    if ($bits(link.req_owner_id)!=32) $fatal(1,"req_owner_id width");
    if ($bits(link.req_instance_id)!=16) $fatal(1,"req_instance_id width");
    if ($bits(link.req_epoch)!=32) $fatal(1,"req_epoch width");
    if ($bits(link.req_task_id)!=32) $fatal(1,"req_task_id width");
    if ($bits(link.req_request_seq)!=64) $fatal(1,"req_request_seq width");
    if ($bits(link.req_context_id)!=16) $fatal(1,"req_context_id width");
    if ($bits(link.req_generation)!=32) $fatal(1,"req_generation width");
    if ($bits(link.req_request_id)!=64) $fatal(1,"req_request_id width");
    if ($bits(link.req_length)!=32) $fatal(1,"req_length width");
    if ($bits(link.rsp_valid)!=1) $fatal(1,"rsp_valid width");
    if ($bits(link.rsp_ready)!=1) $fatal(1,"rsp_ready width");
    if ($bits(link.rsp_owner_id)!=32) $fatal(1,"rsp_owner_id width");
    if ($bits(link.rsp_instance_id)!=16) $fatal(1,"rsp_instance_id width");
    if ($bits(link.rsp_epoch)!=32) $fatal(1,"rsp_epoch width");
    if ($bits(link.rsp_task_id)!=32) $fatal(1,"rsp_task_id width");
    if ($bits(link.rsp_request_seq)!=64) $fatal(1,"rsp_request_seq width");
    if ($bits(link.rsp_context_id)!=16) $fatal(1,"rsp_context_id width");
    if ($bits(link.rsp_generation)!=32) $fatal(1,"rsp_generation width");
    if ($bits(link.rsp_request_id)!=64) $fatal(1,"rsp_request_id width");
    if ($bits(link.rsp_status)!=16) $fatal(1,"rsp_status width");
    if ($bits(link.rsp_data)!=128) $fatal(1,"rsp_data width");
    if ($bits(link.rsp_keep)!=16) $fatal(1,"rsp_keep width");
    if ($bits(link.rsp_last)!=1) $fatal(1,"rsp_last width");
    if ($bits(link.rsp_health_ok)!=1) $fatal(1,"rsp_health_ok width");
    if ($bits(aix_crypto_entropy_w128_req_payload_t)!=320) $fatal(1,"payload width");
    if ($bits(aix_crypto_entropy_w128_rsp_payload_t)!=450) $fatal(1,"payload width");
    if ($bits(aix_crypto_entropy_req_t)!=322 || $bits(aix_crypto_entropy_rsp_t)!=452) $fatal(1,"default aliases");
    wait(reset_n); #1; compare_paths();
    request='1; expected='1; #1; compare_paths();
    for (int sample=1;sample<=128;sample++) begin
      request=322'(pattern(sample)); expected=452'(pattern(sample+271));
      #1; compare_paths();
    end
    for (int bitno=0;bitno<322;bitno++) begin
      request='0; request[bitno]=1'b1; #1; compare_paths(); end
    for (int bitno=0;bitno<452;bitno++) begin
      expected='0; expected[bitno]=1'b1; #1; compare_paths(); end
    $display("PASS crypto_entropy DATA_W=128 fields=26"); done=1;
  end
endmodule
module crypto_entropy_peer_256(aix_crypto_entropy_if.source link,
  input logic [595:0] response, output logic [321:0] observed);
  assign link.req_ready = response[595 +: 1];
  assign link.rsp_valid = response[594 +: 1];
  assign link.rsp_owner_id = response[562 +: 32];
  assign link.rsp_instance_id = response[546 +: 16];
  assign link.rsp_epoch = response[514 +: 32];
  assign link.rsp_task_id = response[482 +: 32];
  assign link.rsp_request_seq = response[418 +: 64];
  assign link.rsp_context_id = response[402 +: 16];
  assign link.rsp_generation = response[370 +: 32];
  assign link.rsp_request_id = response[306 +: 64];
  assign link.rsp_status = response[290 +: 16];
  assign link.rsp_data = response[34 +: 256];
  assign link.rsp_keep = response[2 +: 32];
  assign link.rsp_last = response[1 +: 1];
  assign link.rsp_health_ok = response[0 +: 1];
  assign observed = {link.req_valid, link.req_owner_id, link.req_instance_id, link.req_epoch, link.req_task_id, link.req_request_seq, link.req_context_id, link.req_generation, link.req_request_id, link.req_length, link.rsp_ready};
  always @(posedge link.clk) if (link.reset_n !== 1'b0 && link.reset_n !== 1'b1) $fatal(1,"reset modport");
endmodule
module crypto_entropy_case_256(input logic clk, reset_n, output logic done);
  import aix_crypto_entropy_pkg::*;
  aix_crypto_entropy_w256_req_t request;
  aix_crypto_entropy_w256_rsp_t response;
  logic [595:0] expected;
  logic [321:0] observed;
  aix_crypto_entropy_if #(.DATA_W(256)) link (.clk(clk), .reset_n(reset_n));
  crypto_entropy_peer_256 peer(link, expected, observed);
  aix_crypto_entropy_flat_wrapper #(.DATA_W(256)) bridge(.link(link),
    .req_valid_i(request.req_valid),
    .req_ready_o(response.req_ready),
    .req_owner_id_i(request.req_owner_id),
    .req_instance_id_i(request.req_instance_id),
    .req_epoch_i(request.req_epoch),
    .req_task_id_i(request.req_task_id),
    .req_request_seq_i(request.req_request_seq),
    .req_context_id_i(request.req_context_id),
    .req_generation_i(request.req_generation),
    .req_request_id_i(request.req_request_id),
    .req_length_i(request.req_length),
    .rsp_valid_o(response.rsp_valid),
    .rsp_ready_i(request.rsp_ready),
    .rsp_owner_id_o(response.rsp_owner_id),
    .rsp_instance_id_o(response.rsp_instance_id),
    .rsp_epoch_o(response.rsp_epoch),
    .rsp_task_id_o(response.rsp_task_id),
    .rsp_request_seq_o(response.rsp_request_seq),
    .rsp_context_id_o(response.rsp_context_id),
    .rsp_generation_o(response.rsp_generation),
    .rsp_request_id_o(response.rsp_request_id),
    .rsp_status_o(response.rsp_status),
    .rsp_data_o(response.rsp_data),
    .rsp_keep_o(response.rsp_keep),
    .rsp_last_o(response.rsp_last),
    .rsp_health_ok_o(response.rsp_health_ok)
  );
  function automatic logic [595:0] pattern(input int seed);
    int unsigned state; state=32'h9e3779b9 ^ (32'h85ebca6b * seed);
    for (int i=0;i<596;i++) begin
      state=1664525*state+1013904223; pattern[i]=state[31];
    end
  endfunction
  task automatic compare_paths;
    if (observed !== request) $fatal(1,"crypto_entropy W256 forward wiring");
    if (response !== expected) $fatal(1,"crypto_entropy W256 reverse wiring");
  endtask
  initial begin
    done=0; request='0; expected='0;
    if ($bits(request)!=322 || $bits(response)!=596) $fatal(1,"aggregate width");
    if ($bits(link.req_valid)!=1) $fatal(1,"req_valid width");
    if ($bits(link.req_ready)!=1) $fatal(1,"req_ready width");
    if ($bits(link.req_owner_id)!=32) $fatal(1,"req_owner_id width");
    if ($bits(link.req_instance_id)!=16) $fatal(1,"req_instance_id width");
    if ($bits(link.req_epoch)!=32) $fatal(1,"req_epoch width");
    if ($bits(link.req_task_id)!=32) $fatal(1,"req_task_id width");
    if ($bits(link.req_request_seq)!=64) $fatal(1,"req_request_seq width");
    if ($bits(link.req_context_id)!=16) $fatal(1,"req_context_id width");
    if ($bits(link.req_generation)!=32) $fatal(1,"req_generation width");
    if ($bits(link.req_request_id)!=64) $fatal(1,"req_request_id width");
    if ($bits(link.req_length)!=32) $fatal(1,"req_length width");
    if ($bits(link.rsp_valid)!=1) $fatal(1,"rsp_valid width");
    if ($bits(link.rsp_ready)!=1) $fatal(1,"rsp_ready width");
    if ($bits(link.rsp_owner_id)!=32) $fatal(1,"rsp_owner_id width");
    if ($bits(link.rsp_instance_id)!=16) $fatal(1,"rsp_instance_id width");
    if ($bits(link.rsp_epoch)!=32) $fatal(1,"rsp_epoch width");
    if ($bits(link.rsp_task_id)!=32) $fatal(1,"rsp_task_id width");
    if ($bits(link.rsp_request_seq)!=64) $fatal(1,"rsp_request_seq width");
    if ($bits(link.rsp_context_id)!=16) $fatal(1,"rsp_context_id width");
    if ($bits(link.rsp_generation)!=32) $fatal(1,"rsp_generation width");
    if ($bits(link.rsp_request_id)!=64) $fatal(1,"rsp_request_id width");
    if ($bits(link.rsp_status)!=16) $fatal(1,"rsp_status width");
    if ($bits(link.rsp_data)!=256) $fatal(1,"rsp_data width");
    if ($bits(link.rsp_keep)!=32) $fatal(1,"rsp_keep width");
    if ($bits(link.rsp_last)!=1) $fatal(1,"rsp_last width");
    if ($bits(link.rsp_health_ok)!=1) $fatal(1,"rsp_health_ok width");
    if ($bits(aix_crypto_entropy_w256_req_payload_t)!=320) $fatal(1,"payload width");
    if ($bits(aix_crypto_entropy_w256_rsp_payload_t)!=594) $fatal(1,"payload width");
    wait(reset_n); #1; compare_paths();
    request='1; expected='1; #1; compare_paths();
    for (int sample=1;sample<=128;sample++) begin
      request=322'(pattern(sample)); expected=596'(pattern(sample+271));
      #1; compare_paths();
    end
    for (int bitno=0;bitno<322;bitno++) begin
      request='0; request[bitno]=1'b1; #1; compare_paths(); end
    for (int bitno=0;bitno<596;bitno++) begin
      expected='0; expected[bitno]=1'b1; #1; compare_paths(); end
    $display("PASS crypto_entropy DATA_W=256 fields=26"); done=1;
  end
endmodule
module crypto_entropy_peer_512(aix_crypto_entropy_if.source link,
  input logic [883:0] response, output logic [321:0] observed);
  assign link.req_ready = response[883 +: 1];
  assign link.rsp_valid = response[882 +: 1];
  assign link.rsp_owner_id = response[850 +: 32];
  assign link.rsp_instance_id = response[834 +: 16];
  assign link.rsp_epoch = response[802 +: 32];
  assign link.rsp_task_id = response[770 +: 32];
  assign link.rsp_request_seq = response[706 +: 64];
  assign link.rsp_context_id = response[690 +: 16];
  assign link.rsp_generation = response[658 +: 32];
  assign link.rsp_request_id = response[594 +: 64];
  assign link.rsp_status = response[578 +: 16];
  assign link.rsp_data = response[66 +: 512];
  assign link.rsp_keep = response[2 +: 64];
  assign link.rsp_last = response[1 +: 1];
  assign link.rsp_health_ok = response[0 +: 1];
  assign observed = {link.req_valid, link.req_owner_id, link.req_instance_id, link.req_epoch, link.req_task_id, link.req_request_seq, link.req_context_id, link.req_generation, link.req_request_id, link.req_length, link.rsp_ready};
  always @(posedge link.clk) if (link.reset_n !== 1'b0 && link.reset_n !== 1'b1) $fatal(1,"reset modport");
endmodule
module crypto_entropy_case_512(input logic clk, reset_n, output logic done);
  import aix_crypto_entropy_pkg::*;
  aix_crypto_entropy_w512_req_t request;
  aix_crypto_entropy_w512_rsp_t response;
  logic [883:0] expected;
  logic [321:0] observed;
  aix_crypto_entropy_if #(.DATA_W(512)) link (.clk(clk), .reset_n(reset_n));
  crypto_entropy_peer_512 peer(link, expected, observed);
  aix_crypto_entropy_flat_wrapper #(.DATA_W(512)) bridge(.link(link),
    .req_valid_i(request.req_valid),
    .req_ready_o(response.req_ready),
    .req_owner_id_i(request.req_owner_id),
    .req_instance_id_i(request.req_instance_id),
    .req_epoch_i(request.req_epoch),
    .req_task_id_i(request.req_task_id),
    .req_request_seq_i(request.req_request_seq),
    .req_context_id_i(request.req_context_id),
    .req_generation_i(request.req_generation),
    .req_request_id_i(request.req_request_id),
    .req_length_i(request.req_length),
    .rsp_valid_o(response.rsp_valid),
    .rsp_ready_i(request.rsp_ready),
    .rsp_owner_id_o(response.rsp_owner_id),
    .rsp_instance_id_o(response.rsp_instance_id),
    .rsp_epoch_o(response.rsp_epoch),
    .rsp_task_id_o(response.rsp_task_id),
    .rsp_request_seq_o(response.rsp_request_seq),
    .rsp_context_id_o(response.rsp_context_id),
    .rsp_generation_o(response.rsp_generation),
    .rsp_request_id_o(response.rsp_request_id),
    .rsp_status_o(response.rsp_status),
    .rsp_data_o(response.rsp_data),
    .rsp_keep_o(response.rsp_keep),
    .rsp_last_o(response.rsp_last),
    .rsp_health_ok_o(response.rsp_health_ok)
  );
  function automatic logic [883:0] pattern(input int seed);
    int unsigned state; state=32'h9e3779b9 ^ (32'h85ebca6b * seed);
    for (int i=0;i<884;i++) begin
      state=1664525*state+1013904223; pattern[i]=state[31];
    end
  endfunction
  task automatic compare_paths;
    if (observed !== request) $fatal(1,"crypto_entropy W512 forward wiring");
    if (response !== expected) $fatal(1,"crypto_entropy W512 reverse wiring");
  endtask
  initial begin
    done=0; request='0; expected='0;
    if ($bits(request)!=322 || $bits(response)!=884) $fatal(1,"aggregate width");
    if ($bits(link.req_valid)!=1) $fatal(1,"req_valid width");
    if ($bits(link.req_ready)!=1) $fatal(1,"req_ready width");
    if ($bits(link.req_owner_id)!=32) $fatal(1,"req_owner_id width");
    if ($bits(link.req_instance_id)!=16) $fatal(1,"req_instance_id width");
    if ($bits(link.req_epoch)!=32) $fatal(1,"req_epoch width");
    if ($bits(link.req_task_id)!=32) $fatal(1,"req_task_id width");
    if ($bits(link.req_request_seq)!=64) $fatal(1,"req_request_seq width");
    if ($bits(link.req_context_id)!=16) $fatal(1,"req_context_id width");
    if ($bits(link.req_generation)!=32) $fatal(1,"req_generation width");
    if ($bits(link.req_request_id)!=64) $fatal(1,"req_request_id width");
    if ($bits(link.req_length)!=32) $fatal(1,"req_length width");
    if ($bits(link.rsp_valid)!=1) $fatal(1,"rsp_valid width");
    if ($bits(link.rsp_ready)!=1) $fatal(1,"rsp_ready width");
    if ($bits(link.rsp_owner_id)!=32) $fatal(1,"rsp_owner_id width");
    if ($bits(link.rsp_instance_id)!=16) $fatal(1,"rsp_instance_id width");
    if ($bits(link.rsp_epoch)!=32) $fatal(1,"rsp_epoch width");
    if ($bits(link.rsp_task_id)!=32) $fatal(1,"rsp_task_id width");
    if ($bits(link.rsp_request_seq)!=64) $fatal(1,"rsp_request_seq width");
    if ($bits(link.rsp_context_id)!=16) $fatal(1,"rsp_context_id width");
    if ($bits(link.rsp_generation)!=32) $fatal(1,"rsp_generation width");
    if ($bits(link.rsp_request_id)!=64) $fatal(1,"rsp_request_id width");
    if ($bits(link.rsp_status)!=16) $fatal(1,"rsp_status width");
    if ($bits(link.rsp_data)!=512) $fatal(1,"rsp_data width");
    if ($bits(link.rsp_keep)!=64) $fatal(1,"rsp_keep width");
    if ($bits(link.rsp_last)!=1) $fatal(1,"rsp_last width");
    if ($bits(link.rsp_health_ok)!=1) $fatal(1,"rsp_health_ok width");
    if ($bits(aix_crypto_entropy_w512_req_payload_t)!=320) $fatal(1,"payload width");
    if ($bits(aix_crypto_entropy_w512_rsp_payload_t)!=882) $fatal(1,"payload width");
    wait(reset_n); #1; compare_paths();
    request='1; expected='1; #1; compare_paths();
    for (int sample=1;sample<=128;sample++) begin
      request=322'(pattern(sample)); expected=884'(pattern(sample+271));
      #1; compare_paths();
    end
    for (int bitno=0;bitno<322;bitno++) begin
      request='0; request[bitno]=1'b1; #1; compare_paths(); end
    for (int bitno=0;bitno<884;bitno++) begin
      expected='0; expected[bitno]=1'b1; #1; compare_paths(); end
    $display("PASS crypto_entropy DATA_W=512 fields=26"); done=1;
  end
endmodule
module tb_crypto_entropy;
  logic clk=0; logic reset_n=0;
  logic [4:0] done;
  always #5 clk=~clk;
  initial begin #20; reset_n=1; end
  crypto_entropy_case_32 case_32(clk,reset_n,done[0]);
  crypto_entropy_case_64 case_64(clk,reset_n,done[1]);
  crypto_entropy_case_128 case_128(clk,reset_n,done[2]);
  crypto_entropy_case_256 case_256(clk,reset_n,done[3]);
  crypto_entropy_case_512 case_512(clk,reset_n,done[4]);
  initial begin wait (&done); $display("HWIF_SMOKE_PASS crypto_entropy"); $finish; end
  initial begin #100000; $fatal(1,"timeout"); end
endmodule
