// SPDX-License-Identifier: Apache-2.0
// Generated from the interface contract. Do not edit.
module aix_crypto_staging_flat_wrapper #(parameter int unsigned DATA_W = 128)(
  aix_crypto_staging_if.shell link,
  input logic [(1)-1:0] req_valid_i,
  output logic [(1)-1:0] req_ready_o,
  input logic [(32)-1:0] req_owner_id_i,
  input logic [(16)-1:0] req_instance_id_i,
  input logic [(32)-1:0] req_epoch_i,
  input logic [(32)-1:0] req_task_id_i,
  input logic [(64)-1:0] req_request_seq_i,
  input logic [(16)-1:0] req_context_id_i,
  input logic [(32)-1:0] req_generation_i,
  input logic [(16)-1:0] req_service_version_i,
  input logic [(64)-1:0] req_request_id_i,
  input logic [(8)-1:0] req_operation_i,
  input logic [(64)-1:0] req_staging_ref_i,
  input logic [(64)-1:0] req_length_i,
  input logic [(32)-1:0] req_policy_epoch_i,
  input logic [(1)-1:0] req_auth_valid_i,
  input logic [(1)-1:0] req_auth_ok_i,
  output logic [(1)-1:0] rsp_valid_o,
  input logic [(1)-1:0] rsp_ready_i,
  output logic [(32)-1:0] rsp_owner_id_o,
  output logic [(16)-1:0] rsp_instance_id_o,
  output logic [(32)-1:0] rsp_epoch_o,
  output logic [(32)-1:0] rsp_task_id_o,
  output logic [(64)-1:0] rsp_request_seq_o,
  output logic [(16)-1:0] rsp_context_id_o,
  output logic [(32)-1:0] rsp_generation_o,
  output logic [(64)-1:0] rsp_request_id_o,
  output logic [(16)-1:0] rsp_status_o,
  output logic [(64)-1:0] rsp_staging_ref_o,
  output logic [(64)-1:0] rsp_reserved_bytes_o,
  output logic [(64)-1:0] rsp_written_bytes_o,
  output logic [(8)-1:0] rsp_state_o,
  output logic [(1)-1:0] rsp_cleanup_done_o,
  input logic [(1)-1:0] write_valid_i,
  output logic [(1)-1:0] write_ready_o,
  input logic [(32)-1:0] write_owner_id_i,
  input logic [(16)-1:0] write_instance_id_i,
  input logic [(32)-1:0] write_epoch_i,
  input logic [(32)-1:0] write_task_id_i,
  input logic [(64)-1:0] write_request_seq_i,
  input logic [(16)-1:0] write_context_id_i,
  input logic [(32)-1:0] write_generation_i,
  input logic [(64)-1:0] write_staging_ref_i,
  input logic [(64)-1:0] write_offset_i,
  input logic [(DATA_W)-1:0] write_data_i,
  input logic [(DATA_W/8)-1:0] write_keep_i,
  input logic [(1)-1:0] write_last_i,
  input logic [(1)-1:0] control_req_valid_i,
  output logic [(1)-1:0] control_req_ready_o,
  input logic [(32)-1:0] control_req_owner_id_i,
  input logic [(16)-1:0] control_req_instance_id_i,
  input logic [(32)-1:0] control_req_epoch_i,
  input logic [(32)-1:0] control_req_task_id_i,
  input logic [(64)-1:0] control_req_request_seq_i,
  input logic [(16)-1:0] control_req_context_id_i,
  input logic [(32)-1:0] control_req_generation_i,
  input logic [(16)-1:0] control_req_service_version_i,
  input logic [(64)-1:0] control_req_request_id_i,
  input logic [(8)-1:0] control_req_operation_i,
  input logic [(64)-1:0] control_req_staging_ref_i,
  input logic [(64)-1:0] control_req_length_i,
  input logic [(32)-1:0] control_req_policy_epoch_i,
  input logic [(1)-1:0] control_req_auth_valid_i,
  input logic [(1)-1:0] control_req_auth_ok_i,
  output logic [(1)-1:0] control_rsp_valid_o,
  input logic [(1)-1:0] control_rsp_ready_i,
  output logic [(32)-1:0] control_rsp_owner_id_o,
  output logic [(16)-1:0] control_rsp_instance_id_o,
  output logic [(32)-1:0] control_rsp_epoch_o,
  output logic [(32)-1:0] control_rsp_task_id_o,
  output logic [(64)-1:0] control_rsp_request_seq_o,
  output logic [(16)-1:0] control_rsp_context_id_o,
  output logic [(32)-1:0] control_rsp_generation_o,
  output logic [(64)-1:0] control_rsp_request_id_o,
  output logic [(16)-1:0] control_rsp_status_o,
  output logic [(8)-1:0] control_rsp_state_o,
  output logic [(1)-1:0] control_rsp_cleanup_done_o
);
  assign link.req_valid = req_valid_i;
  assign req_ready_o = link.req_ready;
  assign link.req_owner_id = req_owner_id_i;
  assign link.req_instance_id = req_instance_id_i;
  assign link.req_epoch = req_epoch_i;
  assign link.req_task_id = req_task_id_i;
  assign link.req_request_seq = req_request_seq_i;
  assign link.req_context_id = req_context_id_i;
  assign link.req_generation = req_generation_i;
  assign link.req_service_version = req_service_version_i;
  assign link.req_request_id = req_request_id_i;
  assign link.req_operation = req_operation_i;
  assign link.req_staging_ref = req_staging_ref_i;
  assign link.req_length = req_length_i;
  assign link.req_policy_epoch = req_policy_epoch_i;
  assign link.req_auth_valid = req_auth_valid_i;
  assign link.req_auth_ok = req_auth_ok_i;
  assign rsp_valid_o = link.rsp_valid;
  assign link.rsp_ready = rsp_ready_i;
  assign rsp_owner_id_o = link.rsp_owner_id;
  assign rsp_instance_id_o = link.rsp_instance_id;
  assign rsp_epoch_o = link.rsp_epoch;
  assign rsp_task_id_o = link.rsp_task_id;
  assign rsp_request_seq_o = link.rsp_request_seq;
  assign rsp_context_id_o = link.rsp_context_id;
  assign rsp_generation_o = link.rsp_generation;
  assign rsp_request_id_o = link.rsp_request_id;
  assign rsp_status_o = link.rsp_status;
  assign rsp_staging_ref_o = link.rsp_staging_ref;
  assign rsp_reserved_bytes_o = link.rsp_reserved_bytes;
  assign rsp_written_bytes_o = link.rsp_written_bytes;
  assign rsp_state_o = link.rsp_state;
  assign rsp_cleanup_done_o = link.rsp_cleanup_done;
  assign link.write_valid = write_valid_i;
  assign write_ready_o = link.write_ready;
  assign link.write_owner_id = write_owner_id_i;
  assign link.write_instance_id = write_instance_id_i;
  assign link.write_epoch = write_epoch_i;
  assign link.write_task_id = write_task_id_i;
  assign link.write_request_seq = write_request_seq_i;
  assign link.write_context_id = write_context_id_i;
  assign link.write_generation = write_generation_i;
  assign link.write_staging_ref = write_staging_ref_i;
  assign link.write_offset = write_offset_i;
  assign link.write_data = write_data_i;
  assign link.write_keep = write_keep_i;
  assign link.write_last = write_last_i;
  assign link.control_req_valid = control_req_valid_i;
  assign control_req_ready_o = link.control_req_ready;
  assign link.control_req_owner_id = control_req_owner_id_i;
  assign link.control_req_instance_id = control_req_instance_id_i;
  assign link.control_req_epoch = control_req_epoch_i;
  assign link.control_req_task_id = control_req_task_id_i;
  assign link.control_req_request_seq = control_req_request_seq_i;
  assign link.control_req_context_id = control_req_context_id_i;
  assign link.control_req_generation = control_req_generation_i;
  assign link.control_req_service_version = control_req_service_version_i;
  assign link.control_req_request_id = control_req_request_id_i;
  assign link.control_req_operation = control_req_operation_i;
  assign link.control_req_staging_ref = control_req_staging_ref_i;
  assign link.control_req_length = control_req_length_i;
  assign link.control_req_policy_epoch = control_req_policy_epoch_i;
  assign link.control_req_auth_valid = control_req_auth_valid_i;
  assign link.control_req_auth_ok = control_req_auth_ok_i;
  assign control_rsp_valid_o = link.control_rsp_valid;
  assign link.control_rsp_ready = control_rsp_ready_i;
  assign control_rsp_owner_id_o = link.control_rsp_owner_id;
  assign control_rsp_instance_id_o = link.control_rsp_instance_id;
  assign control_rsp_epoch_o = link.control_rsp_epoch;
  assign control_rsp_task_id_o = link.control_rsp_task_id;
  assign control_rsp_request_seq_o = link.control_rsp_request_seq;
  assign control_rsp_context_id_o = link.control_rsp_context_id;
  assign control_rsp_generation_o = link.control_rsp_generation;
  assign control_rsp_request_id_o = link.control_rsp_request_id;
  assign control_rsp_status_o = link.control_rsp_status;
  assign control_rsp_state_o = link.control_rsp_state;
  assign control_rsp_cleanup_done_o = link.control_rsp_cleanup_done;
endmodule
