// SPDX-License-Identifier: Apache-2.0
// Generated from the interface contract. Do not edit.

package aix_crypto_staging_pkg;
  localparam int unsigned DATA_W = 128;
  localparam int unsigned OPERATION_RESERVE = 1;
  localparam int unsigned OPERATION_PREPARE = 2;
  localparam int unsigned OPERATION_COMMIT = 3;
  localparam int unsigned OPERATION_DESTROY = 4;
  localparam int unsigned OPERATION_QUERY = 5;
  localparam int unsigned STATE_NONE = 0;
  localparam int unsigned STATE_RESERVED = 1;
  localparam int unsigned STATE_WRITTEN = 2;
  localparam int unsigned STATE_PREPARED = 3;
  localparam int unsigned STATE_COMMITTED = 4;
  localparam int unsigned STATE_DESTROYED = 5;
  localparam int unsigned STATE_LOCKED = 6;
  localparam int unsigned STATE_UNKNOWN = 7;
  typedef struct packed {
    logic [0:0] req_valid;
    logic [31:0] req_owner_id;
    logic [15:0] req_instance_id;
    logic [31:0] req_epoch;
    logic [31:0] req_task_id;
    logic [63:0] req_request_seq;
    logic [15:0] req_context_id;
    logic [31:0] req_generation;
    logic [15:0] req_service_version;
    logic [63:0] req_request_id;
    logic [7:0] req_operation;
    logic [63:0] req_staging_ref;
    logic [63:0] req_length;
    logic [31:0] req_policy_epoch;
    logic [0:0] req_auth_valid;
    logic [0:0] req_auth_ok;
    logic [0:0] rsp_ready;
    logic [0:0] write_valid;
    logic [31:0] write_owner_id;
    logic [15:0] write_instance_id;
    logic [31:0] write_epoch;
    logic [31:0] write_task_id;
    logic [63:0] write_request_seq;
    logic [15:0] write_context_id;
    logic [31:0] write_generation;
    logic [63:0] write_staging_ref;
    logic [63:0] write_offset;
    logic [31:0] write_data;
    logic [3:0] write_keep;
    logic [0:0] write_last;
    logic [0:0] control_req_valid;
    logic [31:0] control_req_owner_id;
    logic [15:0] control_req_instance_id;
    logic [31:0] control_req_epoch;
    logic [31:0] control_req_task_id;
    logic [63:0] control_req_request_seq;
    logic [15:0] control_req_context_id;
    logic [31:0] control_req_generation;
    logic [15:0] control_req_service_version;
    logic [63:0] control_req_request_id;
    logic [7:0] control_req_operation;
    logic [63:0] control_req_staging_ref;
    logic [63:0] control_req_length;
    logic [31:0] control_req_policy_epoch;
    logic [0:0] control_req_auth_valid;
    logic [0:0] control_req_auth_ok;
    logic [0:0] control_rsp_ready;
  } aix_crypto_staging_w32_req_t;
  typedef struct packed {
    logic [0:0] req_ready;
    logic [0:0] rsp_valid;
    logic [31:0] rsp_owner_id;
    logic [15:0] rsp_instance_id;
    logic [31:0] rsp_epoch;
    logic [31:0] rsp_task_id;
    logic [63:0] rsp_request_seq;
    logic [15:0] rsp_context_id;
    logic [31:0] rsp_generation;
    logic [63:0] rsp_request_id;
    logic [15:0] rsp_status;
    logic [63:0] rsp_staging_ref;
    logic [63:0] rsp_reserved_bytes;
    logic [63:0] rsp_written_bytes;
    logic [7:0] rsp_state;
    logic [0:0] rsp_cleanup_done;
    logic [0:0] write_ready;
    logic [0:0] control_req_ready;
    logic [0:0] control_rsp_valid;
    logic [31:0] control_rsp_owner_id;
    logic [15:0] control_rsp_instance_id;
    logic [31:0] control_rsp_epoch;
    logic [31:0] control_rsp_task_id;
    logic [63:0] control_rsp_request_seq;
    logic [15:0] control_rsp_context_id;
    logic [31:0] control_rsp_generation;
    logic [63:0] control_rsp_request_id;
    logic [15:0] control_rsp_status;
    logic [7:0] control_rsp_state;
    logic [0:0] control_rsp_cleanup_done;
  } aix_crypto_staging_w32_rsp_t;
  typedef struct packed {
    logic [31:0] req_owner_id;
    logic [15:0] req_instance_id;
    logic [31:0] req_epoch;
    logic [31:0] req_task_id;
    logic [63:0] req_request_seq;
    logic [15:0] req_context_id;
    logic [31:0] req_generation;
    logic [15:0] req_service_version;
    logic [63:0] req_request_id;
    logic [7:0] req_operation;
    logic [63:0] req_staging_ref;
    logic [63:0] req_length;
    logic [31:0] req_policy_epoch;
    logic [0:0] req_auth_valid;
    logic [0:0] req_auth_ok;
  } aix_crypto_staging_w32_req_payload_t;
  typedef struct packed {
    logic [31:0] rsp_owner_id;
    logic [15:0] rsp_instance_id;
    logic [31:0] rsp_epoch;
    logic [31:0] rsp_task_id;
    logic [63:0] rsp_request_seq;
    logic [15:0] rsp_context_id;
    logic [31:0] rsp_generation;
    logic [63:0] rsp_request_id;
    logic [15:0] rsp_status;
    logic [63:0] rsp_staging_ref;
    logic [63:0] rsp_reserved_bytes;
    logic [63:0] rsp_written_bytes;
    logic [7:0] rsp_state;
    logic [0:0] rsp_cleanup_done;
  } aix_crypto_staging_w32_rsp_payload_t;
  typedef struct packed {
    logic [31:0] write_owner_id;
    logic [15:0] write_instance_id;
    logic [31:0] write_epoch;
    logic [31:0] write_task_id;
    logic [63:0] write_request_seq;
    logic [15:0] write_context_id;
    logic [31:0] write_generation;
    logic [63:0] write_staging_ref;
    logic [63:0] write_offset;
    logic [31:0] write_data;
    logic [3:0] write_keep;
    logic [0:0] write_last;
  } aix_crypto_staging_w32_write_payload_t;
  typedef struct packed {
    logic [31:0] control_req_owner_id;
    logic [15:0] control_req_instance_id;
    logic [31:0] control_req_epoch;
    logic [31:0] control_req_task_id;
    logic [63:0] control_req_request_seq;
    logic [15:0] control_req_context_id;
    logic [31:0] control_req_generation;
    logic [15:0] control_req_service_version;
    logic [63:0] control_req_request_id;
    logic [7:0] control_req_operation;
    logic [63:0] control_req_staging_ref;
    logic [63:0] control_req_length;
    logic [31:0] control_req_policy_epoch;
    logic [0:0] control_req_auth_valid;
    logic [0:0] control_req_auth_ok;
  } aix_crypto_staging_w32_control_req_payload_t;
  typedef struct packed {
    logic [31:0] control_rsp_owner_id;
    logic [15:0] control_rsp_instance_id;
    logic [31:0] control_rsp_epoch;
    logic [31:0] control_rsp_task_id;
    logic [63:0] control_rsp_request_seq;
    logic [15:0] control_rsp_context_id;
    logic [31:0] control_rsp_generation;
    logic [63:0] control_rsp_request_id;
    logic [15:0] control_rsp_status;
    logic [7:0] control_rsp_state;
    logic [0:0] control_rsp_cleanup_done;
  } aix_crypto_staging_w32_control_rsp_payload_t;
  typedef struct packed {
    logic [0:0] req_valid;
    logic [31:0] req_owner_id;
    logic [15:0] req_instance_id;
    logic [31:0] req_epoch;
    logic [31:0] req_task_id;
    logic [63:0] req_request_seq;
    logic [15:0] req_context_id;
    logic [31:0] req_generation;
    logic [15:0] req_service_version;
    logic [63:0] req_request_id;
    logic [7:0] req_operation;
    logic [63:0] req_staging_ref;
    logic [63:0] req_length;
    logic [31:0] req_policy_epoch;
    logic [0:0] req_auth_valid;
    logic [0:0] req_auth_ok;
    logic [0:0] rsp_ready;
    logic [0:0] write_valid;
    logic [31:0] write_owner_id;
    logic [15:0] write_instance_id;
    logic [31:0] write_epoch;
    logic [31:0] write_task_id;
    logic [63:0] write_request_seq;
    logic [15:0] write_context_id;
    logic [31:0] write_generation;
    logic [63:0] write_staging_ref;
    logic [63:0] write_offset;
    logic [63:0] write_data;
    logic [7:0] write_keep;
    logic [0:0] write_last;
    logic [0:0] control_req_valid;
    logic [31:0] control_req_owner_id;
    logic [15:0] control_req_instance_id;
    logic [31:0] control_req_epoch;
    logic [31:0] control_req_task_id;
    logic [63:0] control_req_request_seq;
    logic [15:0] control_req_context_id;
    logic [31:0] control_req_generation;
    logic [15:0] control_req_service_version;
    logic [63:0] control_req_request_id;
    logic [7:0] control_req_operation;
    logic [63:0] control_req_staging_ref;
    logic [63:0] control_req_length;
    logic [31:0] control_req_policy_epoch;
    logic [0:0] control_req_auth_valid;
    logic [0:0] control_req_auth_ok;
    logic [0:0] control_rsp_ready;
  } aix_crypto_staging_w64_req_t;
  typedef struct packed {
    logic [0:0] req_ready;
    logic [0:0] rsp_valid;
    logic [31:0] rsp_owner_id;
    logic [15:0] rsp_instance_id;
    logic [31:0] rsp_epoch;
    logic [31:0] rsp_task_id;
    logic [63:0] rsp_request_seq;
    logic [15:0] rsp_context_id;
    logic [31:0] rsp_generation;
    logic [63:0] rsp_request_id;
    logic [15:0] rsp_status;
    logic [63:0] rsp_staging_ref;
    logic [63:0] rsp_reserved_bytes;
    logic [63:0] rsp_written_bytes;
    logic [7:0] rsp_state;
    logic [0:0] rsp_cleanup_done;
    logic [0:0] write_ready;
    logic [0:0] control_req_ready;
    logic [0:0] control_rsp_valid;
    logic [31:0] control_rsp_owner_id;
    logic [15:0] control_rsp_instance_id;
    logic [31:0] control_rsp_epoch;
    logic [31:0] control_rsp_task_id;
    logic [63:0] control_rsp_request_seq;
    logic [15:0] control_rsp_context_id;
    logic [31:0] control_rsp_generation;
    logic [63:0] control_rsp_request_id;
    logic [15:0] control_rsp_status;
    logic [7:0] control_rsp_state;
    logic [0:0] control_rsp_cleanup_done;
  } aix_crypto_staging_w64_rsp_t;
  typedef struct packed {
    logic [31:0] req_owner_id;
    logic [15:0] req_instance_id;
    logic [31:0] req_epoch;
    logic [31:0] req_task_id;
    logic [63:0] req_request_seq;
    logic [15:0] req_context_id;
    logic [31:0] req_generation;
    logic [15:0] req_service_version;
    logic [63:0] req_request_id;
    logic [7:0] req_operation;
    logic [63:0] req_staging_ref;
    logic [63:0] req_length;
    logic [31:0] req_policy_epoch;
    logic [0:0] req_auth_valid;
    logic [0:0] req_auth_ok;
  } aix_crypto_staging_w64_req_payload_t;
  typedef struct packed {
    logic [31:0] rsp_owner_id;
    logic [15:0] rsp_instance_id;
    logic [31:0] rsp_epoch;
    logic [31:0] rsp_task_id;
    logic [63:0] rsp_request_seq;
    logic [15:0] rsp_context_id;
    logic [31:0] rsp_generation;
    logic [63:0] rsp_request_id;
    logic [15:0] rsp_status;
    logic [63:0] rsp_staging_ref;
    logic [63:0] rsp_reserved_bytes;
    logic [63:0] rsp_written_bytes;
    logic [7:0] rsp_state;
    logic [0:0] rsp_cleanup_done;
  } aix_crypto_staging_w64_rsp_payload_t;
  typedef struct packed {
    logic [31:0] write_owner_id;
    logic [15:0] write_instance_id;
    logic [31:0] write_epoch;
    logic [31:0] write_task_id;
    logic [63:0] write_request_seq;
    logic [15:0] write_context_id;
    logic [31:0] write_generation;
    logic [63:0] write_staging_ref;
    logic [63:0] write_offset;
    logic [63:0] write_data;
    logic [7:0] write_keep;
    logic [0:0] write_last;
  } aix_crypto_staging_w64_write_payload_t;
  typedef struct packed {
    logic [31:0] control_req_owner_id;
    logic [15:0] control_req_instance_id;
    logic [31:0] control_req_epoch;
    logic [31:0] control_req_task_id;
    logic [63:0] control_req_request_seq;
    logic [15:0] control_req_context_id;
    logic [31:0] control_req_generation;
    logic [15:0] control_req_service_version;
    logic [63:0] control_req_request_id;
    logic [7:0] control_req_operation;
    logic [63:0] control_req_staging_ref;
    logic [63:0] control_req_length;
    logic [31:0] control_req_policy_epoch;
    logic [0:0] control_req_auth_valid;
    logic [0:0] control_req_auth_ok;
  } aix_crypto_staging_w64_control_req_payload_t;
  typedef struct packed {
    logic [31:0] control_rsp_owner_id;
    logic [15:0] control_rsp_instance_id;
    logic [31:0] control_rsp_epoch;
    logic [31:0] control_rsp_task_id;
    logic [63:0] control_rsp_request_seq;
    logic [15:0] control_rsp_context_id;
    logic [31:0] control_rsp_generation;
    logic [63:0] control_rsp_request_id;
    logic [15:0] control_rsp_status;
    logic [7:0] control_rsp_state;
    logic [0:0] control_rsp_cleanup_done;
  } aix_crypto_staging_w64_control_rsp_payload_t;
  typedef struct packed {
    logic [0:0] req_valid;
    logic [31:0] req_owner_id;
    logic [15:0] req_instance_id;
    logic [31:0] req_epoch;
    logic [31:0] req_task_id;
    logic [63:0] req_request_seq;
    logic [15:0] req_context_id;
    logic [31:0] req_generation;
    logic [15:0] req_service_version;
    logic [63:0] req_request_id;
    logic [7:0] req_operation;
    logic [63:0] req_staging_ref;
    logic [63:0] req_length;
    logic [31:0] req_policy_epoch;
    logic [0:0] req_auth_valid;
    logic [0:0] req_auth_ok;
    logic [0:0] rsp_ready;
    logic [0:0] write_valid;
    logic [31:0] write_owner_id;
    logic [15:0] write_instance_id;
    logic [31:0] write_epoch;
    logic [31:0] write_task_id;
    logic [63:0] write_request_seq;
    logic [15:0] write_context_id;
    logic [31:0] write_generation;
    logic [63:0] write_staging_ref;
    logic [63:0] write_offset;
    logic [127:0] write_data;
    logic [15:0] write_keep;
    logic [0:0] write_last;
    logic [0:0] control_req_valid;
    logic [31:0] control_req_owner_id;
    logic [15:0] control_req_instance_id;
    logic [31:0] control_req_epoch;
    logic [31:0] control_req_task_id;
    logic [63:0] control_req_request_seq;
    logic [15:0] control_req_context_id;
    logic [31:0] control_req_generation;
    logic [15:0] control_req_service_version;
    logic [63:0] control_req_request_id;
    logic [7:0] control_req_operation;
    logic [63:0] control_req_staging_ref;
    logic [63:0] control_req_length;
    logic [31:0] control_req_policy_epoch;
    logic [0:0] control_req_auth_valid;
    logic [0:0] control_req_auth_ok;
    logic [0:0] control_rsp_ready;
  } aix_crypto_staging_w128_req_t;
  typedef struct packed {
    logic [0:0] req_ready;
    logic [0:0] rsp_valid;
    logic [31:0] rsp_owner_id;
    logic [15:0] rsp_instance_id;
    logic [31:0] rsp_epoch;
    logic [31:0] rsp_task_id;
    logic [63:0] rsp_request_seq;
    logic [15:0] rsp_context_id;
    logic [31:0] rsp_generation;
    logic [63:0] rsp_request_id;
    logic [15:0] rsp_status;
    logic [63:0] rsp_staging_ref;
    logic [63:0] rsp_reserved_bytes;
    logic [63:0] rsp_written_bytes;
    logic [7:0] rsp_state;
    logic [0:0] rsp_cleanup_done;
    logic [0:0] write_ready;
    logic [0:0] control_req_ready;
    logic [0:0] control_rsp_valid;
    logic [31:0] control_rsp_owner_id;
    logic [15:0] control_rsp_instance_id;
    logic [31:0] control_rsp_epoch;
    logic [31:0] control_rsp_task_id;
    logic [63:0] control_rsp_request_seq;
    logic [15:0] control_rsp_context_id;
    logic [31:0] control_rsp_generation;
    logic [63:0] control_rsp_request_id;
    logic [15:0] control_rsp_status;
    logic [7:0] control_rsp_state;
    logic [0:0] control_rsp_cleanup_done;
  } aix_crypto_staging_w128_rsp_t;
  typedef struct packed {
    logic [31:0] req_owner_id;
    logic [15:0] req_instance_id;
    logic [31:0] req_epoch;
    logic [31:0] req_task_id;
    logic [63:0] req_request_seq;
    logic [15:0] req_context_id;
    logic [31:0] req_generation;
    logic [15:0] req_service_version;
    logic [63:0] req_request_id;
    logic [7:0] req_operation;
    logic [63:0] req_staging_ref;
    logic [63:0] req_length;
    logic [31:0] req_policy_epoch;
    logic [0:0] req_auth_valid;
    logic [0:0] req_auth_ok;
  } aix_crypto_staging_w128_req_payload_t;
  typedef struct packed {
    logic [31:0] rsp_owner_id;
    logic [15:0] rsp_instance_id;
    logic [31:0] rsp_epoch;
    logic [31:0] rsp_task_id;
    logic [63:0] rsp_request_seq;
    logic [15:0] rsp_context_id;
    logic [31:0] rsp_generation;
    logic [63:0] rsp_request_id;
    logic [15:0] rsp_status;
    logic [63:0] rsp_staging_ref;
    logic [63:0] rsp_reserved_bytes;
    logic [63:0] rsp_written_bytes;
    logic [7:0] rsp_state;
    logic [0:0] rsp_cleanup_done;
  } aix_crypto_staging_w128_rsp_payload_t;
  typedef struct packed {
    logic [31:0] write_owner_id;
    logic [15:0] write_instance_id;
    logic [31:0] write_epoch;
    logic [31:0] write_task_id;
    logic [63:0] write_request_seq;
    logic [15:0] write_context_id;
    logic [31:0] write_generation;
    logic [63:0] write_staging_ref;
    logic [63:0] write_offset;
    logic [127:0] write_data;
    logic [15:0] write_keep;
    logic [0:0] write_last;
  } aix_crypto_staging_w128_write_payload_t;
  typedef struct packed {
    logic [31:0] control_req_owner_id;
    logic [15:0] control_req_instance_id;
    logic [31:0] control_req_epoch;
    logic [31:0] control_req_task_id;
    logic [63:0] control_req_request_seq;
    logic [15:0] control_req_context_id;
    logic [31:0] control_req_generation;
    logic [15:0] control_req_service_version;
    logic [63:0] control_req_request_id;
    logic [7:0] control_req_operation;
    logic [63:0] control_req_staging_ref;
    logic [63:0] control_req_length;
    logic [31:0] control_req_policy_epoch;
    logic [0:0] control_req_auth_valid;
    logic [0:0] control_req_auth_ok;
  } aix_crypto_staging_w128_control_req_payload_t;
  typedef struct packed {
    logic [31:0] control_rsp_owner_id;
    logic [15:0] control_rsp_instance_id;
    logic [31:0] control_rsp_epoch;
    logic [31:0] control_rsp_task_id;
    logic [63:0] control_rsp_request_seq;
    logic [15:0] control_rsp_context_id;
    logic [31:0] control_rsp_generation;
    logic [63:0] control_rsp_request_id;
    logic [15:0] control_rsp_status;
    logic [7:0] control_rsp_state;
    logic [0:0] control_rsp_cleanup_done;
  } aix_crypto_staging_w128_control_rsp_payload_t;
  typedef struct packed {
    logic [0:0] req_valid;
    logic [31:0] req_owner_id;
    logic [15:0] req_instance_id;
    logic [31:0] req_epoch;
    logic [31:0] req_task_id;
    logic [63:0] req_request_seq;
    logic [15:0] req_context_id;
    logic [31:0] req_generation;
    logic [15:0] req_service_version;
    logic [63:0] req_request_id;
    logic [7:0] req_operation;
    logic [63:0] req_staging_ref;
    logic [63:0] req_length;
    logic [31:0] req_policy_epoch;
    logic [0:0] req_auth_valid;
    logic [0:0] req_auth_ok;
    logic [0:0] rsp_ready;
    logic [0:0] write_valid;
    logic [31:0] write_owner_id;
    logic [15:0] write_instance_id;
    logic [31:0] write_epoch;
    logic [31:0] write_task_id;
    logic [63:0] write_request_seq;
    logic [15:0] write_context_id;
    logic [31:0] write_generation;
    logic [63:0] write_staging_ref;
    logic [63:0] write_offset;
    logic [255:0] write_data;
    logic [31:0] write_keep;
    logic [0:0] write_last;
    logic [0:0] control_req_valid;
    logic [31:0] control_req_owner_id;
    logic [15:0] control_req_instance_id;
    logic [31:0] control_req_epoch;
    logic [31:0] control_req_task_id;
    logic [63:0] control_req_request_seq;
    logic [15:0] control_req_context_id;
    logic [31:0] control_req_generation;
    logic [15:0] control_req_service_version;
    logic [63:0] control_req_request_id;
    logic [7:0] control_req_operation;
    logic [63:0] control_req_staging_ref;
    logic [63:0] control_req_length;
    logic [31:0] control_req_policy_epoch;
    logic [0:0] control_req_auth_valid;
    logic [0:0] control_req_auth_ok;
    logic [0:0] control_rsp_ready;
  } aix_crypto_staging_w256_req_t;
  typedef struct packed {
    logic [0:0] req_ready;
    logic [0:0] rsp_valid;
    logic [31:0] rsp_owner_id;
    logic [15:0] rsp_instance_id;
    logic [31:0] rsp_epoch;
    logic [31:0] rsp_task_id;
    logic [63:0] rsp_request_seq;
    logic [15:0] rsp_context_id;
    logic [31:0] rsp_generation;
    logic [63:0] rsp_request_id;
    logic [15:0] rsp_status;
    logic [63:0] rsp_staging_ref;
    logic [63:0] rsp_reserved_bytes;
    logic [63:0] rsp_written_bytes;
    logic [7:0] rsp_state;
    logic [0:0] rsp_cleanup_done;
    logic [0:0] write_ready;
    logic [0:0] control_req_ready;
    logic [0:0] control_rsp_valid;
    logic [31:0] control_rsp_owner_id;
    logic [15:0] control_rsp_instance_id;
    logic [31:0] control_rsp_epoch;
    logic [31:0] control_rsp_task_id;
    logic [63:0] control_rsp_request_seq;
    logic [15:0] control_rsp_context_id;
    logic [31:0] control_rsp_generation;
    logic [63:0] control_rsp_request_id;
    logic [15:0] control_rsp_status;
    logic [7:0] control_rsp_state;
    logic [0:0] control_rsp_cleanup_done;
  } aix_crypto_staging_w256_rsp_t;
  typedef struct packed {
    logic [31:0] req_owner_id;
    logic [15:0] req_instance_id;
    logic [31:0] req_epoch;
    logic [31:0] req_task_id;
    logic [63:0] req_request_seq;
    logic [15:0] req_context_id;
    logic [31:0] req_generation;
    logic [15:0] req_service_version;
    logic [63:0] req_request_id;
    logic [7:0] req_operation;
    logic [63:0] req_staging_ref;
    logic [63:0] req_length;
    logic [31:0] req_policy_epoch;
    logic [0:0] req_auth_valid;
    logic [0:0] req_auth_ok;
  } aix_crypto_staging_w256_req_payload_t;
  typedef struct packed {
    logic [31:0] rsp_owner_id;
    logic [15:0] rsp_instance_id;
    logic [31:0] rsp_epoch;
    logic [31:0] rsp_task_id;
    logic [63:0] rsp_request_seq;
    logic [15:0] rsp_context_id;
    logic [31:0] rsp_generation;
    logic [63:0] rsp_request_id;
    logic [15:0] rsp_status;
    logic [63:0] rsp_staging_ref;
    logic [63:0] rsp_reserved_bytes;
    logic [63:0] rsp_written_bytes;
    logic [7:0] rsp_state;
    logic [0:0] rsp_cleanup_done;
  } aix_crypto_staging_w256_rsp_payload_t;
  typedef struct packed {
    logic [31:0] write_owner_id;
    logic [15:0] write_instance_id;
    logic [31:0] write_epoch;
    logic [31:0] write_task_id;
    logic [63:0] write_request_seq;
    logic [15:0] write_context_id;
    logic [31:0] write_generation;
    logic [63:0] write_staging_ref;
    logic [63:0] write_offset;
    logic [255:0] write_data;
    logic [31:0] write_keep;
    logic [0:0] write_last;
  } aix_crypto_staging_w256_write_payload_t;
  typedef struct packed {
    logic [31:0] control_req_owner_id;
    logic [15:0] control_req_instance_id;
    logic [31:0] control_req_epoch;
    logic [31:0] control_req_task_id;
    logic [63:0] control_req_request_seq;
    logic [15:0] control_req_context_id;
    logic [31:0] control_req_generation;
    logic [15:0] control_req_service_version;
    logic [63:0] control_req_request_id;
    logic [7:0] control_req_operation;
    logic [63:0] control_req_staging_ref;
    logic [63:0] control_req_length;
    logic [31:0] control_req_policy_epoch;
    logic [0:0] control_req_auth_valid;
    logic [0:0] control_req_auth_ok;
  } aix_crypto_staging_w256_control_req_payload_t;
  typedef struct packed {
    logic [31:0] control_rsp_owner_id;
    logic [15:0] control_rsp_instance_id;
    logic [31:0] control_rsp_epoch;
    logic [31:0] control_rsp_task_id;
    logic [63:0] control_rsp_request_seq;
    logic [15:0] control_rsp_context_id;
    logic [31:0] control_rsp_generation;
    logic [63:0] control_rsp_request_id;
    logic [15:0] control_rsp_status;
    logic [7:0] control_rsp_state;
    logic [0:0] control_rsp_cleanup_done;
  } aix_crypto_staging_w256_control_rsp_payload_t;
  typedef struct packed {
    logic [0:0] req_valid;
    logic [31:0] req_owner_id;
    logic [15:0] req_instance_id;
    logic [31:0] req_epoch;
    logic [31:0] req_task_id;
    logic [63:0] req_request_seq;
    logic [15:0] req_context_id;
    logic [31:0] req_generation;
    logic [15:0] req_service_version;
    logic [63:0] req_request_id;
    logic [7:0] req_operation;
    logic [63:0] req_staging_ref;
    logic [63:0] req_length;
    logic [31:0] req_policy_epoch;
    logic [0:0] req_auth_valid;
    logic [0:0] req_auth_ok;
    logic [0:0] rsp_ready;
    logic [0:0] write_valid;
    logic [31:0] write_owner_id;
    logic [15:0] write_instance_id;
    logic [31:0] write_epoch;
    logic [31:0] write_task_id;
    logic [63:0] write_request_seq;
    logic [15:0] write_context_id;
    logic [31:0] write_generation;
    logic [63:0] write_staging_ref;
    logic [63:0] write_offset;
    logic [511:0] write_data;
    logic [63:0] write_keep;
    logic [0:0] write_last;
    logic [0:0] control_req_valid;
    logic [31:0] control_req_owner_id;
    logic [15:0] control_req_instance_id;
    logic [31:0] control_req_epoch;
    logic [31:0] control_req_task_id;
    logic [63:0] control_req_request_seq;
    logic [15:0] control_req_context_id;
    logic [31:0] control_req_generation;
    logic [15:0] control_req_service_version;
    logic [63:0] control_req_request_id;
    logic [7:0] control_req_operation;
    logic [63:0] control_req_staging_ref;
    logic [63:0] control_req_length;
    logic [31:0] control_req_policy_epoch;
    logic [0:0] control_req_auth_valid;
    logic [0:0] control_req_auth_ok;
    logic [0:0] control_rsp_ready;
  } aix_crypto_staging_w512_req_t;
  typedef struct packed {
    logic [0:0] req_ready;
    logic [0:0] rsp_valid;
    logic [31:0] rsp_owner_id;
    logic [15:0] rsp_instance_id;
    logic [31:0] rsp_epoch;
    logic [31:0] rsp_task_id;
    logic [63:0] rsp_request_seq;
    logic [15:0] rsp_context_id;
    logic [31:0] rsp_generation;
    logic [63:0] rsp_request_id;
    logic [15:0] rsp_status;
    logic [63:0] rsp_staging_ref;
    logic [63:0] rsp_reserved_bytes;
    logic [63:0] rsp_written_bytes;
    logic [7:0] rsp_state;
    logic [0:0] rsp_cleanup_done;
    logic [0:0] write_ready;
    logic [0:0] control_req_ready;
    logic [0:0] control_rsp_valid;
    logic [31:0] control_rsp_owner_id;
    logic [15:0] control_rsp_instance_id;
    logic [31:0] control_rsp_epoch;
    logic [31:0] control_rsp_task_id;
    logic [63:0] control_rsp_request_seq;
    logic [15:0] control_rsp_context_id;
    logic [31:0] control_rsp_generation;
    logic [63:0] control_rsp_request_id;
    logic [15:0] control_rsp_status;
    logic [7:0] control_rsp_state;
    logic [0:0] control_rsp_cleanup_done;
  } aix_crypto_staging_w512_rsp_t;
  typedef struct packed {
    logic [31:0] req_owner_id;
    logic [15:0] req_instance_id;
    logic [31:0] req_epoch;
    logic [31:0] req_task_id;
    logic [63:0] req_request_seq;
    logic [15:0] req_context_id;
    logic [31:0] req_generation;
    logic [15:0] req_service_version;
    logic [63:0] req_request_id;
    logic [7:0] req_operation;
    logic [63:0] req_staging_ref;
    logic [63:0] req_length;
    logic [31:0] req_policy_epoch;
    logic [0:0] req_auth_valid;
    logic [0:0] req_auth_ok;
  } aix_crypto_staging_w512_req_payload_t;
  typedef struct packed {
    logic [31:0] rsp_owner_id;
    logic [15:0] rsp_instance_id;
    logic [31:0] rsp_epoch;
    logic [31:0] rsp_task_id;
    logic [63:0] rsp_request_seq;
    logic [15:0] rsp_context_id;
    logic [31:0] rsp_generation;
    logic [63:0] rsp_request_id;
    logic [15:0] rsp_status;
    logic [63:0] rsp_staging_ref;
    logic [63:0] rsp_reserved_bytes;
    logic [63:0] rsp_written_bytes;
    logic [7:0] rsp_state;
    logic [0:0] rsp_cleanup_done;
  } aix_crypto_staging_w512_rsp_payload_t;
  typedef struct packed {
    logic [31:0] write_owner_id;
    logic [15:0] write_instance_id;
    logic [31:0] write_epoch;
    logic [31:0] write_task_id;
    logic [63:0] write_request_seq;
    logic [15:0] write_context_id;
    logic [31:0] write_generation;
    logic [63:0] write_staging_ref;
    logic [63:0] write_offset;
    logic [511:0] write_data;
    logic [63:0] write_keep;
    logic [0:0] write_last;
  } aix_crypto_staging_w512_write_payload_t;
  typedef struct packed {
    logic [31:0] control_req_owner_id;
    logic [15:0] control_req_instance_id;
    logic [31:0] control_req_epoch;
    logic [31:0] control_req_task_id;
    logic [63:0] control_req_request_seq;
    logic [15:0] control_req_context_id;
    logic [31:0] control_req_generation;
    logic [15:0] control_req_service_version;
    logic [63:0] control_req_request_id;
    logic [7:0] control_req_operation;
    logic [63:0] control_req_staging_ref;
    logic [63:0] control_req_length;
    logic [31:0] control_req_policy_epoch;
    logic [0:0] control_req_auth_valid;
    logic [0:0] control_req_auth_ok;
  } aix_crypto_staging_w512_control_req_payload_t;
  typedef struct packed {
    logic [31:0] control_rsp_owner_id;
    logic [15:0] control_rsp_instance_id;
    logic [31:0] control_rsp_epoch;
    logic [31:0] control_rsp_task_id;
    logic [63:0] control_rsp_request_seq;
    logic [15:0] control_rsp_context_id;
    logic [31:0] control_rsp_generation;
    logic [63:0] control_rsp_request_id;
    logic [15:0] control_rsp_status;
    logic [7:0] control_rsp_state;
    logic [0:0] control_rsp_cleanup_done;
  } aix_crypto_staging_w512_control_rsp_payload_t;
  typedef aix_crypto_staging_w128_req_t aix_crypto_staging_req_t;
  typedef aix_crypto_staging_w128_rsp_t aix_crypto_staging_rsp_t;
  typedef aix_crypto_staging_w128_req_payload_t aix_crypto_staging_req_payload_t;
  typedef aix_crypto_staging_w128_rsp_payload_t aix_crypto_staging_rsp_payload_t;
  typedef aix_crypto_staging_w128_write_payload_t aix_crypto_staging_write_payload_t;
  typedef aix_crypto_staging_w128_control_req_payload_t aix_crypto_staging_control_req_payload_t;
  typedef aix_crypto_staging_w128_control_rsp_payload_t aix_crypto_staging_control_rsp_payload_t;
endpackage : aix_crypto_staging_pkg
